apiVersion: v1
kind: Secret
metadata:
    name: db-backup
    namespace: keycloak
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:7RaafhYbrTNIYY5WKw==,iv:g/4CngW+orOHWuBUbVN6hC90K4BAt5HTttcpwDDTFVU=,tag:qdKo214j5DCoPyPceJ0MUg==,type:str]
    secretKey: ENC[AES256_GCM,data:FSIXRwdzwffSZ1JFb//Q3P+TBSJGN4KJd0e7Zxk7ZepeIIfbuXcOfg==,iv:cacMIvRF11SUjzRHIMkM7yp87INiI+ozxAbj+soBZSw=,tag:e7jc9g2OWC4Pl1DMigvfXg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:43Z"
    mac: ENC[AES256_GCM,data:xdqVrMTF7k1QuQ+nEUGvkwIRZp0ZRg/yZ95kdLArt1W8jI502dDAlNpVzaCJQ4rPO1fz/kUs6YBjd4NXro7V2RAd7N+Ky0iJ2LU/NQcPJ11QsfPvCiAz8mZIR5ZkGdAp2/+0CR3m3XNPlmiRySruKFbCFQO5exG69ahXh1gHlNQ=,iv:88cUdDKdcTNlnD59OEjhJsL3snHjC6ux5cs58R8nlC4=,tag:9mOB5wHjyp2M/7CKYPcFtw==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9HMlphaXl9sPS4VxsMBxJ6xPOlPZrf8RJDYedDd8aFThc
            GglK8DDceJzDLdE23naoZHBxo9IzJJ/IWItmxfcC7D7KjrGC0eOEj8anPOOdkfoa
            TaGzYmvO4ivR9ACMZOsGbarHeNyOcrtDXOfogKlz7BJxQJe4b4Ljq98ig0grtZ8n
            cK2xyMP8Jvc4+4UlRZ08G+jHJ4M75oFK8TVqX3ehizgKVpsukbKd8N5WNsntcU65
            rBk57/xKK1mVl1vOtMDsNscw0hETIVy13K+VIaDVwLQqjdaonVzPiZFjhr8K39h9
            rCZwkZ4FZu4EB+zgWc/963Ec+46y5UqLCJZAhSLYIqMeRYOO1bUl4risCiWOONPO
            sgN/8cxm2KnjmIryUIC1093VQjqZkMNUqZfvmbkKRPKkCFfEmjeR+ROJh46A+pGz
            yi8uwziEpAXyY5r/gud1hXCELd6kqw2f9xdsdHtXuT5vF3JBkFobvEvnRU5GqAvO
            akq5jSgpjCdu2Bs+O0CheuIpRIGJQcB/zSXc2b06HnYIUcZd574XSpAl9i4nfHlI
            f+S82StvMvaJtwcTw3mjJKOWeQsoeC1bilGE0ZsyL29DPzK95PpIFcDJTI7xVuab
            QwgOHZBGQ8h0tPtNdbXYL0pYLSs33pkhOqf23Gj+myKEtISzXQLlDqbxJ8dw1FfU
            aAEJAhAtFTZXN0JlH0p7GzimcAk5xizVMcpK/cAFMUXRSMIDEoGVciXC2UBgFbbd
            dMaTGLXa4d1QXKy8MIovTqxWYbO2YU2QTzJONTMO0P4LxSqaMLZvAA5mwKduq86I
            bYIeM9mBnqbT
            =OGRC
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
