{
 "title": "Node Temperatures",
 "description": "Requires smartmontools & lm-sensors",
 "tags": [ "smartmon" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$host\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures Disks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartmon_attr_raw_value{name=\"temperature_celsius\",instance=\"$node\"}) by (device)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk Temperature - current",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "last_over_time(smartmon_attr_raw_value{name=\"temperature_celsius\",instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~\"platform_coretemp.*\",instance=\"$node\"}) by(sensor)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Temperature - current",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "last_over_time(node_hwmon_temp_celsius{chip=~\"platform_coretemp.*\",instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}