apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backup-mirror
    namespace: gitlab
type: Opaque
stringData:
    SOURCE_ACCESSKEY: ENC[AES256_GCM,data:5CgCiwzEurJk0GST7Ov999P/kjYaClmUtLs=,iv:/PqDw5/kDPfm3IcQR50TzNW3NZ1BqqtZ0CoTsoFrpA8=,tag:1Fh9ul7hHpzQzg9rmhrcJw==,type:str]
    SOURCE_SECRETKEY: ENC[AES256_GCM,data:eC4YgIbIGH3phXT+pc0kjPFchv6nrHtLokBkQPL5kTdZ3EFuM3mpw5VdFy9MNakXiG0o1AumwuE12X8E9HzZPQ==,iv:HCuEabkKRkJ/gwnio3vUs4qcH6HTNlw6TcNJr7jpgic=,tag:ENKLc5ChTBDkNIYaigmulA==,type:str]
    DESTINATION_ACCESSKEY: ENC[AES256_GCM,data:TzJr2H/ziUMIS5De0DwlNtIj7sI=,iv:pcZbH3+dG45BAjW3Vwrkq0jzwdaLbjw1H1Z/Apk5gIw=,tag:KX8m/7NR+VyqHHdYUBPGoQ==,type:str]
    DESTINATION_SECRETKEY: ENC[AES256_GCM,data:J7GBozEiiE6vRg1oUuFKTBII2Os6xIcOAKHYtGrjiXz6xFKoanr/Tg==,iv:NycDt5AHlqFgVJWmUsfCiteam/U+yIl2l4ijHJvvFww=,tag:cMmPAwgaqeGcVnHZ4CCSxg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:47Z"
    mac: ENC[AES256_GCM,data:V55c48cF8043vF6aDIIcpG+g+Jr/8PGYHTk2AVQQZ1FWg+XlHcm41MO84eRcFRSawM8Qy2vly1NCQZ/c2dc4PaNjMcu4kP83k9VJsV7CJE15TMUwBJJiaMdo1H6uEfpGac21omD9Gef8Cgp7aLhFqVuxlIdZD2hsL5j2ZuuqMTQ=,iv:xIljmz7bCp+5TVBs7oTkWvEgX0cATupOPYv8+baU8JY=,tag:AqUVvKEtMqlfJc6V9Qnr+A==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+LVJFiqlOlhcuenKQSnLmmQYkkScubA2QuzelGrbApY3T
            tWuBXHprcJPwBclzsVfkD8Bl95eEat6GtqxbG1GdDPRdIyrza15ZWHDfEM5RiyTW
            KfcDVGCquSYVvW7kOhhLGIU+zt0+wDOdNFNjxzWlvERy4p54W1hpSXlAQ+zfOJjt
            2xg7HsqT9ZrNMDG2JNQzShK9Lzp7nfAPIaMCtawgH0ABhvemLtK7XoQxjeCeR5el
            aR/ODqxtWn/A/ycU64Lyti29xDZ11rfOCMAR54FQOAWS4KWv9sPNXqPauLpzawZY
            vUJZUJPIaLmH74xD30S6SeM0mb/i/eldeYnbVAnlub/YOB8tFC8IJ5N9njP6QCfN
            wRNc3k9JDarL6u1phwuUMzV0Uxu8rpuxtDmNPmtZQMk8GVK9zqdw2wDG8bx0IH4i
            ys+xK7y4yywWYGuo1ht2gWUFmj2DJjLoAbpmwTErZgyVMtS247CIW7aUQwG/dIDu
            xiUCA3M514YCpWoWeTIEidf5CTVh/k2Ot9aG1YPHPqb7Lb878NT75JSVMFKeKRQJ
            WQF+0hueoxyGdivmxNnFhW8DpFvmYA6RIHfQXxH7WwElFjvaQAVs4fMq48XDvUXj
            To9Agb9hoIJkm3xh/algWJALSBxddXsSOC7eY+lmtMsIXPRosCsik/9ZKBhVDarU
            aAEJAhBSk5BA+oQP1SF204cd8D+YQm5W89izrekN2caJDUJIWMqizCgX1l25+Wk2
            wbijxhmgrgF9BctCcjfK+qZTMs/oUQXYKX+Km3qUJ9w/BxgPAllMzaDIdqx/0Qsp
            G/Vib/DzQiMu
            =OXEG
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
