---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-system
  namespace: flux-system
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: Exists
  podMetricsEndpoints:
    - port: http-prom
      metricRelabelings:
        - action: drop
          sourceLabels: [__name__]
          regex: "gotk_reconcile_duration_seconds_(bucket|sum|count)|controller_runtime_reconcile_time_seconds_(bucket|sum|count)|workqueue_(queue|work)_duration_seconds_(bucket|sum|count)"
