---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-garage
  namespace: gitlab
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./script/helm/garage
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 30m
  values:
    deployment:
      replicaCount: 1
    garage:
      replicationFactor: "1"
      rpcBindAddr: "0.0.0.0:3901"
      s3:
        api:
          bindAddr: ":3900"
        web:
          bindAddr: ":3901"
      admin:
        apiBindAddr: ":3903"
    persistence:
      data:
        size: 5Gi
      meta:
        size: 250Mi
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: gitlab-garage
              spec:
                template:
                  spec:
                    initContainers:
                      - name: garage-init
                        command:
                          - sh
                          - -c
                          - |
                            sed "s/__RPC_SECRET_REPLACE__/$RPC_SECRET/" /mnt/garage.toml > /mnt/etc/garage.toml
                            printf '\nadmin_token = "%s"\n' "$ADMIN_TOKEN" >> /mnt/etc/garage.toml
                        env:
                          - name: ADMIN_TOKEN
                            valueFrom:
                              secretKeyRef:
                                name: gitlab-garage-admin
                                key: adminToken
