---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicies/
  - secret.yaml
  - gitlab-object-storage-s3cmd.yaml
  - gitlab-object-storage.yaml
  - helmchart.yaml
