apiVersion: v1
kind: Secret
metadata:
    name: gitlab-garage-admin
    namespace: gitlab
type: Opaque
stringData:
    adminToken: ENC[AES256_GCM,data:UzVxxX+Qrvjo4QRo2eal92kuoCoFhLPRekq4Ny7xlDryr/lA5B0X07en0Evbusn2xBWK2N5srpcxzqY8g6PdGw==,iv:Lx+8LoonhkI79j8KenyvtNEL+5SR3DRNbY1SaGPDvfA=,tag:v6JAP0haD6m9zeH80OcpXA==,type:str]
sops:
    lastmodified: "2026-04-22T14:18:04Z"
    mac: ENC[AES256_GCM,data:RroLqL9LLftytG4YDDoBav2mdmJkp5mIecT/2ayu4v/jc2cZHt2FAGlxPW8rEVTIQzZ+wBwDdr4gdClGXzBgvadGLKYJKA19DcDKihgBS/r35oqqpwoisqCoWl1sfDgp/bYF8vXYHgtScOb4Z3T+Bk1pCJVCSRTy17yiTqWeTuE=,iv:Rn7tfMSkdPUTFNkfg8ab74BVQC4SuT5/xZbASuY3i88=,tag:PLfaHrwN2yJbIC+gqpWmuw==,type:str]
    pgp:
        - created_at: "2026-04-22T14:18:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAu/r8oMFZxUMPSMDkWdozh+MSufQEds+8CuN22i0U7bXQ
            GinV8j0DE+wcP/2m4Q6psVMim0yOF91NTOz8eYFxExGSqSlouXvtrq3iXycWBXy/
            OzZw9JntJ8CpmXQUXHXMBcIzy4OxpOCvcyYscmgnjxSHs/avodE7p7N77vePrJ8K
            HCoxKD+ePh7YnMArcumsnH/1/r1YWS8S3klvr+maClK4J3ZqIlNDjptp0WcrbDCc
            h9d+W8ffcm2lLs9IvtGymAT23NMUWbYQVHSxYS6OkfoMR2vU1dkxF+K/vrus7txN
            hyqP+XFR/u2mOtmMyS7cbtMi4lPtO9fLmpJtDLElUuPPX7F2pulqeaNZEUhm/D4J
            fUzN0Pn/Arb4R0xARaMR5ejXUHyHa/cXuLfcuTWNb1UPFN8Ls6A3IFeOhMY37B2C
            UCGXOm6Bw/7pSAf+waNaBpSuEkMxt2+rNWvLIuWXgSPmRO1cCV8bI1Ui1pdIq2NM
            3X1nGte0Fwj+DHwNYrxpUyZVT+gR9tdPNQeP83PyRip0OyLO0zFm5LR6H6e334Oj
            owQ4sGIiUH8GxEg8cIGdac58KexEqKkYaijzIE5UBSpA8xRgQpLWgXP28w/Ho0iU
            hah+0gqFMzjXJWCTaG3I1aDh/aDgMjlxNvK+AypLAR7Q4IMr2TdTgyM8/ozYkMXU
            aAEJAhCXYkNvfWoFYyu1UgERSl2JPgFDlamOc49fbdg3p655PZ7JRhUuTrKvFOpK
            pByTIkTdhPjKFkqb3vNPi3PakU1+n10tTw5Rc+9hQvtwZ8FwmvtaE9OMqzTE2kPW
            TrIA+/+kjitY
            =Y/ih
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
