apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Kw2uBjox780CM1kh3HpzbdRyh+5Ow0yuszE/PU54J5zOMtwiXNVhsku2dwiyOgWbhkCO/l8sGpN/p6kP9hRAiV4EXKeXdSoeWiHaJngly5qEKaE=,iv:6fwAYqtOXq5Q/l36QA5wK4U8Lwcm2pp6UM+KJ5pS5+8=,tag:f8qfSlEgjgr3v5KVtUsw0Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-24T13:00:08Z"
    mac: ENC[AES256_GCM,data:i2H9dj/tc0MALOATX5oT9IOwcOOeSaomNg3+8deElEhIv2iBvcgjeTBktFBjhPqB8UCWv6Z/yDNvIi2fldtUzawti4SOjk6XZxoI56s1GQ+2DNM6OlExhe4csTklmvielGxebdR3nH6mJZWLaf7vx1CeEYBVwlAGYxvp1r02+AE=,iv:k30RE8L4EbQ+zp5W7KNw+ft1mSDVt/4A435y15t+5OI=,tag:TPzs0l1a1FZcEVggEPJfdw==,type:str]
    pgp:
        - created_at: "2026-07-24T13:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//RzOC0cP+/9WLN8jPQ9Suwct2juRm6SJVYHKYnPYW9Mx/
            687E4cqlVSYHzojGFOuLHaLOHVYrchqb+PSNUGYzSR68x0usuodbUqIbggLd98VN
            Y5tfJI6FWn789kCW5SRid6QsqdxkCtHs+CfB/hW/STeAdS1z3bbRFQL6dfbtetyn
            3EnvW8CEqsoQNRItPENrmrkxXcXzUgAb56GngU56CLZPpRzBtp+e3pv8gWW8qJ7h
            +VX/kvaw8CntZZMEVcofxpLYHWxDLUPa8F1gLeVADEEtzB4FXwXcQLdo0u488MdC
            I580bxfcSTBRr59w655NYAM+u4Im41nGu7kbvYCq+Qpkjrgdb+PcGpdMIQwwVlzM
            1+oVedyN8DjPCvbPQ5zN13NVrC1HUYKHJ2J7YjE9tdZMOn2EQgGwjNRJPQWaSkDH
            d5pOgeO9a2ApAaF/Uk+etGwv3HkUIN+E6lw05w3X+kapxQ5YSgwkjzOsTS9uD609
            RFNLhwNlVGfNrauMmWisUUh+YUNbXmvASw5g3gUfn8QW4NFSC+8qwSbm31yfhciO
            SFN3Vn0bnXMIScbuIvRtSMe0K2oZmTbtqUHLbB5XiOztv/4dag+J4YdsDgkeYgmv
            7gF1vsq8QYrUez5MGwOQ/xMai5dn9x+KbU5Aa/6P8LEkvdgzcnq1fMeSOrdKDBHU
            aAEJAhC20ziGBVZLf5tUuHkDW1PKy3lfIwFo/K6WQLD3iellMSR1KhH4a10IgSh5
            otyHAs69ZiQ3u+aO4d3Ufr+W5uEePuVOFF4J6S4+dI6HLOIJ+CrOWi2uZa7wfeX2
            QoGjNB6Ebsq8
            =rh21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:g+M5FKP6Q7jrsjnEUmFlCw==,iv:T5lOASiXLDq1/VHnv+PDkW9sTkpiP18pTEdwPELlBM0=,tag:Imt4K6AHapbOW5di0L7wSA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-24T13:00:08Z"
    mac: ENC[AES256_GCM,data:i2H9dj/tc0MALOATX5oT9IOwcOOeSaomNg3+8deElEhIv2iBvcgjeTBktFBjhPqB8UCWv6Z/yDNvIi2fldtUzawti4SOjk6XZxoI56s1GQ+2DNM6OlExhe4csTklmvielGxebdR3nH6mJZWLaf7vx1CeEYBVwlAGYxvp1r02+AE=,iv:k30RE8L4EbQ+zp5W7KNw+ft1mSDVt/4A435y15t+5OI=,tag:TPzs0l1a1FZcEVggEPJfdw==,type:str]
    pgp:
        - created_at: "2026-07-24T13:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//RzOC0cP+/9WLN8jPQ9Suwct2juRm6SJVYHKYnPYW9Mx/
            687E4cqlVSYHzojGFOuLHaLOHVYrchqb+PSNUGYzSR68x0usuodbUqIbggLd98VN
            Y5tfJI6FWn789kCW5SRid6QsqdxkCtHs+CfB/hW/STeAdS1z3bbRFQL6dfbtetyn
            3EnvW8CEqsoQNRItPENrmrkxXcXzUgAb56GngU56CLZPpRzBtp+e3pv8gWW8qJ7h
            +VX/kvaw8CntZZMEVcofxpLYHWxDLUPa8F1gLeVADEEtzB4FXwXcQLdo0u488MdC
            I580bxfcSTBRr59w655NYAM+u4Im41nGu7kbvYCq+Qpkjrgdb+PcGpdMIQwwVlzM
            1+oVedyN8DjPCvbPQ5zN13NVrC1HUYKHJ2J7YjE9tdZMOn2EQgGwjNRJPQWaSkDH
            d5pOgeO9a2ApAaF/Uk+etGwv3HkUIN+E6lw05w3X+kapxQ5YSgwkjzOsTS9uD609
            RFNLhwNlVGfNrauMmWisUUh+YUNbXmvASw5g3gUfn8QW4NFSC+8qwSbm31yfhciO
            SFN3Vn0bnXMIScbuIvRtSMe0K2oZmTbtqUHLbB5XiOztv/4dag+J4YdsDgkeYgmv
            7gF1vsq8QYrUez5MGwOQ/xMai5dn9x+KbU5Aa/6P8LEkvdgzcnq1fMeSOrdKDBHU
            aAEJAhC20ziGBVZLf5tUuHkDW1PKy3lfIwFo/K6WQLD3iellMSR1KhH4a10IgSh5
            otyHAs69ZiQ3u+aO4d3Ufr+W5uEePuVOFF4J6S4+dI6HLOIJ+CrOWi2uZa7wfeX2
            QoGjNB6Ebsq8
            =rh21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:Kj+F/ES8DETAqPnw4R715MiFOOZxVhmW3e0oq9cWQQUNpAlgD8TVSXXH+5As76KCpcSWIdiFWBjQZBsxKzoxAv7Bp22CHsjLLyD61Cm2cTz3VBzr99TnxXJQ12ztdnD+qy36WZuLlOq6dQfBPPCwc4y21W1ptyOb3XXGalPrVh/Ic2bzjxyNPA5y9X27qdFQ2yGSFe5kkbPYtnvGCh5cWj56CpF9ybQDC+9aS5ut0PTiZWR5vkSbvJIf3GBs7Luoyz3zMpe6qxeK1hnlitbIxTO+PiXt3XmL4doALnbR1ixRk4u9pDJqjrgEegTyb4HdUWZdi5bfKWSI1tFDSBoEKK4wMO+YU60/5f2Wk2V7qXkBSLwgAQmW9f2pxt0DJa2cCAdnWkPmvxZ850IxG9sw3x428YV6lqgwrU6EbDOJ6w+fCUqAmK1NrSr4rL/KDenTnekcLd9CTkKJK2vL4uXvK9niUil8QCp5MuW1pTq9/XePk+9xgfsx4ZkxUtbrRfWQ6Fom3NqV/N33sr5hI/Nc87ceQv2+DoBUG43O1JcNmSH/uHB5ay0zrSTKb96KcIJExQEksEjlT84hatrfI54VibusXzlthji0+r8=,iv:K3FRj9HDdE/a1LMIlGVFX2/oel2FAuYch+2mMTB+5rQ=,tag:DJ94CkKVG8BeRWx7Yzi+zw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-24T13:00:08Z"
    mac: ENC[AES256_GCM,data:i2H9dj/tc0MALOATX5oT9IOwcOOeSaomNg3+8deElEhIv2iBvcgjeTBktFBjhPqB8UCWv6Z/yDNvIi2fldtUzawti4SOjk6XZxoI56s1GQ+2DNM6OlExhe4csTklmvielGxebdR3nH6mJZWLaf7vx1CeEYBVwlAGYxvp1r02+AE=,iv:k30RE8L4EbQ+zp5W7KNw+ft1mSDVt/4A435y15t+5OI=,tag:TPzs0l1a1FZcEVggEPJfdw==,type:str]
    pgp:
        - created_at: "2026-07-24T13:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//RzOC0cP+/9WLN8jPQ9Suwct2juRm6SJVYHKYnPYW9Mx/
            687E4cqlVSYHzojGFOuLHaLOHVYrchqb+PSNUGYzSR68x0usuodbUqIbggLd98VN
            Y5tfJI6FWn789kCW5SRid6QsqdxkCtHs+CfB/hW/STeAdS1z3bbRFQL6dfbtetyn
            3EnvW8CEqsoQNRItPENrmrkxXcXzUgAb56GngU56CLZPpRzBtp+e3pv8gWW8qJ7h
            +VX/kvaw8CntZZMEVcofxpLYHWxDLUPa8F1gLeVADEEtzB4FXwXcQLdo0u488MdC
            I580bxfcSTBRr59w655NYAM+u4Im41nGu7kbvYCq+Qpkjrgdb+PcGpdMIQwwVlzM
            1+oVedyN8DjPCvbPQ5zN13NVrC1HUYKHJ2J7YjE9tdZMOn2EQgGwjNRJPQWaSkDH
            d5pOgeO9a2ApAaF/Uk+etGwv3HkUIN+E6lw05w3X+kapxQ5YSgwkjzOsTS9uD609
            RFNLhwNlVGfNrauMmWisUUh+YUNbXmvASw5g3gUfn8QW4NFSC+8qwSbm31yfhciO
            SFN3Vn0bnXMIScbuIvRtSMe0K2oZmTbtqUHLbB5XiOztv/4dag+J4YdsDgkeYgmv
            7gF1vsq8QYrUez5MGwOQ/xMai5dn9x+KbU5Aa/6P8LEkvdgzcnq1fMeSOrdKDBHU
            aAEJAhC20ziGBVZLf5tUuHkDW1PKy3lfIwFo/K6WQLD3iellMSR1KhH4a10IgSh5
            otyHAs69ZiQ3u+aO4d3Ufr+W5uEePuVOFF4J6S4+dI6HLOIJ+CrOWi2uZa7wfeX2
            QoGjNB6Ebsq8
            =rh21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage-s3cmd
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:tZkZkh6u4wuCAkgQUAjdZy0oE2/virzl1XDFA4pwukHThrvTirDn7ivxWBEDZLdxhtIc2F7Vdx5zOwJT7pFP0CwZmgKJ/z2+nWIZHFgn231mXOAX+MvT285u67Ah0rEQNBbS9Dqb+z2vBbGfws29JWNHEmGyzWzkn6IE/RfBW53Mu9xYm+rxDK98vqDDZfnbA3S3Mrcv9x+Bw8Msh65o7PwvZX3UZXa0x1Pr57MDs2oX4xwuQZh/6wPlRdMBBu1etOfCGFGPkc66bGmhtxo+Fk7cYPxZ4apNIxnaggyXN30N8wFwCIrTaHxSuB0TcUhMuiEBZ1QvkCTnods7DQ0AjdQoTq8=,iv:XrE249K5jR7xr4XdEavyDGZWr3UpTZ8eFLL6S8unkW4=,tag:OssHN1Prx80Ev9gP8wq97g==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-24T13:00:08Z"
    mac: ENC[AES256_GCM,data:i2H9dj/tc0MALOATX5oT9IOwcOOeSaomNg3+8deElEhIv2iBvcgjeTBktFBjhPqB8UCWv6Z/yDNvIi2fldtUzawti4SOjk6XZxoI56s1GQ+2DNM6OlExhe4csTklmvielGxebdR3nH6mJZWLaf7vx1CeEYBVwlAGYxvp1r02+AE=,iv:k30RE8L4EbQ+zp5W7KNw+ft1mSDVt/4A435y15t+5OI=,tag:TPzs0l1a1FZcEVggEPJfdw==,type:str]
    pgp:
        - created_at: "2026-07-24T13:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//RzOC0cP+/9WLN8jPQ9Suwct2juRm6SJVYHKYnPYW9Mx/
            687E4cqlVSYHzojGFOuLHaLOHVYrchqb+PSNUGYzSR68x0usuodbUqIbggLd98VN
            Y5tfJI6FWn789kCW5SRid6QsqdxkCtHs+CfB/hW/STeAdS1z3bbRFQL6dfbtetyn
            3EnvW8CEqsoQNRItPENrmrkxXcXzUgAb56GngU56CLZPpRzBtp+e3pv8gWW8qJ7h
            +VX/kvaw8CntZZMEVcofxpLYHWxDLUPa8F1gLeVADEEtzB4FXwXcQLdo0u488MdC
            I580bxfcSTBRr59w655NYAM+u4Im41nGu7kbvYCq+Qpkjrgdb+PcGpdMIQwwVlzM
            1+oVedyN8DjPCvbPQ5zN13NVrC1HUYKHJ2J7YjE9tdZMOn2EQgGwjNRJPQWaSkDH
            d5pOgeO9a2ApAaF/Uk+etGwv3HkUIN+E6lw05w3X+kapxQ5YSgwkjzOsTS9uD609
            RFNLhwNlVGfNrauMmWisUUh+YUNbXmvASw5g3gUfn8QW4NFSC+8qwSbm31yfhciO
            SFN3Vn0bnXMIScbuIvRtSMe0K2oZmTbtqUHLbB5XiOztv/4dag+J4YdsDgkeYgmv
            7gF1vsq8QYrUez5MGwOQ/xMai5dn9x+KbU5Aa/6P8LEkvdgzcnq1fMeSOrdKDBHU
            aAEJAhC20ziGBVZLf5tUuHkDW1PKy3lfIwFo/K6WQLD3iellMSR1KhH4a10IgSh5
            otyHAs69ZiQ3u+aO4d3Ufr+W5uEePuVOFF4J6S4+dI6HLOIJ+CrOWi2uZa7wfeX2
            QoGjNB6Ebsq8
            =rh21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:QAZMHX3x9SAQG54O/A91DOcd+CpmEium2r+tfCiErTTEbji6HCUjkLyxPJPuDogs58uI0s+plaO6CBbgx5Py7OLXVP45bl+fUIN3ci1mJ+/wQxpBmckM+oEPBS1/+X8k+f75eZrRlvdIdN6tjd6ZXQ5vvnctPL+IAeJs/Ul/5Yo0A6wdblR/2H0NK6XpnObhdrAvXHgrtCRR2//CFvt57ZnjE1PwcEzvgI6NFp71MOWF+zhGK4ujjfyITJ8l7bAHbP5ODNqLaPZzRRBe75sbLypdMTev4tj3YSApYHPXApMa6g7+46IEfw87RXf4Hie4cPfb,iv:qmIHufHkzCnm4mbjcia9TS7ELfr9kD+Zv38IEHcWo5o=,tag:l+2yvxayUHgKJsvx7FAf3A==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-24T13:00:08Z"
    mac: ENC[AES256_GCM,data:i2H9dj/tc0MALOATX5oT9IOwcOOeSaomNg3+8deElEhIv2iBvcgjeTBktFBjhPqB8UCWv6Z/yDNvIi2fldtUzawti4SOjk6XZxoI56s1GQ+2DNM6OlExhe4csTklmvielGxebdR3nH6mJZWLaf7vx1CeEYBVwlAGYxvp1r02+AE=,iv:k30RE8L4EbQ+zp5W7KNw+ft1mSDVt/4A435y15t+5OI=,tag:TPzs0l1a1FZcEVggEPJfdw==,type:str]
    pgp:
        - created_at: "2026-07-24T13:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//RzOC0cP+/9WLN8jPQ9Suwct2juRm6SJVYHKYnPYW9Mx/
            687E4cqlVSYHzojGFOuLHaLOHVYrchqb+PSNUGYzSR68x0usuodbUqIbggLd98VN
            Y5tfJI6FWn789kCW5SRid6QsqdxkCtHs+CfB/hW/STeAdS1z3bbRFQL6dfbtetyn
            3EnvW8CEqsoQNRItPENrmrkxXcXzUgAb56GngU56CLZPpRzBtp+e3pv8gWW8qJ7h
            +VX/kvaw8CntZZMEVcofxpLYHWxDLUPa8F1gLeVADEEtzB4FXwXcQLdo0u488MdC
            I580bxfcSTBRr59w655NYAM+u4Im41nGu7kbvYCq+Qpkjrgdb+PcGpdMIQwwVlzM
            1+oVedyN8DjPCvbPQ5zN13NVrC1HUYKHJ2J7YjE9tdZMOn2EQgGwjNRJPQWaSkDH
            d5pOgeO9a2ApAaF/Uk+etGwv3HkUIN+E6lw05w3X+kapxQ5YSgwkjzOsTS9uD609
            RFNLhwNlVGfNrauMmWisUUh+YUNbXmvASw5g3gUfn8QW4NFSC+8qwSbm31yfhciO
            SFN3Vn0bnXMIScbuIvRtSMe0K2oZmTbtqUHLbB5XiOztv/4dag+J4YdsDgkeYgmv
            7gF1vsq8QYrUez5MGwOQ/xMai5dn9x+KbU5Aa/6P8LEkvdgzcnq1fMeSOrdKDBHU
            aAEJAhC20ziGBVZLf5tUuHkDW1PKy3lfIwFo/K6WQLD3iellMSR1KhH4a10IgSh5
            otyHAs69ZiQ3u+aO4d3Ufr+W5uEePuVOFF4J6S4+dI6HLOIJ+CrOWi2uZa7wfeX2
            QoGjNB6Ebsq8
            =rh21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:urNRKWe1vNdzTS3Mff/ir3IXXhzeMvp7GZPgL0m86mnuftnsgd/aNswzSL62TqrN1XUnkiB2BUkhyL0zUhQCwCK8HbECt/iNdF4rOdSkwZv0BW4BXeKW5qn2+aIHVhTwmG/ltacMwudjdV697sEOklwjYc7psny+BTVzvKJfGqWgavIakgZMU1xycOgCXAGQZzy1HQdPN3AM8J50CMIo2ZUvUrMPGBsu/BYpo8EztnJ2ZjwNiXTPCQb3xcGrLZeEvVqlvgv3bb1hZAouofmAySRagR66Eoz08+j588L9tzHDWZX3SjJLlZNrzMS+uY+SdR6atttWe19Y0ymU2icnf5TDzOh6di4EeGhdqnB7YzUCU/ybFoz6YiZd80Pb1eq+,iv:3antCNBg6VwL17X3pTOXElPsw4boupV2Wua/uhABEGg=,tag:AY+KYejSDNiA6kRoQzVBOw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-24T13:00:08Z"
    mac: ENC[AES256_GCM,data:i2H9dj/tc0MALOATX5oT9IOwcOOeSaomNg3+8deElEhIv2iBvcgjeTBktFBjhPqB8UCWv6Z/yDNvIi2fldtUzawti4SOjk6XZxoI56s1GQ+2DNM6OlExhe4csTklmvielGxebdR3nH6mJZWLaf7vx1CeEYBVwlAGYxvp1r02+AE=,iv:k30RE8L4EbQ+zp5W7KNw+ft1mSDVt/4A435y15t+5OI=,tag:TPzs0l1a1FZcEVggEPJfdw==,type:str]
    pgp:
        - created_at: "2026-07-24T13:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//RzOC0cP+/9WLN8jPQ9Suwct2juRm6SJVYHKYnPYW9Mx/
            687E4cqlVSYHzojGFOuLHaLOHVYrchqb+PSNUGYzSR68x0usuodbUqIbggLd98VN
            Y5tfJI6FWn789kCW5SRid6QsqdxkCtHs+CfB/hW/STeAdS1z3bbRFQL6dfbtetyn
            3EnvW8CEqsoQNRItPENrmrkxXcXzUgAb56GngU56CLZPpRzBtp+e3pv8gWW8qJ7h
            +VX/kvaw8CntZZMEVcofxpLYHWxDLUPa8F1gLeVADEEtzB4FXwXcQLdo0u488MdC
            I580bxfcSTBRr59w655NYAM+u4Im41nGu7kbvYCq+Qpkjrgdb+PcGpdMIQwwVlzM
            1+oVedyN8DjPCvbPQ5zN13NVrC1HUYKHJ2J7YjE9tdZMOn2EQgGwjNRJPQWaSkDH
            d5pOgeO9a2ApAaF/Uk+etGwv3HkUIN+E6lw05w3X+kapxQ5YSgwkjzOsTS9uD609
            RFNLhwNlVGfNrauMmWisUUh+YUNbXmvASw5g3gUfn8QW4NFSC+8qwSbm31yfhciO
            SFN3Vn0bnXMIScbuIvRtSMe0K2oZmTbtqUHLbB5XiOztv/4dag+J4YdsDgkeYgmv
            7gF1vsq8QYrUez5MGwOQ/xMai5dn9x+KbU5Aa/6P8LEkvdgzcnq1fMeSOrdKDBHU
            aAEJAhC20ziGBVZLf5tUuHkDW1PKy3lfIwFo/K6WQLD3iellMSR1KhH4a10IgSh5
            otyHAs69ZiQ3u+aO4d3Ufr+W5uEePuVOFF4J6S4+dI6HLOIJ+CrOWi2uZa7wfeX2
            QoGjNB6Ebsq8
            =rh21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backup-mirror
    namespace: gitlab
type: Opaque
stringData:
    DESTINATION_ACCESSKEY: ENC[AES256_GCM,data:FxHHCopFMoAvJfsWaV5zc9jFxz0=,iv:jncJPLmLfqHl6rlPz6VnuyCvD2eIH28UvClhXbiIiZY=,tag:9OmsYQmBA6L7zaMIpeoW3A==,type:str]
    DESTINATION_SECRETKEY: ENC[AES256_GCM,data:dOACZjFZ38VgQl4vAsCyA9JgJIQmANdjfce6ZZHB9G8gE5iQ1fCb4Q==,iv:mW15iGsHpQctPoNOxX48ziI3TGMXkhZ/ckGVmsE7zGQ=,tag:RB1WPWiw/nZxYnOBJVfJvQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-24T13:00:08Z"
    mac: ENC[AES256_GCM,data:i2H9dj/tc0MALOATX5oT9IOwcOOeSaomNg3+8deElEhIv2iBvcgjeTBktFBjhPqB8UCWv6Z/yDNvIi2fldtUzawti4SOjk6XZxoI56s1GQ+2DNM6OlExhe4csTklmvielGxebdR3nH6mJZWLaf7vx1CeEYBVwlAGYxvp1r02+AE=,iv:k30RE8L4EbQ+zp5W7KNw+ft1mSDVt/4A435y15t+5OI=,tag:TPzs0l1a1FZcEVggEPJfdw==,type:str]
    pgp:
        - created_at: "2026-07-24T13:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//RzOC0cP+/9WLN8jPQ9Suwct2juRm6SJVYHKYnPYW9Mx/
            687E4cqlVSYHzojGFOuLHaLOHVYrchqb+PSNUGYzSR68x0usuodbUqIbggLd98VN
            Y5tfJI6FWn789kCW5SRid6QsqdxkCtHs+CfB/hW/STeAdS1z3bbRFQL6dfbtetyn
            3EnvW8CEqsoQNRItPENrmrkxXcXzUgAb56GngU56CLZPpRzBtp+e3pv8gWW8qJ7h
            +VX/kvaw8CntZZMEVcofxpLYHWxDLUPa8F1gLeVADEEtzB4FXwXcQLdo0u488MdC
            I580bxfcSTBRr59w655NYAM+u4Im41nGu7kbvYCq+Qpkjrgdb+PcGpdMIQwwVlzM
            1+oVedyN8DjPCvbPQ5zN13NVrC1HUYKHJ2J7YjE9tdZMOn2EQgGwjNRJPQWaSkDH
            d5pOgeO9a2ApAaF/Uk+etGwv3HkUIN+E6lw05w3X+kapxQ5YSgwkjzOsTS9uD609
            RFNLhwNlVGfNrauMmWisUUh+YUNbXmvASw5g3gUfn8QW4NFSC+8qwSbm31yfhciO
            SFN3Vn0bnXMIScbuIvRtSMe0K2oZmTbtqUHLbB5XiOztv/4dag+J4YdsDgkeYgmv
            7gF1vsq8QYrUez5MGwOQ/xMai5dn9x+KbU5Aa/6P8LEkvdgzcnq1fMeSOrdKDBHU
            aAEJAhC20ziGBVZLf5tUuHkDW1PKy3lfIwFo/K6WQLD3iellMSR1KhH4a10IgSh5
            otyHAs69ZiQ3u+aO4d3Ufr+W5uEePuVOFF4J6S4+dI6HLOIJ+CrOWi2uZa7wfeX2
            QoGjNB6Ebsq8
            =rh21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
