apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:+6ZkWluq18WqQDwNAqpyCK+0bIOTvFUmuE85NkV7Ke0rPkOi+k40SLWOWt00dmZYePIt07aL7rSLDa/6JqYfReoPC4J60byUozvdg0G3Oo+XLdU=,iv:Mptm0nnIG877UtufwFMRvo65mYlJyJD/8FcOuSZlfc0=,tag:Nlth2z35gr80046dWQy6Kw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:09:05Z"
    mac: ENC[AES256_GCM,data:RxTMCiAQv9vIn6BYhN6oTv2lPKu+t70Ko6Xt/Y9GdozTaAH+rqEj6tVtDBeoowZ28IcOEfadA/L28o6/QCIFGr4INlUBj8DVvha7kKjDBGjc/NWz4Rx2LcvBa+vNNlGGYpcenGr/GsMnhnVc2hQY9HJBCiQ6C2xXc57X8ZGFMqE=,iv:GpyLHRA5EWi3y6kXreLBtyP4RviSsnnua7GyPLM0P/I=,tag:Uek+/nHviY07JK4QZ7OQ3w==,type:str]
    pgp:
        - created_at: "2026-07-24T13:05:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAsFSl811a7uGa0ZJPP8bXAemtGvdwWUeYlsJeJw9Y7wFB
            0/HCevaj19l1bGnu+vtHuth86aGjPhjscUbe2GyZd6FAMWynMLUCF4RKLBWGx5GC
            5x5+pX6PA9PQtS04MCahjwMC6imwGSnSYu5V4iCZpVSBLMFGqurMjwlBoH3iRpLe
            Mib0JqlRdU7ej841cMIVustn5V96Ufo3LJQdlewK6RgcgM7a+9XUIRlj6mlj4bd1
            fy6Zha92aYtcN3wjjd3tyyWzyrUxM2fHBpksk5ef2CbzXdwyjuSpUngDxDBaKc6L
            INaesu1vRm9FakSZVjRT9HmlhhLCn5EQ/TkO0GzBn/kcsnvjtRLvAPcWVPvfpp0P
            gxLNVr0fwYA9lzrAhy9W55YbO7LDpc6OJEtZbO49v2hoX0heFLb+5OvuV3jC7gig
            5EkyGWSOymDdPCN/r8DkMNsSGfZxI2vnjDwU4afPzIcqk/DKpqAczjGIWiKOolfY
            DeWNCe3nOEsdu0TusPa7+tpIx7aFKzR4jLK4gb1mfwXdACq02e9Ze3RHIJtVUZB8
            dMSB56lA6B137ar5UP0K9adkjV9lXxpCxt5e0wKhEeoB+ce/YHSqlhNunSbetJh2
            1DXRrYnVQmNhjWX6nyfhsyP9f6yNs8fhHie0zecQbkZvNwZY6vNugiE6ExWiJgXU
            aAEJAhCWnMYRtRXKaZ5SyljhWsQyP2sjoxSurqFgS6ocQ96/ZU0ArwNXyxvKb6jX
            2C+ZxMzFfftaaslK66rYRHF8sFGq3vyDYdcysESB+Gq7/Fg6Wpe/GWwBel/QsW3b
            G1dTOUWF3xwv
            =zIXa
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7iGLaYRX94BipNtPR7/F7A==,iv:xl9iTpfXd5I0h3F226Jhsya8Gm9b3nZ72oP+NZToqtA=,tag:tmPcbm5Wsq0E9+8NjmXhEg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:09:05Z"
    mac: ENC[AES256_GCM,data:RxTMCiAQv9vIn6BYhN6oTv2lPKu+t70Ko6Xt/Y9GdozTaAH+rqEj6tVtDBeoowZ28IcOEfadA/L28o6/QCIFGr4INlUBj8DVvha7kKjDBGjc/NWz4Rx2LcvBa+vNNlGGYpcenGr/GsMnhnVc2hQY9HJBCiQ6C2xXc57X8ZGFMqE=,iv:GpyLHRA5EWi3y6kXreLBtyP4RviSsnnua7GyPLM0P/I=,tag:Uek+/nHviY07JK4QZ7OQ3w==,type:str]
    pgp:
        - created_at: "2026-07-24T13:05:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAsFSl811a7uGa0ZJPP8bXAemtGvdwWUeYlsJeJw9Y7wFB
            0/HCevaj19l1bGnu+vtHuth86aGjPhjscUbe2GyZd6FAMWynMLUCF4RKLBWGx5GC
            5x5+pX6PA9PQtS04MCahjwMC6imwGSnSYu5V4iCZpVSBLMFGqurMjwlBoH3iRpLe
            Mib0JqlRdU7ej841cMIVustn5V96Ufo3LJQdlewK6RgcgM7a+9XUIRlj6mlj4bd1
            fy6Zha92aYtcN3wjjd3tyyWzyrUxM2fHBpksk5ef2CbzXdwyjuSpUngDxDBaKc6L
            INaesu1vRm9FakSZVjRT9HmlhhLCn5EQ/TkO0GzBn/kcsnvjtRLvAPcWVPvfpp0P
            gxLNVr0fwYA9lzrAhy9W55YbO7LDpc6OJEtZbO49v2hoX0heFLb+5OvuV3jC7gig
            5EkyGWSOymDdPCN/r8DkMNsSGfZxI2vnjDwU4afPzIcqk/DKpqAczjGIWiKOolfY
            DeWNCe3nOEsdu0TusPa7+tpIx7aFKzR4jLK4gb1mfwXdACq02e9Ze3RHIJtVUZB8
            dMSB56lA6B137ar5UP0K9adkjV9lXxpCxt5e0wKhEeoB+ce/YHSqlhNunSbetJh2
            1DXRrYnVQmNhjWX6nyfhsyP9f6yNs8fhHie0zecQbkZvNwZY6vNugiE6ExWiJgXU
            aAEJAhCWnMYRtRXKaZ5SyljhWsQyP2sjoxSurqFgS6ocQ96/ZU0ArwNXyxvKb6jX
            2C+ZxMzFfftaaslK66rYRHF8sFGq3vyDYdcysESB+Gq7/Fg6Wpe/GWwBel/QsW3b
            G1dTOUWF3xwv
            =zIXa
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:KNAJKDrdCriLFPXmZiO/lmrnywQhMgLhCcJlfxem/YTeLAOvGQXelVNDuMzWE68vYKj9m1Q/IK+rpZvos9UT/GKNhNcMyr/RAP8J6Azqds2q+uvuwwmyJG1tn8feiXddjKLcmKbQa8MpdI7GIeoj3911Hqm/PRiUgXxPBzU9Oiv5nwIlqvCx4OOqP3WU4YZQcEY/DNSscZvcmuUs/ggXa3SmHpkZwK/fM6NoS8N1EpmGlZoJI+exmYICKGtIO24/vNG249l1nVGBidZq/i7YMDRRfpB6MWwXDwfe/EOWsnAEltGIjQmXDue7mKSCRe8FMH/z9NrTmY3TwHVucja7Bn1cNSphlkEnQ4TVlcnsiasrUomJY5azKbQEeo6LrgtLzOdPfvnkFOqWmBV3xyq2CjQ3jaiKsgEoGwYzP+BXBaNHkOUkkfpvmP5IJGAhQ9Gb4tH7dcsXpw2EcLTlBS2BNncLGlBEFxkIstmYZMJhvw6q6ooDwRvfsMdFbvsQdlRleeND1s+2t1/zHWIAmAR5oWYQ0rFJ3mjHzi7XRvS2wA1jNBORrD2tFUEK/CBM7Lt9HqT7Sl7xkDNsLhrRg8JtGdUetTdrR1rm4sylGsYP9hyBSu9RgXR1HXPC9vB8naC1CYjeuX4IFahBGpIbyzMfDcQMXRnfc9cW,iv:iKsL9y3d83zHKIbsbEmH8ZgE7wQ/7QkVzPGLbjGnzO0=,tag:+7yBRSN0qrHhdrZI+OxYzg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:09:05Z"
    mac: ENC[AES256_GCM,data:RxTMCiAQv9vIn6BYhN6oTv2lPKu+t70Ko6Xt/Y9GdozTaAH+rqEj6tVtDBeoowZ28IcOEfadA/L28o6/QCIFGr4INlUBj8DVvha7kKjDBGjc/NWz4Rx2LcvBa+vNNlGGYpcenGr/GsMnhnVc2hQY9HJBCiQ6C2xXc57X8ZGFMqE=,iv:GpyLHRA5EWi3y6kXreLBtyP4RviSsnnua7GyPLM0P/I=,tag:Uek+/nHviY07JK4QZ7OQ3w==,type:str]
    pgp:
        - created_at: "2026-07-24T13:05:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAsFSl811a7uGa0ZJPP8bXAemtGvdwWUeYlsJeJw9Y7wFB
            0/HCevaj19l1bGnu+vtHuth86aGjPhjscUbe2GyZd6FAMWynMLUCF4RKLBWGx5GC
            5x5+pX6PA9PQtS04MCahjwMC6imwGSnSYu5V4iCZpVSBLMFGqurMjwlBoH3iRpLe
            Mib0JqlRdU7ej841cMIVustn5V96Ufo3LJQdlewK6RgcgM7a+9XUIRlj6mlj4bd1
            fy6Zha92aYtcN3wjjd3tyyWzyrUxM2fHBpksk5ef2CbzXdwyjuSpUngDxDBaKc6L
            INaesu1vRm9FakSZVjRT9HmlhhLCn5EQ/TkO0GzBn/kcsnvjtRLvAPcWVPvfpp0P
            gxLNVr0fwYA9lzrAhy9W55YbO7LDpc6OJEtZbO49v2hoX0heFLb+5OvuV3jC7gig
            5EkyGWSOymDdPCN/r8DkMNsSGfZxI2vnjDwU4afPzIcqk/DKpqAczjGIWiKOolfY
            DeWNCe3nOEsdu0TusPa7+tpIx7aFKzR4jLK4gb1mfwXdACq02e9Ze3RHIJtVUZB8
            dMSB56lA6B137ar5UP0K9adkjV9lXxpCxt5e0wKhEeoB+ce/YHSqlhNunSbetJh2
            1DXRrYnVQmNhjWX6nyfhsyP9f6yNs8fhHie0zecQbkZvNwZY6vNugiE6ExWiJgXU
            aAEJAhCWnMYRtRXKaZ5SyljhWsQyP2sjoxSurqFgS6ocQ96/ZU0ArwNXyxvKb6jX
            2C+ZxMzFfftaaslK66rYRHF8sFGq3vyDYdcysESB+Gq7/Fg6Wpe/GWwBel/QsW3b
            G1dTOUWF3xwv
            =zIXa
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage-s3cmd
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:MViQblKOSHCfcz4PpO+hFaHNo7LyFl48iRbVxal0VR4SQEJRc4I5xahtHeA7ggBt3l5UtwZ22CMI9KyqOzYTNDyta69cSEHkk3Ha4NNvUHxLKMIWOgiwvWthDL/5ac2MjG5G5jq3x5SNRhB+eybuBJ8kWG7tvYwRjhxeCQCy34TYYssB+LdMdhYpyM7itAst10SW1uVk5Z22mYSjY0mVGk/c+f+NfaqYNYAH4XAfScG6rLvOWBWdJurVX/lMPlkvJYOn51FEu2SL6Ax676JnaTjdJSrqjq2AfvrUeq4GZNVB3fo9cN7a9uDMCZA87boirB+McZM5b01YPMFG2Rt1Gd38ew0=,iv:YkPiOmXO17DW77yCzaVDyYhDgH/xT+L5qthQMGEjlUk=,tag:JaU6+/7MJG1UE4W27WoIrQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:09:05Z"
    mac: ENC[AES256_GCM,data:RxTMCiAQv9vIn6BYhN6oTv2lPKu+t70Ko6Xt/Y9GdozTaAH+rqEj6tVtDBeoowZ28IcOEfadA/L28o6/QCIFGr4INlUBj8DVvha7kKjDBGjc/NWz4Rx2LcvBa+vNNlGGYpcenGr/GsMnhnVc2hQY9HJBCiQ6C2xXc57X8ZGFMqE=,iv:GpyLHRA5EWi3y6kXreLBtyP4RviSsnnua7GyPLM0P/I=,tag:Uek+/nHviY07JK4QZ7OQ3w==,type:str]
    pgp:
        - created_at: "2026-07-24T13:05:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAsFSl811a7uGa0ZJPP8bXAemtGvdwWUeYlsJeJw9Y7wFB
            0/HCevaj19l1bGnu+vtHuth86aGjPhjscUbe2GyZd6FAMWynMLUCF4RKLBWGx5GC
            5x5+pX6PA9PQtS04MCahjwMC6imwGSnSYu5V4iCZpVSBLMFGqurMjwlBoH3iRpLe
            Mib0JqlRdU7ej841cMIVustn5V96Ufo3LJQdlewK6RgcgM7a+9XUIRlj6mlj4bd1
            fy6Zha92aYtcN3wjjd3tyyWzyrUxM2fHBpksk5ef2CbzXdwyjuSpUngDxDBaKc6L
            INaesu1vRm9FakSZVjRT9HmlhhLCn5EQ/TkO0GzBn/kcsnvjtRLvAPcWVPvfpp0P
            gxLNVr0fwYA9lzrAhy9W55YbO7LDpc6OJEtZbO49v2hoX0heFLb+5OvuV3jC7gig
            5EkyGWSOymDdPCN/r8DkMNsSGfZxI2vnjDwU4afPzIcqk/DKpqAczjGIWiKOolfY
            DeWNCe3nOEsdu0TusPa7+tpIx7aFKzR4jLK4gb1mfwXdACq02e9Ze3RHIJtVUZB8
            dMSB56lA6B137ar5UP0K9adkjV9lXxpCxt5e0wKhEeoB+ce/YHSqlhNunSbetJh2
            1DXRrYnVQmNhjWX6nyfhsyP9f6yNs8fhHie0zecQbkZvNwZY6vNugiE6ExWiJgXU
            aAEJAhCWnMYRtRXKaZ5SyljhWsQyP2sjoxSurqFgS6ocQ96/ZU0ArwNXyxvKb6jX
            2C+ZxMzFfftaaslK66rYRHF8sFGq3vyDYdcysESB+Gq7/Fg6Wpe/GWwBel/QsW3b
            G1dTOUWF3xwv
            =zIXa
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:VJPK3oGU15gB80xlmpWMLNDeirnQ2FheZhxBVE/2YUcobpazrQvABKeVykTN0nAymvQsO0YwJGsfB7CUprHxWL5O3HzcezmIK43YDqRgVErBDAwcMkT1rad328UjkNTfvs5a5SCYV2mKiLcs5fTPjdeQVu1D337dGXc6ucKkwlOjnMzPIV+fNJ4MhoHAiufpf2+ZW/Ajtekf/sGm0U1+X2gQPp/MJgchkKsQwEEkNp4vY/ZAl9rJQpMki5mDQjv/NZjKCo6Z4yVpCO1+IfGqGVGElrQVDUW7bCmjm+PDExPa6BgZKWNIHkofoakoeAUR5+0G,iv:8s0a6IfjVFFmTps0qbFUmAnscbuc904zqQR65SnZBjk=,tag:4Qt6T7rp/QS9VuJ6b4HZHA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:09:05Z"
    mac: ENC[AES256_GCM,data:RxTMCiAQv9vIn6BYhN6oTv2lPKu+t70Ko6Xt/Y9GdozTaAH+rqEj6tVtDBeoowZ28IcOEfadA/L28o6/QCIFGr4INlUBj8DVvha7kKjDBGjc/NWz4Rx2LcvBa+vNNlGGYpcenGr/GsMnhnVc2hQY9HJBCiQ6C2xXc57X8ZGFMqE=,iv:GpyLHRA5EWi3y6kXreLBtyP4RviSsnnua7GyPLM0P/I=,tag:Uek+/nHviY07JK4QZ7OQ3w==,type:str]
    pgp:
        - created_at: "2026-07-24T13:05:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAsFSl811a7uGa0ZJPP8bXAemtGvdwWUeYlsJeJw9Y7wFB
            0/HCevaj19l1bGnu+vtHuth86aGjPhjscUbe2GyZd6FAMWynMLUCF4RKLBWGx5GC
            5x5+pX6PA9PQtS04MCahjwMC6imwGSnSYu5V4iCZpVSBLMFGqurMjwlBoH3iRpLe
            Mib0JqlRdU7ej841cMIVustn5V96Ufo3LJQdlewK6RgcgM7a+9XUIRlj6mlj4bd1
            fy6Zha92aYtcN3wjjd3tyyWzyrUxM2fHBpksk5ef2CbzXdwyjuSpUngDxDBaKc6L
            INaesu1vRm9FakSZVjRT9HmlhhLCn5EQ/TkO0GzBn/kcsnvjtRLvAPcWVPvfpp0P
            gxLNVr0fwYA9lzrAhy9W55YbO7LDpc6OJEtZbO49v2hoX0heFLb+5OvuV3jC7gig
            5EkyGWSOymDdPCN/r8DkMNsSGfZxI2vnjDwU4afPzIcqk/DKpqAczjGIWiKOolfY
            DeWNCe3nOEsdu0TusPa7+tpIx7aFKzR4jLK4gb1mfwXdACq02e9Ze3RHIJtVUZB8
            dMSB56lA6B137ar5UP0K9adkjV9lXxpCxt5e0wKhEeoB+ce/YHSqlhNunSbetJh2
            1DXRrYnVQmNhjWX6nyfhsyP9f6yNs8fhHie0zecQbkZvNwZY6vNugiE6ExWiJgXU
            aAEJAhCWnMYRtRXKaZ5SyljhWsQyP2sjoxSurqFgS6ocQ96/ZU0ArwNXyxvKb6jX
            2C+ZxMzFfftaaslK66rYRHF8sFGq3vyDYdcysESB+Gq7/Fg6Wpe/GWwBel/QsW3b
            G1dTOUWF3xwv
            =zIXa
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:mfQQhS5rTIgfVsXa/XpVnhl9C74sCIHaKXytNRtEk/wRTujHdnU5MnBWrnJePJmPOZDPt/ZNExtDpOcyZRQRwWobj5mk4X0gLb2ROi3st2C9JM7Hjob/mrJjEzpsRgxq7wYM3UuP9ed6ucAPYk3H8JuTJRkqpZ/gHBrOPtvwBLB6T1Wd/l3ypEOR0ZuDJ9uZy67HXNLy9NxiO2spioTF8SwG6fE0HmOBVR5bo5TZvme+ZggcYZXw/QNUqMaObBxGipMVz8qW71XGOebGHbyQUAdj+Hr4vkAutKNzdAc5NEP/lkA3o3W3Xp3FT/SqBR8ZTDXGafcwSWtJlD13axHU8jIA/6PoH8DPKKi9Oxc8rUcfT0iBTE27+HqNy0Cd9ro6,iv:0eOzPQRjayQG87zFJ4wYeCAMo6GTiAHq9UwhKt/25Zc=,tag:JH3D3TOqtXGrF5a6S2zZww==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:09:05Z"
    mac: ENC[AES256_GCM,data:RxTMCiAQv9vIn6BYhN6oTv2lPKu+t70Ko6Xt/Y9GdozTaAH+rqEj6tVtDBeoowZ28IcOEfadA/L28o6/QCIFGr4INlUBj8DVvha7kKjDBGjc/NWz4Rx2LcvBa+vNNlGGYpcenGr/GsMnhnVc2hQY9HJBCiQ6C2xXc57X8ZGFMqE=,iv:GpyLHRA5EWi3y6kXreLBtyP4RviSsnnua7GyPLM0P/I=,tag:Uek+/nHviY07JK4QZ7OQ3w==,type:str]
    pgp:
        - created_at: "2026-07-24T13:05:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAsFSl811a7uGa0ZJPP8bXAemtGvdwWUeYlsJeJw9Y7wFB
            0/HCevaj19l1bGnu+vtHuth86aGjPhjscUbe2GyZd6FAMWynMLUCF4RKLBWGx5GC
            5x5+pX6PA9PQtS04MCahjwMC6imwGSnSYu5V4iCZpVSBLMFGqurMjwlBoH3iRpLe
            Mib0JqlRdU7ej841cMIVustn5V96Ufo3LJQdlewK6RgcgM7a+9XUIRlj6mlj4bd1
            fy6Zha92aYtcN3wjjd3tyyWzyrUxM2fHBpksk5ef2CbzXdwyjuSpUngDxDBaKc6L
            INaesu1vRm9FakSZVjRT9HmlhhLCn5EQ/TkO0GzBn/kcsnvjtRLvAPcWVPvfpp0P
            gxLNVr0fwYA9lzrAhy9W55YbO7LDpc6OJEtZbO49v2hoX0heFLb+5OvuV3jC7gig
            5EkyGWSOymDdPCN/r8DkMNsSGfZxI2vnjDwU4afPzIcqk/DKpqAczjGIWiKOolfY
            DeWNCe3nOEsdu0TusPa7+tpIx7aFKzR4jLK4gb1mfwXdACq02e9Ze3RHIJtVUZB8
            dMSB56lA6B137ar5UP0K9adkjV9lXxpCxt5e0wKhEeoB+ce/YHSqlhNunSbetJh2
            1DXRrYnVQmNhjWX6nyfhsyP9f6yNs8fhHie0zecQbkZvNwZY6vNugiE6ExWiJgXU
            aAEJAhCWnMYRtRXKaZ5SyljhWsQyP2sjoxSurqFgS6ocQ96/ZU0ArwNXyxvKb6jX
            2C+ZxMzFfftaaslK66rYRHF8sFGq3vyDYdcysESB+Gq7/Fg6Wpe/GWwBel/QsW3b
            G1dTOUWF3xwv
            =zIXa
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backups
    namespace: gitlab
type: Opaque
stringData:
    DESTINATION_ACCESSKEY: ENC[AES256_GCM,data:G5XUg9UwoO25VTjjoTwTWt3rRxY=,iv:+36ygL+YNpiZN8dVNAMQEHYtVrdegbzB6ieUbfVOp5U=,tag:l8FD5Qh96DJ8pLHvlgB9Wg==,type:str]
    DESTINATION_SECRETKEY: ENC[AES256_GCM,data:BvnmXLEKfX37DTmi/CU8AZJYhuZAkkHV3A0PmGuXn0ZG5cG1rXKnrA==,iv:zsNKia5jkOtw4tG69DZuYJbZ67ounx45eQqyQgYTI/A=,tag:0gAOiE2GvvqJfJ7Egs68dg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:09:05Z"
    mac: ENC[AES256_GCM,data:RxTMCiAQv9vIn6BYhN6oTv2lPKu+t70Ko6Xt/Y9GdozTaAH+rqEj6tVtDBeoowZ28IcOEfadA/L28o6/QCIFGr4INlUBj8DVvha7kKjDBGjc/NWz4Rx2LcvBa+vNNlGGYpcenGr/GsMnhnVc2hQY9HJBCiQ6C2xXc57X8ZGFMqE=,iv:GpyLHRA5EWi3y6kXreLBtyP4RviSsnnua7GyPLM0P/I=,tag:Uek+/nHviY07JK4QZ7OQ3w==,type:str]
    pgp:
        - created_at: "2026-07-24T13:05:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAsFSl811a7uGa0ZJPP8bXAemtGvdwWUeYlsJeJw9Y7wFB
            0/HCevaj19l1bGnu+vtHuth86aGjPhjscUbe2GyZd6FAMWynMLUCF4RKLBWGx5GC
            5x5+pX6PA9PQtS04MCahjwMC6imwGSnSYu5V4iCZpVSBLMFGqurMjwlBoH3iRpLe
            Mib0JqlRdU7ej841cMIVustn5V96Ufo3LJQdlewK6RgcgM7a+9XUIRlj6mlj4bd1
            fy6Zha92aYtcN3wjjd3tyyWzyrUxM2fHBpksk5ef2CbzXdwyjuSpUngDxDBaKc6L
            INaesu1vRm9FakSZVjRT9HmlhhLCn5EQ/TkO0GzBn/kcsnvjtRLvAPcWVPvfpp0P
            gxLNVr0fwYA9lzrAhy9W55YbO7LDpc6OJEtZbO49v2hoX0heFLb+5OvuV3jC7gig
            5EkyGWSOymDdPCN/r8DkMNsSGfZxI2vnjDwU4afPzIcqk/DKpqAczjGIWiKOolfY
            DeWNCe3nOEsdu0TusPa7+tpIx7aFKzR4jLK4gb1mfwXdACq02e9Ze3RHIJtVUZB8
            dMSB56lA6B137ar5UP0K9adkjV9lXxpCxt5e0wKhEeoB+ce/YHSqlhNunSbetJh2
            1DXRrYnVQmNhjWX6nyfhsyP9f6yNs8fhHie0zecQbkZvNwZY6vNugiE6ExWiJgXU
            aAEJAhCWnMYRtRXKaZ5SyljhWsQyP2sjoxSurqFgS6ocQ96/ZU0ArwNXyxvKb6jX
            2C+ZxMzFfftaaslK66rYRHF8sFGq3vyDYdcysESB+Gq7/Fg6Wpe/GWwBel/QsW3b
            G1dTOUWF3xwv
            =zIXa
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
