---
apiVersion: v1
kind: Secret
metadata:
  name: db-backup
  namespace: lore
type: Opaque
stringData:
  accessKey: ENC[AES256_GCM,data:53+ZnfZyJTZ5,iv:JBVh9lm3e4yeFe5Ozvq9cVxGvCGVUAtRmLsCy9+DgNc=,tag:f/yX1SnjKpLs0hboDnho1A==,type:str]
  secretKey: ENC[AES256_GCM,data:yRpYVZ/HvXFq7sPkb8y8oAUJS53/pMkoRoegfvmAzwwsyG26a1lQVw==,iv:tQ+FTi4E93KROaI6O8ZjxQwzbly8Un+JqqnmPbjLKxo=,tag:x0Sq+qyZC2Gz5yguSFUV1Q==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-09-04T15:01:13Z"
  mac: ENC[AES256_GCM,data:/8klHiUSrXS0n/gC8aonmM50ICdRqEZ3K2ehsylPWN3xVHgAi2lluX33qer8CldjQxkD3JrkswB5awXsthKLdrlh9lwMKuyra56tQ83XylI+PWEGhkpzi5MJnv+XNuRlaUZ0Hebu4mHCdxShG5ch2u4znQpQz525etRMk1wMjZA=,iv:FBLEVqRpsxanHF8TmoSsFKiPRv4En//DM/Za+2HVGp8=,tag:chHQGdB3AOiMkF7CUP1r3g==,type:str]
  pgp:
    - created_at: "2026-09-04T15:01:13Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ//Q1YdVmndsf8srEAQOgf0msnjdGgE9Oib/WDacukr030N
        sMBOfk6hxREP0qAiNTBI7Eewd1zUpAv3s3bvurNWpIWPb4rtuCy2KbSzfPLo9G6g
        vdBG9EJYv4Lo8BmCU9vl8iASl6s8KhSTqGQ8Fz1P+5yhmn/d8yJuOao7XyJ/qUH7
        XWVVgeoCSeVf4k5Jm4reAXZgRRiI3mgU3W3tsQufFM/GMqwf+lVwyDP0zTcUFvG4
        Aq0MlzBv8/m02wG2AWCc+62p5rZ6v9RjCnJqRHYcfu6Wd1m0N3GiwXyjPzkhxfCH
        Ttk8mvzb2+/iTaBbWWfC6Re2lETHtVF+WBW7Rx+qqCvF9yjMbGmBy8+TtKd7inlZ
        iAMvosxTh27LrtySl9Lgb7nWg3lcGA+ikfzpq+P9d5s+H1tKYKE/cs9bPSh7z1Kc
        QXS1zCYQS3pM2h0BCqTn50zloLG054fMvjCEyKgvzLFXQYcmTD37B2sV95BZbpZh
        xiAk4g9WlfKWrhqlMiczQGMleuYeqwqPlyG+HCpHtGGqgiCF4f36bPfP3LhnjjOM
        +g6fxJYrP96pOYSzNdvPddgRzKZS25oPy3ZKaI4t/GjrgjPGkQXyYpAoLnqoKvDz
        lkr5k4JTqTasl6M52aXy+Y2brkz1GuIF+MgFPe9Pq9ObR/Ve/nQYFxkDLJobvBzU
        aAEJAhAR7O7Wq2uDw8hSZM6ELiS7rtdlDoLuMlqVP/DIhYlQPg0lEW10njFSTZiH
        uifA964aepp4YG4cUkWJpsv3Ivt51JcDuPuyHGJhsPPpDpxIQkAkGXAm94EJsrUK
        3uZGgSBjxUFW
        =wdWb
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.3
