apiVersion: v1
kind: Secret
metadata:
    name: db-backup
    namespace: motus
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:3u51IOAtBhek+g==,iv:0JTPxSoIsNN3Et/1G70fm0+YFsf2kgq+uU3kqE3jM3g=,tag:fNkHdHCAlkkUW8DiFxNYWQ==,type:str]
    secretKey: ENC[AES256_GCM,data:wupm8h7NECTmLTH4lKITejtSsNZ/DDKmgLjPO9ocrwy1XJFoXopGpQ==,iv:Iy8oYyu5Cgkjx1V4xIKXYh7WLovg78KOaojw7hfwCQ4=,tag:zdzeSJKWixyT/QRJSAjhcg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:34Z"
    mac: ENC[AES256_GCM,data:X+/RSQh770Eeol5euV4cbZCvKENQtFmYUoDjAls6DvUZE7aa5UUNxfVR6xzG16nFM10S1AKrbmfVsuQBR0cK4ewWuLlnJMuWvgej81jDP8epqrd7uWYaVFmOlRx1EZxiDYI0WL+rLrri7sUUk0GxR1PYOUFKLWrcfWdp9npe8kA=,iv:qim986ZOZbTrbbl4LkeFaY78/sjM4IIRitHpIvzDOL4=,tag:6ebgco25fNXOYSioQVXPag==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+LtTnQP4H/bqMSmlgPT05uZ9eyfIU/6F+APnWSYl8u6Mb
            Ei+G9lH2jiOvaB5xW/taHC4lLBPMWRB0/8lU1fMCjrnwsbDw9Tn7/tSnsyr3xogt
            mB9UQLheqYek1IcZ1bwQqAmpqxgqdlENdj9ns1LAqweO9f4HrkB04sLg5gF6PxRE
            Z+XgOd6PnAF67dllofwRkIJCnZAW3r6VGMKvhanbB417xgyQNEpv4zu65TMdqzxB
            vXpfkXNdQa64Xx7YmtJ2ro84o2Yh72Vm6t8xus9lS55mAGWu0BjU3eeybJP2ZU2J
            LESf7IjlbgwjM3igLjfrrTxUldi4OxGwMWCNsRiCqw5Vui0Ae9O8WMrrwi1O+CwS
            3lk0QfgGIkXgHCWq5mbhGA6HBZdASZc06p8xqYl3fRw3nqiUOf9bk6ym+oh52TiS
            oJ75/TKylIRVnOl2APQ0qUdmt1Z8Jb4vooCiwjZVAmt8pGQ4rE1snqhh8tpZwO9Q
            M572KdCcr1Cd8U3/4glx4HGtG2E/NSgoqlZMHbykJUA43fpQFUsmWvxE2tqaml4X
            KZ74izPr5C0gZkfCjBZ/YHykhadI7Bdc0mwaUccewgBSuG1bIjVXRIOSISF0v6vg
            +e39pMxy14sICueH7mIyX8XTq6rXLzL7qYgCAJqaV8NwIkV8w2TuX0hI1rfEpDfU
            aAEJAhBgzA9o3UyLNXjpQRSJaBW+ta6K9rAZXbRYqO+4LfUheBY83nIAfOsRupVu
            USBdArbXujEs/LHRSHWBZyZHILSwzijNsp5sUc+iXwIlpwUSgE2mO8gxYKtwh+Ik
            xQxV7yGhTgZM
            =UXYA
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
