apiVersion: v1
kind: Secret
metadata:
  name: ${BASE_DOMAIN/./-}-sso-client-secret
  namespace: cilium
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:tNDM6HbEKAUtLr1ArqKpEVPAGLKL/nk9fn2LbxMVAW4=,iv:kVLgSuB50yZhxs2iL3FWq8NS5ncYEXhBuv1Xg7315mU=,tag:naD9jxgkshqx7uL/S091xw==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:31:08Z"
  mac: ENC[AES256_GCM,data:Jm23EPPM4X9qx9C6716urQYj3l2JhERZ7ImAEIld6N5prs14KLmbMTK3bLOZZbZdwzyxkpX70ZSDbff6oQCsi6gGBPTI/QtsKZ06YFvSo7mRMEsG+mk6+d7bWgZadW5+tvBfggarACHbeU2lTV2tA/Am2eqtO4b5yahmZEjpWOo=,iv:J7CZcqKHqq9UQjfLhl34QACPywg8tFucgwwUYi3CiJ8=,tag:lUqg2SQ+BqjdW2yCIH9NXw==,type:str]
  pgp:
    - created_at: "2026-06-29T15:31:08Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAAu48GydOOANY4/a7kASCX8a6vsXZ4AL1XwCbEllJJ3ZkP
        WV40ceH4yoXonE1MZaGYO+3KoLeOe1DPwhXwMFH/ADkeQPXvb7arx9UI3ET5Z8/q
        VXoGBNXKJS/2Nz1VE9OOJq4cnaMSLot88DuxrPMuCN7GQBmqw0frjvQKDa9S3geU
        Gk+SNwDdbf7nQLMul33LeV59tGkiMMBpfUfC/+maHgp7qTSERh1XzNhvmEXOHDPr
        6iuWW8Z1pzI0veL/TVLjBDnjaHaocm1W2LnOLeidcyUqc6EQ0oimpRAMjWqRaszz
        jqLxPFKbxsnO6UnRd7bmNxpW/d3BggsYKehuzIqz9T8vuS1J5QrK/YD7WqFmefSe
        PXFuEUTt5xSu1eeMFIrL048t6CXkXCK/7WMtjIJ8hFc5Gx4S3SVsZCmv5F/M2s/7
        VPri4gTxnaEbbz7XgNrVqFtsvfX7Ot877D2pt1/uGRLdxPF6Uq9GAz1Rie7zEYPY
        /jEogcT6D7Pxxqd3NBZhgdZf7d0z2hFbmf0sni5HUmlOaIe9wGjg1M3xhw1aCnYG
        CCxx45tZWzsJOZw6iNB8n1eJSuOOnZrAMurs8Y8wPz66D2J2yW4sjzvJCAHK7W3/
        MCkLd5QllHogGs7AWfj0cjs9uR/io0382/krDzw7OQ5w3uqEL6cjBp0oxkMyzX7U
        aAEJAhAJVoDSPyVONv2m9bdrupWMezkx5dt06qgxLvu123U1r512rCf/FNIz0K8f
        0Z6RDhGHhJHu1wFZ/Xm1/DpLmMjXuWpfwfZOdWk0mUVCDDp1zKq0E7pdDpIDJgOT
        kTFB6VsIbvTY
        =H9pH
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
