apiVersion: v1
kind: Secret
metadata:
    name: db-backup
    namespace: wiki
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:KttDp78ZDiej,iv:5CczfZBIAQIK4zr4BY6DD2MzLt5IWgEgNdTXi+lovgU=,tag:E7h/oYn1csG2acgo++JzMQ==,type:str]
    secretKey: ENC[AES256_GCM,data:J+qOqtTL+xtlPbO7hnQzeY7VUrRZT6yJCj3PC6DRrs/0mxqoONVabA==,iv:cAUKPNZe2hCq5ZGVqdWXvVTPQy0UQ8/HBzfUYBfAdNg=,tag:AV5acrDnz0YfwxrER1DF8w==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:26Z"
    mac: ENC[AES256_GCM,data:mnEmUvE9PhtjwDqjxr00esp1tSzWwcXpvdHRzeuvdOHKg0VZd0iPaSYbPYATQ+AYP50EAAprWaGTUMAkxj7H/h3L7dH2ZuAW6JzbF6csWthO+44Ug0npQU/G8LXXXQhuWcydzsyS2MUeCbcUji6QyWX7d2KDPG5p/V9thI0PGrw=,iv:+gtC944IDc+Qkyio6EoiJs/PErvi1rJ6o+5WgTyCOJ4=,tag:+fGh5hIKK9T8i0lPo3QIVQ==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArePGhItYIn59WFtK7JO8fHsoTMK+1dPnsYtMKSH6Mi+z
            hvTTK0vQUiSGc9W4wJIbIox/JGxNtl0paND2y4TtN0qGIkapIbqJ03bshbs4IBtx
            B2Rs7YkOYE8OqckkN+eoIUJK3ERtqmc/cW9KghrxAgjcGY5rNQDUwx+tgzj/AjlZ
            uMTE/Ob/KImsDkz491NvtEaJ9dgPJFfk8UyeMHoiLbQcVx1PM+ouk6GRICncHfNw
            kvQtySHKJtgoisg4QeR9wD+1mcYLLOJvL2lpiPhNL8FmTC95bs0d2Qw5j9q13rcN
            TbzaETSGXYhV2y/zP7wMuTAQY5cauuw/c3qTKFq3y8tf5vN6Mak0eoXrRmGMKV4v
            qwfcJnEghotTRtUBQdgfJa1m/9uMRVI+0LanNRSisBh4fq+xfK4YLvWx3XjUVlsK
            7ozcepoxaRoU9/bRnW7lB1GHYuMCaPGSZh9yG3YDttBgmfmklYmFxfefAA1lfBEI
            izpjdzuUEzyQ+QWnKS5cH1l9t5B5vjCeAgAxKHNmpYBMmeC30r+TqhEPNpTNoKPl
            zf4EaoZQNgdw1zSckSZVHqOTHM5Z0EWdaRIOMDDRVmQSDvRuvsQ7YoccAk2+uHA0
            PHh1vGRl1Z9lBpFm5TXmHi3nbwhDHaHcbygvvA90NmqmdvfFM/hfUuuSHrsK0v7U
            aAEJAhC8014GSCaAxcoLT+ucMBRo0ic8df7Df95r9yJyidomaVSw3mz6Sueu4qbA
            LV684Obcx16r6ZHF5AzCsEYCE6O5AEhKMxPyxZCw5Oyab6q7wzA71uX5gmh22l+O
            C4regytgvoT5
            =xDgz
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
