---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 30m
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  timeout: 3m
