apiVersion: v1
kind: Secret
metadata:
  name: healthchecks-prunes-healthchecks-url
  namespace: healthchecks
type: Opaque
stringData:
  HEALTHCHECKS_URL: ENC[AES256_GCM,data:o2YcivoUVHdd2NkyenXtK7bzjQZfa/SrmlULvKdne/YsHn7+XUaaQ+pMXNxj7Fn3+PYDJ9Tso0gGbuEoH+0i,iv:1tD4yA4QbgbRmHsOozMd6uvnR8CR6e/fPVHPbFi32Nk=,tag:GqUsaelVOJhmD4OBJKyAdA==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:18Z"
  mac: ENC[AES256_GCM,data:5Ti/MaAlsDOxW1ep9JLwqOUy4fo++tVQqvDZxQoX6+HFYzSxTy6/RswqzXLaJyMAGGMduSHV62XQxC9W7e02cL4v3Q/V4cU73ZBGYaOHjZJzWeuKV6KUBKZDTYni5Ub7Q5VJCcRc4ccgtTDNvK+lhxeeh9ET1DV+JjdKV2Bzmvw=,iv:T84l/0mlMt1QpOoUfRrU6ehLOEPwZveaog1f9eHJggo=,tag:wbhKj/8KsDYehh06f8IVuQ==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ/8CaFUEvX9Njy2uGo0HHZ9GavcVZWyTkwQfmdEyF9wur26
        24enxMMimQztWYVjev14qEq9cwmVu1mHYL/lmzn2VSzz3MhX4Yj8zZh652hKFZna
        0ILtH4DBPSVkKGLjOHsQLW9CJHcrZhGgTLALjR6eoiOtvW4dSrdvFIM4Zfs0uUNe
        tVk4/7n/LsPI7a/KT8g7RuvmbdWt1/kq3aQlIRSNw7YAEj/m7V6sPD0rd3zn+XS4
        6q7IQLPkkjI+EJ/d1jvS3cp6tULMsadv2N1ky5CONr/riVexV3XgAECxwVygYdWp
        Mc8gRRELKQXxLx0wCDkqRxt71pLsG4838BDPVLFIpCR1gGeKX/P5en0hUOwSaDAc
        Y080HZjMCUhmsGM2gQchrfLptfEovARiQnb/aeaMR9Ct1ckCybRmVGLXbvx9KFUW
        QB3cuPb+NyYgqPuXF7DEk63IlmcwuL4YnVPLZNRuQ410vWE2SQQB8KWc08GX7Qpi
        Ijg5i+sfxIFE7gevmhROZbTcq1ZuhaYaNr0rfy0BvrBg3S17UJ2AmvC2wXk3r8wq
        BaIYirpBMFngPV9MikVyJhaBcaCOGjo2aBV+pLau+2mFFGCJoyHEs2Q3PrNDklN3
        7UyXgwz3qumP9JGeGVn+BTGtRVVBDykwpVj1A0oR+y2M+9yQ7aLSYZai1gW77FPU
        aAEJAhASoWdpRdqd4n4lbl5zaqwkjqvquCvo9Ax+SctKSpIkhrOm8A4xv3M6zCZP
        JNj99KXJ89SEQwsyobbAqMS9/vAc/mjTqPMFJopspMGKj9/R+1zuecTLU7nrb+in
        ddLU89+yElw+
        =PbZA
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: healthchecks-settings
  namespace: healthchecks
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:O+fK4FjpgRN0z9SYcmIoqhiVdJFdKfORBB/nVyuquFE=,iv:m74+1Sa16ni5ObfRilOmqlrzRjCJ3We2TxjF8XZrqdE=,tag:JwKtsxzqKaRMC4K+ZCILpw==,type:str]
  SUPERUSER_EMAIL: ENC[AES256_GCM,data:cEWzsJRD8312QxaOmq2nKvKT2mlWpDM=,iv:MKGoizVp7ES3SVnXejRWkh3H+ThsZ9D6LXa9Pte2aKQ=,tag:8Xw9bv7+DB86YPOBrs+5cg==,type:str]
  SUPERUSER_PASSWORD: ENC[AES256_GCM,data:quqrvco3QpvvWLZycF6QHIhZbPy/1Clp,iv:eh0pnIDJccKWPP+8eaH7dYSn+w0lfHTnzAWF+3Tz+so=,tag:nJQtmgtPzG/Bo/pUBV/L3A==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:18Z"
  mac: ENC[AES256_GCM,data:5Ti/MaAlsDOxW1ep9JLwqOUy4fo++tVQqvDZxQoX6+HFYzSxTy6/RswqzXLaJyMAGGMduSHV62XQxC9W7e02cL4v3Q/V4cU73ZBGYaOHjZJzWeuKV6KUBKZDTYni5Ub7Q5VJCcRc4ccgtTDNvK+lhxeeh9ET1DV+JjdKV2Bzmvw=,iv:T84l/0mlMt1QpOoUfRrU6ehLOEPwZveaog1f9eHJggo=,tag:wbhKj/8KsDYehh06f8IVuQ==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ/8CaFUEvX9Njy2uGo0HHZ9GavcVZWyTkwQfmdEyF9wur26
        24enxMMimQztWYVjev14qEq9cwmVu1mHYL/lmzn2VSzz3MhX4Yj8zZh652hKFZna
        0ILtH4DBPSVkKGLjOHsQLW9CJHcrZhGgTLALjR6eoiOtvW4dSrdvFIM4Zfs0uUNe
        tVk4/7n/LsPI7a/KT8g7RuvmbdWt1/kq3aQlIRSNw7YAEj/m7V6sPD0rd3zn+XS4
        6q7IQLPkkjI+EJ/d1jvS3cp6tULMsadv2N1ky5CONr/riVexV3XgAECxwVygYdWp
        Mc8gRRELKQXxLx0wCDkqRxt71pLsG4838BDPVLFIpCR1gGeKX/P5en0hUOwSaDAc
        Y080HZjMCUhmsGM2gQchrfLptfEovARiQnb/aeaMR9Ct1ckCybRmVGLXbvx9KFUW
        QB3cuPb+NyYgqPuXF7DEk63IlmcwuL4YnVPLZNRuQ410vWE2SQQB8KWc08GX7Qpi
        Ijg5i+sfxIFE7gevmhROZbTcq1ZuhaYaNr0rfy0BvrBg3S17UJ2AmvC2wXk3r8wq
        BaIYirpBMFngPV9MikVyJhaBcaCOGjo2aBV+pLau+2mFFGCJoyHEs2Q3PrNDklN3
        7UyXgwz3qumP9JGeGVn+BTGtRVVBDykwpVj1A0oR+y2M+9yQ7aLSYZai1gW77FPU
        aAEJAhASoWdpRdqd4n4lbl5zaqwkjqvquCvo9Ax+SctKSpIkhrOm8A4xv3M6zCZP
        JNj99KXJ89SEQwsyobbAqMS9/vAc/mjTqPMFJopspMGKj9/R+1zuecTLU7nrb+in
        ddLU89+yElw+
        =PbZA
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: healthchecks-mail-settings
  namespace: healthchecks
type: Opaque
stringData:
  DEFAULT_FROM_EMAIL: ENC[AES256_GCM,data:/g8RksU4fCvSSjnJaExvESR2n21w,iv:R4OSjpCDj8ZLophbYwrvPHwXwEZlkjniZmPNUFLMT7Y=,tag:tUL36LR74d81ev+4zrT40Q==,type:str]
  EMAIL_HOST: ENC[AES256_GCM,data:IT6huf172paS2uG9zwQ=,iv:GyhO9iY6oFMt8imS3rMJzCncSDxN2q5xUQBIMLLDIy0=,tag:QiHJ+IJyYDCdHGDAcFHp7A==,type:str]
  EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:rZTMZZ8KJn+wOLNuZayeaA==,iv:eOadr5V2gr5uY2jh2k1M3zAcyS8V89w/7ovG6hkp0LM=,tag:keU00A+Kccco419zj3clJg==,type:str]
  EMAIL_HOST_USER: ENC[AES256_GCM,data:tED35JNE9L50SbYss8nuDP1er9ijz4I=,iv:HNAhsoQR5zarRvA5nYwXnFhk/d9IImoMWawYvXEhyZ0=,tag:cegtSiZnsNEwTnArXxU0Rw==,type:str]
  EMAIL_PORT: ENC[AES256_GCM,data:bdma,iv:xXdEwkAVtSZcjHhbB/UP2mxd1cuo5plM6+VXv8+Bbqk=,tag:7qjwK9Y+K0038GGjauiGGg==,type:str]
  EMAIL_USE_TLS: ENC[AES256_GCM,data:nmIndg==,iv:m2kDuswyGcSJPCmWUz8QJRl5derLjmv2y7Fwl6U2RhY=,tag:VksH2rlBs7UvBoq+ChCs+w==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:18Z"
  mac: ENC[AES256_GCM,data:5Ti/MaAlsDOxW1ep9JLwqOUy4fo++tVQqvDZxQoX6+HFYzSxTy6/RswqzXLaJyMAGGMduSHV62XQxC9W7e02cL4v3Q/V4cU73ZBGYaOHjZJzWeuKV6KUBKZDTYni5Ub7Q5VJCcRc4ccgtTDNvK+lhxeeh9ET1DV+JjdKV2Bzmvw=,iv:T84l/0mlMt1QpOoUfRrU6ehLOEPwZveaog1f9eHJggo=,tag:wbhKj/8KsDYehh06f8IVuQ==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ/8CaFUEvX9Njy2uGo0HHZ9GavcVZWyTkwQfmdEyF9wur26
        24enxMMimQztWYVjev14qEq9cwmVu1mHYL/lmzn2VSzz3MhX4Yj8zZh652hKFZna
        0ILtH4DBPSVkKGLjOHsQLW9CJHcrZhGgTLALjR6eoiOtvW4dSrdvFIM4Zfs0uUNe
        tVk4/7n/LsPI7a/KT8g7RuvmbdWt1/kq3aQlIRSNw7YAEj/m7V6sPD0rd3zn+XS4
        6q7IQLPkkjI+EJ/d1jvS3cp6tULMsadv2N1ky5CONr/riVexV3XgAECxwVygYdWp
        Mc8gRRELKQXxLx0wCDkqRxt71pLsG4838BDPVLFIpCR1gGeKX/P5en0hUOwSaDAc
        Y080HZjMCUhmsGM2gQchrfLptfEovARiQnb/aeaMR9Ct1ckCybRmVGLXbvx9KFUW
        QB3cuPb+NyYgqPuXF7DEk63IlmcwuL4YnVPLZNRuQ410vWE2SQQB8KWc08GX7Qpi
        Ijg5i+sfxIFE7gevmhROZbTcq1ZuhaYaNr0rfy0BvrBg3S17UJ2AmvC2wXk3r8wq
        BaIYirpBMFngPV9MikVyJhaBcaCOGjo2aBV+pLau+2mFFGCJoyHEs2Q3PrNDklN3
        7UyXgwz3qumP9JGeGVn+BTGtRVVBDykwpVj1A0oR+y2M+9yQ7aLSYZai1gW77FPU
        aAEJAhASoWdpRdqd4n4lbl5zaqwkjqvquCvo9Ax+SctKSpIkhrOm8A4xv3M6zCZP
        JNj99KXJ89SEQwsyobbAqMS9/vAc/mjTqPMFJopspMGKj9/R+1zuecTLU7nrb+in
        ddLU89+yElw+
        =PbZA
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: ${BASE_DOMAIN/./-}-sso-client-secret
  namespace: healthchecks
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:QDj+RdEK+xOIDEmeODBpC1u6PrTT7UCM/ZuxZZV2T/8=,iv:Rxyh2rN4qZnQlEUqVlqUO5nzUf4f7EtD1eqgM93sp2c=,tag:x7+dRHnh33ggXFEI0Hwy/Q==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:18Z"
  mac: ENC[AES256_GCM,data:5Ti/MaAlsDOxW1ep9JLwqOUy4fo++tVQqvDZxQoX6+HFYzSxTy6/RswqzXLaJyMAGGMduSHV62XQxC9W7e02cL4v3Q/V4cU73ZBGYaOHjZJzWeuKV6KUBKZDTYni5Ub7Q5VJCcRc4ccgtTDNvK+lhxeeh9ET1DV+JjdKV2Bzmvw=,iv:T84l/0mlMt1QpOoUfRrU6ehLOEPwZveaog1f9eHJggo=,tag:wbhKj/8KsDYehh06f8IVuQ==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ/8CaFUEvX9Njy2uGo0HHZ9GavcVZWyTkwQfmdEyF9wur26
        24enxMMimQztWYVjev14qEq9cwmVu1mHYL/lmzn2VSzz3MhX4Yj8zZh652hKFZna
        0ILtH4DBPSVkKGLjOHsQLW9CJHcrZhGgTLALjR6eoiOtvW4dSrdvFIM4Zfs0uUNe
        tVk4/7n/LsPI7a/KT8g7RuvmbdWt1/kq3aQlIRSNw7YAEj/m7V6sPD0rd3zn+XS4
        6q7IQLPkkjI+EJ/d1jvS3cp6tULMsadv2N1ky5CONr/riVexV3XgAECxwVygYdWp
        Mc8gRRELKQXxLx0wCDkqRxt71pLsG4838BDPVLFIpCR1gGeKX/P5en0hUOwSaDAc
        Y080HZjMCUhmsGM2gQchrfLptfEovARiQnb/aeaMR9Ct1ckCybRmVGLXbvx9KFUW
        QB3cuPb+NyYgqPuXF7DEk63IlmcwuL4YnVPLZNRuQ410vWE2SQQB8KWc08GX7Qpi
        Ijg5i+sfxIFE7gevmhROZbTcq1ZuhaYaNr0rfy0BvrBg3S17UJ2AmvC2wXk3r8wq
        BaIYirpBMFngPV9MikVyJhaBcaCOGjo2aBV+pLau+2mFFGCJoyHEs2Q3PrNDklN3
        7UyXgwz3qumP9JGeGVn+BTGtRVVBDykwpVj1A0oR+y2M+9yQ7aLSYZai1gW77FPU
        aAEJAhASoWdpRdqd4n4lbl5zaqwkjqvquCvo9Ax+SctKSpIkhrOm8A4xv3M6zCZP
        JNj99KXJ89SEQwsyobbAqMS9/vAc/mjTqPMFJopspMGKj9/R+1zuecTLU7nrb+in
        ddLU89+yElw+
        =PbZA
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
