apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-prunes-healthchecks-url
    namespace: healthchecks
type: Opaque
stringData:
    HEALTHCHECKS_URL: ENC[AES256_GCM,data:mc9mMa4jw3QLi9e9GNSyOE7aoEVwyN0D5jU3hVm0NZwOvX2XxvhdvKgI4NNuHkWVVfqZ/1eG9Ri4QFzkIAjA,iv:Rk6NiQMuX+RuaLHYGUJMJNzR6rgjYq5NIebea3RBj5Q=,tag:f9eT9CqWmmjMpXYO4bz5dg==,type:str]
sops:
    lastmodified: "2026-03-30T11:22:39Z"
    mac: ENC[AES256_GCM,data:5tzgIVdfmRv2ekHqFZNDFU7pbMClk4EncL3alj9tDRNRh+Lc7jaCumigFis6nDhtK5S8TH83LVi513gnT0VzuXjQxlrleKh9CtjmUcq1cJWlbNs9sOHTUVe7q1dvLsBfJne/VzL/Bzo4xZa/fg2QZiE4Gx+fz5KhLbgInyPQIW0=,iv:ngq2dACeokQ+iR4ktKwvErEDAwApxdzp8elirsQg/ss=,tag:P1hugIbYkRBg42NKs9HbBg==,type:str]
    pgp:
        - created_at: "2026-03-30T11:22:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//UgwejkgWfGKoqwn5RWNbaTjH9s+eT8qr3YljrCD0N+pB
            fXu0kCmzMxOVGDWifgnVx8QHgK7YwLxK/fClhohA0Ice4MDzpOs7NwDI+XQj18uz
            xOeHFcChU2Dfgyx4Kl4/Joc9a+QVngsWyXQvZ0Z1WhfErQaVtiXxoSAPcPJYd77J
            EUxbpWCr0hkUnKwhBrGutdxnJ10gGkcFFWzH6ulcgYLWT80hb0fKt73FBm1fcViD
            keCB7OcC6JpkAGGcRN2CyCs4hvCM26wm6sZkiqfVe1R41VVYlbW5tTeWwMhTvmZw
            LUP5BxVOWF5QdQS1kWaN1KV8cgkmsj7ysJj3JIEGN/ol8R16VDAWBb8pGZOVZemg
            Tzq9SshWRbf0bsQi/CFR2TiKpTVuifWUDudmHgy7x4Lf4yzml0Qb8vFggrTfVDJD
            Lh4jgO/vRuw6EkwNpybuw96oA/Oe8VhQSI9mrX2D4/w7/VbQC3j1a9HaYy5J0r3U
            mXsdin2AyPFleWWr2DgxNXC8VTFcvw5rB368foSLUeiOgxCV4M3lTWDbp1PQ9tUt
            c9jjJOff3ArEE/keIy+FFJUOzwIXHVkaSQ7oXWHclaHQArsMcvdifrB2liv9otWC
            KeofrfyTwwG1RnJ83KrQq4Ipv6eEJrG1rYqW4jGbsZPBZSAu40qZ/AtszDa24D7U
            aAEJAhBBcDrT1ISgi8OQMX1Mac/Qu1reyaMdQGRSkUC2qTUZIxTmC6RLdhcemgas
            VzxjOSHoFVK8S/Tzw6zcvaF5Lv4sY7YXdhUbHfREIqfx+qIwhPMcNb9/PNSoCIrg
            pA9W/TRUuhBb
            =yBmf
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-settings
    namespace: healthchecks
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:+kHygPvwnoVgugSAGYQIOVAiouPbIHPzW4R3sk2eodU=,iv:PVllWI4mo7w0OhGy9nm1cwjHSQCt0R1OMyzoSx5LAGg=,tag:Z+cv/rr5U7UmdvhDMjUt0A==,type:str]
    SUPERUSER_EMAIL: ENC[AES256_GCM,data:g3isoQio2ttWZL0V8UfLQkxb1xAKYwY=,iv:vS8yt/nL+WAh29qDa+YkFWugwlZASxcEvQqnvhgJ4DQ=,tag:VAy7toNA8rPXA2qfqdEbsA==,type:str]
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:9fKQaDI6YfRef6JfBgsxWsK3rkaEusjf,iv:RquSTbXURZ497m20RjAtvRLDKQMNUrEbT+wI0gDfREc=,tag:jNNWdRwOqG+3NBm6VShr5g==,type:str]
sops:
    lastmodified: "2026-03-30T11:22:39Z"
    mac: ENC[AES256_GCM,data:5tzgIVdfmRv2ekHqFZNDFU7pbMClk4EncL3alj9tDRNRh+Lc7jaCumigFis6nDhtK5S8TH83LVi513gnT0VzuXjQxlrleKh9CtjmUcq1cJWlbNs9sOHTUVe7q1dvLsBfJne/VzL/Bzo4xZa/fg2QZiE4Gx+fz5KhLbgInyPQIW0=,iv:ngq2dACeokQ+iR4ktKwvErEDAwApxdzp8elirsQg/ss=,tag:P1hugIbYkRBg42NKs9HbBg==,type:str]
    pgp:
        - created_at: "2026-03-30T11:22:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//UgwejkgWfGKoqwn5RWNbaTjH9s+eT8qr3YljrCD0N+pB
            fXu0kCmzMxOVGDWifgnVx8QHgK7YwLxK/fClhohA0Ice4MDzpOs7NwDI+XQj18uz
            xOeHFcChU2Dfgyx4Kl4/Joc9a+QVngsWyXQvZ0Z1WhfErQaVtiXxoSAPcPJYd77J
            EUxbpWCr0hkUnKwhBrGutdxnJ10gGkcFFWzH6ulcgYLWT80hb0fKt73FBm1fcViD
            keCB7OcC6JpkAGGcRN2CyCs4hvCM26wm6sZkiqfVe1R41VVYlbW5tTeWwMhTvmZw
            LUP5BxVOWF5QdQS1kWaN1KV8cgkmsj7ysJj3JIEGN/ol8R16VDAWBb8pGZOVZemg
            Tzq9SshWRbf0bsQi/CFR2TiKpTVuifWUDudmHgy7x4Lf4yzml0Qb8vFggrTfVDJD
            Lh4jgO/vRuw6EkwNpybuw96oA/Oe8VhQSI9mrX2D4/w7/VbQC3j1a9HaYy5J0r3U
            mXsdin2AyPFleWWr2DgxNXC8VTFcvw5rB368foSLUeiOgxCV4M3lTWDbp1PQ9tUt
            c9jjJOff3ArEE/keIy+FFJUOzwIXHVkaSQ7oXWHclaHQArsMcvdifrB2liv9otWC
            KeofrfyTwwG1RnJ83KrQq4Ipv6eEJrG1rYqW4jGbsZPBZSAu40qZ/AtszDa24D7U
            aAEJAhBBcDrT1ISgi8OQMX1Mac/Qu1reyaMdQGRSkUC2qTUZIxTmC6RLdhcemgas
            VzxjOSHoFVK8S/Tzw6zcvaF5Lv4sY7YXdhUbHfREIqfx+qIwhPMcNb9/PNSoCIrg
            pA9W/TRUuhBb
            =yBmf
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-mail-settings
    namespace: healthchecks
type: Opaque
stringData:
    DEFAULT_FROM_EMAIL: ENC[AES256_GCM,data:xr6OzUkGlgjj+vbzSCp6ZjXNXGSL,iv:C0l63sMFo1YV14OHAUnGN2L5itSoLCaMykAVpsZA7FA=,tag:0tIW4u+04PBuyztUA/vYfQ==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:ZgN5/+nhiAYqmDaHdRk=,iv:cvRawqH8/B/DJB50dDZ2TXNoDQK7qAAdCq2Be/OpiSU=,tag:Q0+yqLT+ujX7iD/Q97PZ/Q==,type:str]
    EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:/6lGIO6Nw3QvKHKLsf8msw==,iv:FgDFe0Cm1t00cKFKSWoUEnnlEacnKCwy7kuMS1819hU=,tag:Yc6vXPmnKLoXqV+cNGkeUA==,type:str]
    EMAIL_HOST_USER: ENC[AES256_GCM,data:0nB2ELlI0KsJj/mFXg1eqDVxYh3l/Dg=,iv:VQPOP14und/4Ww8BU7T4kQUvCRegn0e6H5VxLD3cX9k=,tag:YXJ15nV1hoQ64uKCeuJoPw==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:kpq0,iv:cqmtqStGgM2PwOY/rurbX6QmVPIzLOyw78ZXcPfDCdE=,tag:Ht1N10fuYqr2AxMmCsMNpQ==,type:str]
    EMAIL_USE_TLS: ENC[AES256_GCM,data:+/g4lw==,iv:EyiV7l/9/H5IF08phV+vVYNoGX78a/oFHpqDrE2u02c=,tag:2sEluAk9s6ivdvwOTAWv8w==,type:str]
sops:
    lastmodified: "2026-03-30T11:22:39Z"
    mac: ENC[AES256_GCM,data:5tzgIVdfmRv2ekHqFZNDFU7pbMClk4EncL3alj9tDRNRh+Lc7jaCumigFis6nDhtK5S8TH83LVi513gnT0VzuXjQxlrleKh9CtjmUcq1cJWlbNs9sOHTUVe7q1dvLsBfJne/VzL/Bzo4xZa/fg2QZiE4Gx+fz5KhLbgInyPQIW0=,iv:ngq2dACeokQ+iR4ktKwvErEDAwApxdzp8elirsQg/ss=,tag:P1hugIbYkRBg42NKs9HbBg==,type:str]
    pgp:
        - created_at: "2026-03-30T11:22:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//UgwejkgWfGKoqwn5RWNbaTjH9s+eT8qr3YljrCD0N+pB
            fXu0kCmzMxOVGDWifgnVx8QHgK7YwLxK/fClhohA0Ice4MDzpOs7NwDI+XQj18uz
            xOeHFcChU2Dfgyx4Kl4/Joc9a+QVngsWyXQvZ0Z1WhfErQaVtiXxoSAPcPJYd77J
            EUxbpWCr0hkUnKwhBrGutdxnJ10gGkcFFWzH6ulcgYLWT80hb0fKt73FBm1fcViD
            keCB7OcC6JpkAGGcRN2CyCs4hvCM26wm6sZkiqfVe1R41VVYlbW5tTeWwMhTvmZw
            LUP5BxVOWF5QdQS1kWaN1KV8cgkmsj7ysJj3JIEGN/ol8R16VDAWBb8pGZOVZemg
            Tzq9SshWRbf0bsQi/CFR2TiKpTVuifWUDudmHgy7x4Lf4yzml0Qb8vFggrTfVDJD
            Lh4jgO/vRuw6EkwNpybuw96oA/Oe8VhQSI9mrX2D4/w7/VbQC3j1a9HaYy5J0r3U
            mXsdin2AyPFleWWr2DgxNXC8VTFcvw5rB368foSLUeiOgxCV4M3lTWDbp1PQ9tUt
            c9jjJOff3ArEE/keIy+FFJUOzwIXHVkaSQ7oXWHclaHQArsMcvdifrB2liv9otWC
            KeofrfyTwwG1RnJ83KrQq4Ipv6eEJrG1rYqW4jGbsZPBZSAu40qZ/AtszDa24D7U
            aAEJAhBBcDrT1ISgi8OQMX1Mac/Qu1reyaMdQGRSkUC2qTUZIxTmC6RLdhcemgas
            VzxjOSHoFVK8S/Tzw6zcvaF5Lv4sY7YXdhUbHfREIqfx+qIwhPMcNb9/PNSoCIrg
            pA9W/TRUuhBb
            =yBmf
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: ${BASE_DOMAIN/./-}-sso-client-secret
    namespace: healthchecks
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:nACrqA1s48zq4DFvqqS5SkAv+IChvZ7QYQy87H16qas=,iv:KnqXBR5AQbJjfIZOPHriJCJ3ybNOmY7/bmuvrORaF1M=,tag:nSAqYiDpQ2g/yTBIcRFF2w==,type:str]
sops:
    lastmodified: "2026-03-30T11:22:39Z"
    mac: ENC[AES256_GCM,data:5tzgIVdfmRv2ekHqFZNDFU7pbMClk4EncL3alj9tDRNRh+Lc7jaCumigFis6nDhtK5S8TH83LVi513gnT0VzuXjQxlrleKh9CtjmUcq1cJWlbNs9sOHTUVe7q1dvLsBfJne/VzL/Bzo4xZa/fg2QZiE4Gx+fz5KhLbgInyPQIW0=,iv:ngq2dACeokQ+iR4ktKwvErEDAwApxdzp8elirsQg/ss=,tag:P1hugIbYkRBg42NKs9HbBg==,type:str]
    pgp:
        - created_at: "2026-03-30T11:22:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//UgwejkgWfGKoqwn5RWNbaTjH9s+eT8qr3YljrCD0N+pB
            fXu0kCmzMxOVGDWifgnVx8QHgK7YwLxK/fClhohA0Ice4MDzpOs7NwDI+XQj18uz
            xOeHFcChU2Dfgyx4Kl4/Joc9a+QVngsWyXQvZ0Z1WhfErQaVtiXxoSAPcPJYd77J
            EUxbpWCr0hkUnKwhBrGutdxnJ10gGkcFFWzH6ulcgYLWT80hb0fKt73FBm1fcViD
            keCB7OcC6JpkAGGcRN2CyCs4hvCM26wm6sZkiqfVe1R41VVYlbW5tTeWwMhTvmZw
            LUP5BxVOWF5QdQS1kWaN1KV8cgkmsj7ysJj3JIEGN/ol8R16VDAWBb8pGZOVZemg
            Tzq9SshWRbf0bsQi/CFR2TiKpTVuifWUDudmHgy7x4Lf4yzml0Qb8vFggrTfVDJD
            Lh4jgO/vRuw6EkwNpybuw96oA/Oe8VhQSI9mrX2D4/w7/VbQC3j1a9HaYy5J0r3U
            mXsdin2AyPFleWWr2DgxNXC8VTFcvw5rB368foSLUeiOgxCV4M3lTWDbp1PQ9tUt
            c9jjJOff3ArEE/keIy+FFJUOzwIXHVkaSQ7oXWHclaHQArsMcvdifrB2liv9otWC
            KeofrfyTwwG1RnJ83KrQq4Ipv6eEJrG1rYqW4jGbsZPBZSAu40qZ/AtszDa24D7U
            aAEJAhBBcDrT1ISgi8OQMX1Mac/Qu1reyaMdQGRSkUC2qTUZIxTmC6RLdhcemgas
            VzxjOSHoFVK8S/Tzw6zcvaF5Lv4sY7YXdhUbHfREIqfx+qIwhPMcNb9/PNSoCIrg
            pA9W/TRUuhBb
            =yBmf
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
