apiVersion: v1
kind: Secret
metadata:
    name: ${BASE_DOMAIN/./-}-sso-client-secret
    namespace: motus
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:PF803phQsZ+bYWhwM3FK08ntB80kHjrqCaaoMzJkA0FD4jSu/gR2Xa2kY7c66GebB0XC4TlXNPMP8G/MqVdszuL8fAsmhtIfvvKUDiVFQqwa5jUhPw8=,iv:2gLjd+B5xdRNO6AeizIhMR4fl7q0d6PptEXKxQmbFXc=,tag:h+Nx8i9bB0fjUkkPIknI3A==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T09:08:22Z"
    mac: ENC[AES256_GCM,data:6hAM7/yVy6JGA8GrZ1zvBeSdbJy3BOAV5f91RGa/2bL/0vfxBdz4qRqPQlBa+YrEqKXgy8qw+xz4avQtd1PJdAuZHGw1NkFZ3IRT0d1POayzOmeeGismx92zz7fG3LCQarfZGkAhcV2nWbcAI6910mj8fBrelTQwDQvUs5B0sC4=,iv:j0BUNJAvxMBOSHZ1H6haVQeJounEoN07QyQ9tV16s3Y=,tag:tUIU9Cx4skws7x+XDTnz/Q==,type:str]
    pgp:
        - created_at: "2026-06-29T15:30:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+J+fLfzLL3DagUlwmDqkljHrqW6LsgCCH3GGG5qvZsjIS
            aAlwYek2mLWhbEsnLVdtUuyFHPZxOpCvkB8wRLVyXQsh6s8fokkuHFxEgT0VkFjM
            E+Q9zNfu+elkvhWlhhbT27flrSIDnjGGYtg98S/ysaRMdEB495MHuwIlsX5EqolJ
            C9wMKsLMa8H8wZ4V4amlaC06khGkV9oX16iPswefYVWb3h0rxLdiCckHs+gs/HYL
            Ot9FgjieQ13SLQFsqmczzaLvaPuk4MyXAKJZyG9vNu72bSS3MMOoxodyhDL6ECI2
            Uu9lKU2zwqLVfLAts/mn1UJewGiR7Fpk62nxXGYw6Y8PvCcBYWpNEoO/h6trx2Lo
            x1myWgxZ7RsN8Ws/p6dQTsSaFxcjlyxjf9P2XBwuNirvoq4YHRhIV29BE2xoob6m
            fgiUESVAlciFb5FV+EdGOrVwtUytjDKCe/kpyepr/1JR7Dfd0aWOfXb7DFTrVKVe
            vC442K8saXDT9Z0Jbka/hCb03XFBq2jBxXuqYDIlP6moacBXU8jqhPUS+8mC363P
            eCb74I9wSoe0yiOh1ShYh1vQShVP01bmt7aS5nv6ZJ2aqPQTCTWXXnGaQJQ1Qh0P
            /5J+xaoOxZprg7vsVsaBKO3CQkYFTGSZbTCJEhBe12jUgZS7iHI1wpCL2oW32TjU
            aAEJAhB25WEaGS55XfHpiGQfvqP7mpBDN4s6PqjH3rX+8e9qzQRClHCY/FwcOF6X
            mWhc1oXAYoWbVhm65M0pj/nhEsnHVEnod5cHZoPMJrNvoOH1gmxYMCqvlEhez8yd
            wvAMdCgS9AOK
            =hF8U
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
