apiVersion: v1
kind: Secret
metadata:
    name: vimbin
    namespace: vimbin
type: Opaque
stringData:
    VIMBIN_TOKEN: ENC[AES256_GCM,data:WkcIgbeWXX30yJNoKzcfQoOjqTkahcGrRzWWwU3Ch1w=,iv:YsIHvPjCOpb50HwkgEcR79IkbqcgvGbJ5Q/ftfg5eG4=,tag:2Rg4Orac+SHOQsmCes7fXw==,type:str]
sops:
    lastmodified: "2026-03-30T11:23:23Z"
    mac: ENC[AES256_GCM,data:P05+7iEHkR0gShpIDoOE2KwufWGImtkEj75ghXtbdMuxjN4wS+nsiYELbpYc6KbalVzj3khlvTK4HsTVdHA7/pJk3wR/FJtXswF+qt2TehXLJoj57lEFofcPYnsgCFNl+3k19G2p7O8sK65Kkpii3aKF0iJ9qB6Uw++TKtXe6so=,iv:xQApgzEDBW59AKFQfIS6CuGXbUfZMvWwpODk14fEY6c=,tag:JCXA3FpSEDF4CsmGdfmIPQ==,type:str]
    pgp:
        - created_at: "2026-03-30T11:23:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//SoS6OGkzLYxvKMqbF67C1wWE1TAUR/XTpCDdRzEIfzcT
            ubfkAq6TMT+p7/oxMGmSFvwyAjs35FtmLRCHBuhhVDWvx5ScJLwRtxfDaWD6/O/c
            OjoPItIkV7DyZlncor+z79lnDWslMD0GDh2QEX/tIQcQKKCe9pEKeOF/OScF3DCD
            Mln0B5VBQjAskGkP5SexfI/NzyBSRxoCd6AUuwHzsrJHul+1lSL8cjzBNHYSuejg
            s/TzQUcP3kPyqJvBBHRPVAu37u0XkL3mVmSZvqKKAagEsYERKfrNQPDmuLIPq95/
            84LhTD4AFe1Tz59U68eRVgezUlLQm3kL5FjFEzYphOTtgjkhlQUgt+XSLg640O5z
            FKgL2isnsFi1Xt6TfwiJerEKtXt9Oe9dtjzw6wc6zfl9EmaViHmDvfZ9bEX1yLHR
            iFWzNhlElSpKGD0ITCz4bg/eTpbqJIEDao7D80TIFXRPlngm5/y9OwJjPSZgdzqA
            2KSSMcJLvmtMobPou1dCALwCCJHEyc0rL1s/kCcspFx30pwUJY3CjvA/5epH1ahM
            SqpFyciZ/ie0WITN5sAv/NZilEsy7D9apH41k2QY0nvu7sidjVTHpvr0E+lZMIuR
            yKrCuC5s3Q87pPJmdPWdp2Ex3cLIIBcyvwOogIRry1uYoF+mmaLSJjPor2Kj9JbU
            aAEJAhBDYuwwmRTVAkpsDjz0UoWTQ3WJSoHIhir6uUFeAWeqgYNBkAhzkelWqL28
            buW3xgnDON4uUeZsbg7OxinYaQvl99IfmkyjHcY7bk58mZP7hTeJtIt8MKxw01ij
            8TBjfAy40TS2
            =YNfJ
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: ${BASE_DOMAIN/./-}-sso-client-secret
    namespace: vimbin
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:UUBjA0MKZ2Hx5EPHXq6O/h0fkUu0Wu15ZvqtEup7eEI=,iv:9N/tOdU8q9ihvuJtfUUA3mVZTMKN82DFnPNeCS+qIvc=,tag:yIz7oef1AsC4UHwfeYW/qQ==,type:str]
sops:
    lastmodified: "2026-03-30T11:23:23Z"
    mac: ENC[AES256_GCM,data:P05+7iEHkR0gShpIDoOE2KwufWGImtkEj75ghXtbdMuxjN4wS+nsiYELbpYc6KbalVzj3khlvTK4HsTVdHA7/pJk3wR/FJtXswF+qt2TehXLJoj57lEFofcPYnsgCFNl+3k19G2p7O8sK65Kkpii3aKF0iJ9qB6Uw++TKtXe6so=,iv:xQApgzEDBW59AKFQfIS6CuGXbUfZMvWwpODk14fEY6c=,tag:JCXA3FpSEDF4CsmGdfmIPQ==,type:str]
    pgp:
        - created_at: "2026-03-30T11:23:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//SoS6OGkzLYxvKMqbF67C1wWE1TAUR/XTpCDdRzEIfzcT
            ubfkAq6TMT+p7/oxMGmSFvwyAjs35FtmLRCHBuhhVDWvx5ScJLwRtxfDaWD6/O/c
            OjoPItIkV7DyZlncor+z79lnDWslMD0GDh2QEX/tIQcQKKCe9pEKeOF/OScF3DCD
            Mln0B5VBQjAskGkP5SexfI/NzyBSRxoCd6AUuwHzsrJHul+1lSL8cjzBNHYSuejg
            s/TzQUcP3kPyqJvBBHRPVAu37u0XkL3mVmSZvqKKAagEsYERKfrNQPDmuLIPq95/
            84LhTD4AFe1Tz59U68eRVgezUlLQm3kL5FjFEzYphOTtgjkhlQUgt+XSLg640O5z
            FKgL2isnsFi1Xt6TfwiJerEKtXt9Oe9dtjzw6wc6zfl9EmaViHmDvfZ9bEX1yLHR
            iFWzNhlElSpKGD0ITCz4bg/eTpbqJIEDao7D80TIFXRPlngm5/y9OwJjPSZgdzqA
            2KSSMcJLvmtMobPou1dCALwCCJHEyc0rL1s/kCcspFx30pwUJY3CjvA/5epH1ahM
            SqpFyciZ/ie0WITN5sAv/NZilEsy7D9apH41k2QY0nvu7sidjVTHpvr0E+lZMIuR
            yKrCuC5s3Q87pPJmdPWdp2Ex3cLIIBcyvwOogIRry1uYoF+mmaLSJjPor2Kj9JbU
            aAEJAhBDYuwwmRTVAkpsDjz0UoWTQ3WJSoHIhir6uUFeAWeqgYNBkAhzkelWqL28
            buW3xgnDON4uUeZsbg7OxinYaQvl99IfmkyjHcY7bk58mZP7hTeJtIt8MKxw01ij
            8TBjfAy40TS2
            =YNfJ
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
