apiVersion: v1
kind: Secret
metadata:
  name: vimbin
  namespace: vimbin
type: Opaque
stringData:
  VIMBIN_TOKEN: ENC[AES256_GCM,data:xaRX2k9WAoUeW+1/0iE9gIDWM6Jip+t0PlPQ6ceFAYg=,iv:CRPVPLI84k+hCxG0pruUFypAYvg+kZ8DHTAXJr53xCc=,tag:0PVvtoQ3N08/ToS8kewpFQ==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:51Z"
  mac: ENC[AES256_GCM,data:5lyuXERnP8O3KNm9p3ueUcAFad7WpXWrs0zvL+aCYyJcs62BaJk+/JzJh7C8gK/XUntOR84D9zi/cXRTGi2hEjV6kBqLCH99V6f+6FS82hyg6FbrWZmF6OBFYkQpvaVePGR1ioNzTIwRBTXaI40aQOgfsbxZBpkeGVDyQHJkFUc=,iv:xOvoM80z7UhcC1Ih9D8VaJ6i2l6xnCHWKRIvOmc8llY=,tag:WiMYW/dx3b+MHtoyOMtGqw==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAA1L7bVMDnBC+ayUMW2wFw3qH+j/CX5R+43bO9FapKCMY7
        Ln1uUkoS38IVed5HVdrK5LR4kecs2TQgO8PM65xrOcpaR2p8FWpEk2k//A/any3D
        7WSLT5Ae/g2rLR7QSW1BqUnlkQj1TPBsJQpBG+Y7dKetby90g7GMSf855RXPsTbe
        TBrYzrNlU2kWjHlvcY1R61u+KIsSMVzqSv9tiVTeLt6O7S9kj62MpvrPn3JsqMYW
        atUG7Yk82zZd5IMNo7wzu2/yCSSn1OVU0C9OOve8TEjS81FgNktUhxF1qjGjaHXS
        jTPggjOkUC2ajiwjJYA+GoiKareeT3Ilt+EUdytIRhKkPKzCg+sf/gfj5dq5Wiwq
        Yvw+fNj/k+4cGlUVr1vU4Kjhj0GB1FUaVn6oMItIWJjpUkeQKH6VuYwabcDAPAN7
        0ljPOBLVt4TUumQpAJ/6N5lEXNzRFZar4fTh/8su2vD6GxCcd9YsyFXf06JlKjD9
        npoNqqqPKQuKjV3wwbnz/78XjdJDz80NYwcytSczkt24iboFiexmFG/Bn9TG7Fxs
        zkoZiA0tL7o7lvP4cPvV8JcW+2mpb1a21qjgBVEQcKGV7+gMeuDchq4fBH6gXIpx
        PgwYv4EtQ8OrGw5Pw8TbaswWOPJ6XIO8wIIw5aJOOn1+fS/zjwpjZEPCQ1KyKgbU
        aAEJAhBZNU26yjvLVdAWzFxS9oV3gekVnSDKXBjFbA6AE4FBFAZMtjMoZw/2O3yY
        NjQcgAebeDmy75eF/3iC8wH+rvb5G2SFkc1kftcsAjaTkvX0IoDk0DR0/PEzlDFI
        y/ve682it070
        =xL3+
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: ${BASE_DOMAIN/./-}-sso-client-secret
  namespace: vimbin
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:7uauoNkYEFtwEz0P57VjBpPh2cciK/5eqtQcM7QB7O0=,iv:6ttrWjLh9giPJTLJViR6WdN1Kc72BmNaBZ6DTOyxQlU=,tag:MLekqTF1cuKKIiv5uop++A==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:51Z"
  mac: ENC[AES256_GCM,data:5lyuXERnP8O3KNm9p3ueUcAFad7WpXWrs0zvL+aCYyJcs62BaJk+/JzJh7C8gK/XUntOR84D9zi/cXRTGi2hEjV6kBqLCH99V6f+6FS82hyg6FbrWZmF6OBFYkQpvaVePGR1ioNzTIwRBTXaI40aQOgfsbxZBpkeGVDyQHJkFUc=,iv:xOvoM80z7UhcC1Ih9D8VaJ6i2l6xnCHWKRIvOmc8llY=,tag:WiMYW/dx3b+MHtoyOMtGqw==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAA1L7bVMDnBC+ayUMW2wFw3qH+j/CX5R+43bO9FapKCMY7
        Ln1uUkoS38IVed5HVdrK5LR4kecs2TQgO8PM65xrOcpaR2p8FWpEk2k//A/any3D
        7WSLT5Ae/g2rLR7QSW1BqUnlkQj1TPBsJQpBG+Y7dKetby90g7GMSf855RXPsTbe
        TBrYzrNlU2kWjHlvcY1R61u+KIsSMVzqSv9tiVTeLt6O7S9kj62MpvrPn3JsqMYW
        atUG7Yk82zZd5IMNo7wzu2/yCSSn1OVU0C9OOve8TEjS81FgNktUhxF1qjGjaHXS
        jTPggjOkUC2ajiwjJYA+GoiKareeT3Ilt+EUdytIRhKkPKzCg+sf/gfj5dq5Wiwq
        Yvw+fNj/k+4cGlUVr1vU4Kjhj0GB1FUaVn6oMItIWJjpUkeQKH6VuYwabcDAPAN7
        0ljPOBLVt4TUumQpAJ/6N5lEXNzRFZar4fTh/8su2vD6GxCcd9YsyFXf06JlKjD9
        npoNqqqPKQuKjV3wwbnz/78XjdJDz80NYwcytSczkt24iboFiexmFG/Bn9TG7Fxs
        zkoZiA0tL7o7lvP4cPvV8JcW+2mpb1a21qjgBVEQcKGV7+gMeuDchq4fBH6gXIpx
        PgwYv4EtQ8OrGw5Pw8TbaswWOPJ6XIO8wIIw5aJOOn1+fS/zjwpjZEPCQ1KyKgbU
        aAEJAhBZNU26yjvLVdAWzFxS9oV3gekVnSDKXBjFbA6AE4FBFAZMtjMoZw/2O3yY
        NjQcgAebeDmy75eF/3iC8wH+rvb5G2SFkc1kftcsAjaTkvX0IoDk0DR0/PEzlDFI
        y/ve682it070
        =xL3+
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
