---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: filebrowser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: ghcr.io/gtsteffaniak/filebrowser:1.4-stable-slim
          env:
            - name: TZ
              value: Europe/Zurich
            - name: FILEBROWSER_CONFIG
              value: /home/filebrowser/data/config.yaml
            - name: FILEBROWSER_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: filebrowser-oidc
                  key: client-id
                  optional: true
            - name: FILEBROWSER_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: filebrowser-oidc
                  key: client-secret
                  optional: true
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            failureThreshold: 30
            timeoutSeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 30
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: db
              mountPath: /home/filebrowser/data
            - name: config
              mountPath: /home/filebrowser/data/config.yaml
              subPath: config.yaml
            - name: branding
              mountPath: /home/filebrowser/data/custom.css
              subPath: custom.css
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: filebrowser-data
        - name: db
          persistentVolumeClaim:
            claimName: filebrowser-db
        - name: config
          configMap:
            name: filebrowser-config
        - name: branding
          configMap:
            name: custom-themes
            items:
              - key: custom.css
                path: custom.css
