apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-oidc
  namespace: filebrowser
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:H4S2ty2ZeFtBUqVbyA==,iv:9nFvnUsYzJRieyF4j4lfS+g5MAKmI4bIIldbC7fK5EU=,tag:Z8qH4PDyh0yRWY+Ynbh0OQ==,type:str]
  client-secret: ENC[AES256_GCM,data:qTW6jRa/floUPjGMKA+ww28olcXbojbtiZE2ujfJ73g=,iv:qsxV92dNpz39M4FP49NkHoEhzW8H2G1cnRmGRHhzQuA=,tag:vyS0S6bExzm9+i4p0tgHNg==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-30T09:04:27Z"
  mac: ENC[AES256_GCM,data:NIh8xE4HIFe9HcQSuhUPmmolo47f9OS+zDOq9Ea4pkEYPQKAQcEwbGECRA9OADjm/c63VCAu54KIOM63IbKDOcPggsVCWnTKvZR42nsvSDR/pryYcU5F0zQBk0NzdzsnUIN9osWKn2oZGcqNHg3ohcAQ4sK3fncFHUeNYIsaQRs=,iv:XOrmdxu+amx255rUbXgu/an42N3Vp/Yu2qA7geIW1+g=,tag:0kLUiglfOk0kJRya0bS9BQ==,type:str]
  pgp:
    - created_at: "2026-06-30T09:04:27Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ//UO+5ZVoEoVTSQz4PfjsDvKLIMAn6rvfy3WI7w1/9iGga
        iWGs/JQD6bolhKjaTSoEvSG8nb4nJPyLgvfNeBQ7JaEPrN0sZ9hWfJeOJDKTs/Or
        3TBsMPLOHrHXuoh2KEF6CAUjbBIP2VmXP1paPfMKv6qV5dCtkcTcQ4COxRR/T4Dd
        cmT8g4T63NmRRIxaHQh1SZuyrWDJajQNfzxN48gtoiQrWV814kJO2rzEnu/rACQN
        cwATOlCVk/fbz03eX6UWq1YAhBojM6WC3hTI1/dgKO4hGwYYYYhefFAbI6KOtqvA
        GfA5pgbxu7fcITnUO+5nOxTrV9th/SOeArFNGEUIMCUDrVs2tnjngKeYqk3H8N/7
        dfk2lZtfz6HtctfagT4dVvSDd/RBG9z9d/fu3t7no20wxo71LmBMs3tDlRB2N8H7
        wdZBzA50xYI31lcecX+q4iEKBkWnlRRg/DVzSBHxLwRq9u6GpAaon1qragq0CCTY
        5ApWV6J1JZfAUCOm3/t9cxpueE00bry6rZaWWZrLY1ISSGUfD+e3A/zA1s0lKqQe
        DU4Sq1uV2TaijR1nDufTYJW1oTqgTdTsCI9C+nPbMnI4dLNZ5dD+fk4pOTzm7jb+
        iiccZaJ5ZX0Uc1biXxXgrndh+FtVxxJ0rA2h+Bq2NC1QWXxm/rmeu+vUE81kdv/U
        aAEJAhD+d33aTJmBkoRlm/4bJnXXi9WxJsTueb+2oe4jH3xDuHOncryM9NoUR9K4
        bTvg1f5ALNJEhUTm4AYQSacg5NaZkNbPyGpFIqr8j1n+Tq6oHMQ0/oFbIKqbthEK
        uB5KfaVp1LoD
        =JP0o
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
