apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-settings
  namespace: filebrowser
type: Opaque
stringData:
  settings.json: ENC[AES256_GCM,data:66Lt8nozOe43ndn5HtENc8zggGJqqbt8iFpEMBIm6mY84jGdHlXWlAzZq5Xb+tp13WhlnsvDk4xlkRrpZi8nfwST0/LIgx0PZC0ltcIZQ9qte/khXOmMk61tHBlZ5Y/tkLW0CUH+bmAgP1hc9Vz9ULGnk6Ud65EkSbf/AFP3YSbOB8AbiXDwFyOdWAFYmgqreNUYJPzESWRhaGtUYD6F6j3E5bNGO04XXykR4tbaaTryxm7wTlAyISwEM731qTdTi3Cf4GFZbBRLX8Ca7NxOTk+QjB1JQxAZnVc3ozHzYhQpJ3SG1X0yfuLOHLA6dl8F4UJoldljYbxzkG35+GpUTjZwRCbx50b924lxyvW3GhzAdmIUE3qIc2T2Aj4A1I9AGdvzBk5uiSqdu/+sUnUfNDgICClD7gejwScRQHBfzxRyRLH19X0w+/iufgRbe6DzucJdvJEBqinNzRpicqoc5X5zX5SLd16A2snWHEgWVPFwqpbJP3UsM6482WaJQeYhfehtxMk+ySHF7ZpVZIyq74+3NWz3MTB2eT2me2W1tkwQIWKzD136reyjjNP4FVkaPuhw1Lm5liV/yUxwGvDbySlWhlPpBFc14LQ51pe8WjVlu+YtoqrIR46Q4kklBaFuRZx9JrqAEnowQIiu1EGTLAc5fCL0c7a+wvjoPFjlz2vnv253QDHvJAftrlZ97SKI9RXxeVQOoaYDmL10FMCAeTZXtsvULqM+We78T9L8MguyyxfMagL5Fe4gBPv2288+nGQ5nuVgTL/oDZVh/GJWLVHG1iII2jkr8H7utrzQzt8jTWbgV8DXGbRIK+PIdYEd21MG8A+I/vAZptzlfDJYNpkhF/AGBEQK/J6Cni3hYO+m044S4AjAxk2MkyErE92CZ6CYiHBe6c2GMkeKoe4K4uSudQW6NgU29a2FgrsG3Tanp4nkNoK+LP9DwNOzc9QAiGidgkp8jnnYWzEMJOJjCblxuiwlhdB1VKo4O/4KTcnnkmKSCwAYWGcPxlOxu/o5/FapPoRymig+14DCcZso+95NaSCc/T9RQWKmGVwCw/K+uQ8aExFRLBv+f1QZEctPjIAz72HpqVD9zoXycra8ylcexWBuDXGMhoOa9dGvoNE8jGVA4pbDMZ5SenA5rQFueJCzbbeIuKvNhzjGqPQtl1ILuWdWP9mSrjVCX8NO8aZqVi2bGD9exe6OgJGbZNXY3Jo53IOnB9DXdzWjybdbgwR4qySAr351x+YzXHtS6MB0TOKIyR18nVzeLh/onsUzp23kGPcJ3ky8kOka4dLSHCSRVW6I0lOLCnig855wY/aDiSQwr+ex1EctmKRIYOCTk1kld8hQO97nUYNdBOrMFBE5Ljf5V7YdO8eP1iwkLcBMqP0T0285PCYKlMpFkun4APxHuX+iVaCm+HnPCmH+3zizez7owPhYqyu7pByfBmGpPWG5QPPcMnKVZqHVlmiTp6v+4UsDpDSvtbClUklOrDwPDp+KDzaqvkmzTkHbt16Jjz9AxJ/6roXf6Mc+aHLST09ehf/v34auWr1uEBzth4WJsStr+kooH1dQNeroNWY3RqL7wZfEsKRfSEyfPaJ9ktLhGq2yxScV6iNqnttVWd/rSw1KhaqTZoYpJTxMJU6V5JfvYwPrx+9Pmy9D3k1uoVnOBRKSwpADWwZO8+y9So08E0hkpzeI7BK7Q6I/RsX0FtfRasIyXa6W7EZcwmUSxdPOmkkmw6olfuQaO+yMkh1AA8dx48zxXytNFd+FW38xdXQx4zQlR0YNvNMYDfcyJad9hSrpCFfBK0LwKgQD8u3dCsGEU4UrgYpUcVnzdom7WAaDdfyAo9tFJ8FdElaMxcgtlr9lm07LA90NDCabpqHf7G5OkjHjzxgt19AOaqaw0aQvDjJ3g/9dc1zPsUZHQnP9MrQ5oZijtbJSpeKjpk5TQaugPazP5Qn1jBjIm4xLhyYT+R0L3nWJLCtQOIccHje5QwiQka1HBk3qQKiq1NHZYogNljqgW5BuITX0pdKZhmRoTm5eEjDpXJFTW4HSHCzSitePhsyaFH0hjH79VzYAMnKkpBhQqqudvmxBArQtRruDkLh+VzbgdBTuzC4Lh0If2vu5wcbOXHltLTw6zEGuzEVmKOGPu+3m1Br0MZUqt4yxPi1UaLT0wqX1MQ1cNk8b3RXftp7NooN27pJIkEEtru3rxym/Bd3TDYMdhWrXzb5zLXRZW2Lo9fd1DL39HwyrJkO03+bzvfwNzHqxveSGN2XJfNMdtXheMbqeC+cCMgm9Xkotmtqzmiowk7/YmM6Jho2GFccGZWD+m7C7sucdD3EtOMSzbNKj65pf3pM+TOo2p7Jw+f86uL1XIh81bz9G4E9AqdaSSeWy/pshVmHSc24Fp2KZY+xdUn4UgrNj69innaknUrvkTbOlpMxPqi0ItO7kiZUQNBws7Cg1EtTYhqOjz+wW1CCd+DftWvzHXZJvDdbIyTD7+xZ8v7SvmMDK/WPu86pfEE0HpTdB1MPnCVP3+Ct8IxF4CMC8sbh/YclB9Y5aNhhSyRpkAy+AiHvuLuw9VwELSMwEwcP+XpvE9EXptZx+cLArWgbU2GeBTzfTmV9LqLeRW/55SgehFHPEKdNrB0ylSKwJ463W0wQAYF8ETXin2u4EnB7cQknqctuBXxCxr1UXbQegQPraNizPI/KFUJM5uj9sf/p330mAey7MgOKGkDGLS5ifVFqU6ALkKkawd3sV3GNWJiB9iXOsVzYF+kjvfj0tRXtlzghYlBKdOfIL2I4JyrfsOulCdWL7GmCGHqGWdr/q70lAvoPdE0d5Z5sNnnOdIytmSa6OdQ==,iv:Rr00jqZAzTeBb6dsvoVbTA11h2wsp98bNW98koep6Z4=,tag:zlEItP/SIhqVuyO6CFURcg==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:12Z"
  mac: ENC[AES256_GCM,data:XttKID23gVroODKE9EiN/v3qwDPfCI4VwGY5v//6TPKdqLOq9/PlWZEfwMxyhGHF3wEvwWOWRLfpSnrYOA/GcXOaj4yNknXNsbOXJubMORfTG9jYdlFrXANRVa6Js5K2ScVbAAFYbVxv+xR6srrvc+Ryk5ZzDnjBeEEgXuyWea8=,iv:MovOfZq7QiQJ6XMzsKdsc0itFu2Dtmj67Coe0yZ6XbQ=,tag:vIjjx3mCjaI1FWc4gN8UAA==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAAqpwrrZW/jUXVsWxkqXTdPhv4I2TGGqd9wMj5XFu24wJb
        ERdmup78DCFmpZlsJ4nEdyhqyMQrK3w9iFccaSSIQDK9ZC0zBBxB5gVNj6B9ELVz
        fiS9XYOomMtythQXrWdOAMAU8rJ0jsvA5A4WfiKHHe7ODry2gDXvPLUCHGpCZgrV
        +AGQhfG4PbuvL8g1Hmv+nbAM2SXk28Rg6XvS2QYZIth/XbCsnvVNZFBw6awrBmjL
        wwFlelfwB+f/tXG99R896I2ay9AAfFdAfTXO/qQlF9UEHF1L3iPVTvxNr99b0G0W
        QErV7sq/nmSbaGKXLrVHjfQkpkX7yRLfJHUuRe5NZ2ecv+T+BqTAYO3Gt0FqlSjW
        o67vm+xS70UUe9FNTuoDM/Fu/2b2JjuMxEn77/eqevQMR/8k9rCBvIdz9CcI/5Vp
        rLz+ZqtOzD1TDpx6ZczxZa//g5DBHXhLo9a3LKPzPQRLcwvBweNNzfmxw49OS9qG
        3xLNQCRDVniK6Qa83o8tM4g1YTayozkx/Nbhy8O+E+kdNZ73wA1RK5nHg2dEQX32
        qY03DxkSrpxwrNWJ0DM8NpV0XsRbBe69ndOdPuBYHZbHn7CW57qoeK4zXtapVqSW
        bTtDvBCYsytm0klg8gsigl+dKHX9q+UDgPkyJiKspq6RpTsIpevL/joRsCUI1dfU
        aAEJAhCcK7rjXcAPwDabt2F1PO0FPTP5dFKyNT0/cgrbLoJTpIoSG8XAwngv29Zi
        8ggvbGZaAAM01MBRs3Wn7mW99CIXriO+pv7J6Az4ZJLwu/a6e36mcJq1/fHnCIRl
        CasCWOdfKZ9R
        =Tnmt
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: users
  namespace: filebrowser
type: Opaque
stringData:
  .users.json: ENC[AES256_GCM,data:MmsxDSDVms/eWFzoZ5Vr/pu666DzKXSZAbukWunhLZblQFaH/PTCGa2dtVrOSW57CVQ6xqI2jPXz+2dv4EnG4YUTPvQD8fmYTavYVyQsF39xwUcz/c5VZU03pDCKDhffHkisw7vK2HmNjAJzFo+iwpgWBqWPZyjygBm6SRMwmw+kgbcisgsHzeJ3yYFD5AjHtdCRKgzWhEB3AW4ZUjvqlQiZb0GcgOGwD+0Kw+Eg8qzhxPRC+9SLts7bcNec5cg88nB4vPWyFfDvL7HFcHhKzXeW2WmlKln1HDVGlctsZ9ydnp43SNC/uPeSTm87gDFPwIxYS3XFKqkoi7xlMoZS0H32FA151Zlc9hPMIkizeWiOZcK8oMh4cUnvYEA8FblcOLjvb9nUjKGLAr4AyWrdcnEymjYr72yMu60a9uFXr23YOXXf1i0ysSVCWQ6RsSi9k5eGAuIeEhA2ecEYKC2xCbGo6yyMbPyroBxVu3wnBwlkDvgywm11mxNoXXnwd7No937qn3ztmQYHWlPzHL323LXaO37UpJTBLTgFrTJ9AorfOBQQEy/fkg8f47ilQj+RzAWj4KxMguwykcPIUrvXK10mScA+goF1Nvh1p1n6snKLNST2Bg66gB2t1Dgpey+Owy/EHK18Nfj4OK8t26/lMyQflEg+JTPyEh/mXHIzdaempCVjKnt9SJDOrlm68/AcKgmjOJJt5dRymVx4sILIOiheubkv16sgmOUpt34lg0dos/fmUrRcDoV5t3xZ6uuPMT7L3UZITO4vtc/m/DwS+3ksNhmCLuUTFRNQgc+VMTr3Lx0OL9PePq0rurGtFCc9YS75vteNu1R35KRS5SzkgX5mTLJfweI4a/Q7N50fKmu3dfIgl21PE1fDLzsMRRHXhPtZ0nN0iIe6eM2J91pI3Jp0K1/e/WQHgOBmn3My6LPJ+BRtPlCBgKMRZLwqNR3OFmcLzxYNgKJbqmmNH+wa52fFfOUswqoTWPE6MDpDM7Cd9FriCZsNyBnScDyEVGk5LOKv16fbi2hZMxtDkQfDgy3GbYDrKsurP90g0qHpr+xWOMMMriw3cvl0MKhUl8Ni+MZw/9iAfXoWsUpdloJwxchxbuvq2Xsh9rY7C11YJJGtdjf2xerSLtGLqve4q1SlmcrJEQyTweR6nzlKDjkSLoLf9b3KjbH/BY0+y8gsw7RX1A5A3rKqwo5o6LBh+D+PEDAqFbK5j/UsQd70sTZOyafagJ3RkoJ3yqhaaN7KdyLw5O0MfJ1tHVKbpPOyuf0r50S6Uh+40PCFsyjBGPbs9Bh/xaCbqS3KeByhUUylIlqeiWh9FQmwA9pwXZTozZBkcGHfbiB/X+pEKNVRvP6RDpwzr8Y1B4FeTzF0kBqAhwhYLPXtonCP3N/IvBct2d7RDotlFBym/v7w7/xDTU/XQxYOJXv+8jKPbPmltV5cZmrePm+DcXJlA/u0jpotyomYGxaOB1QqliaqpXquewN/t3lm0hIT1P4rzx7MILrmc1QCb7DajOo1/hjVK55k3bVpzE21mcnk1WqeAj7XiF3QGPhlrz0hWlf0A5m5VDk2B9FpRaPSmzB79lI6GDJG35VWxvJ4Uf2Enx88vt+icZHQfetGYud4EWFsY40NConbDDRlapwWCWIlmNGBlRBTieAwleWEpNucwB3vBEBXzZ58gytvV90Nquldgcb+nSt86xyxmW/7nRG3oGBITrWae7pf+dngnWmLJ+y8r58eqPqTm7rvZXGPUzS/14gzDNZDtbv7eB20D/8hoYakA7uzbxadl7MhGOySFEvLT6IxFOQi4r/vVOHUF9uX+dn47pi9QefCsdZM8EdVbQtIbyMHBg0a3WRnDYJV2k4rga5Xmy1pqkMlYc2ZPC9cCPhSeKHKVMklSbNAe++g2ih7R5UVMMvRtY+J8KU7evi428Z9dW1WI8b6VEHlcUn2jeEQmR01Bg==,iv:aEhwCAon885dOTQ68tDz2PLS1KwjGD5en549wumhreA=,tag:WkGw21Qa0DAonc/+ejYDcg==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:12Z"
  mac: ENC[AES256_GCM,data:XttKID23gVroODKE9EiN/v3qwDPfCI4VwGY5v//6TPKdqLOq9/PlWZEfwMxyhGHF3wEvwWOWRLfpSnrYOA/GcXOaj4yNknXNsbOXJubMORfTG9jYdlFrXANRVa6Js5K2ScVbAAFYbVxv+xR6srrvc+Ryk5ZzDnjBeEEgXuyWea8=,iv:MovOfZq7QiQJ6XMzsKdsc0itFu2Dtmj67Coe0yZ6XbQ=,tag:vIjjx3mCjaI1FWc4gN8UAA==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAAqpwrrZW/jUXVsWxkqXTdPhv4I2TGGqd9wMj5XFu24wJb
        ERdmup78DCFmpZlsJ4nEdyhqyMQrK3w9iFccaSSIQDK9ZC0zBBxB5gVNj6B9ELVz
        fiS9XYOomMtythQXrWdOAMAU8rJ0jsvA5A4WfiKHHe7ODry2gDXvPLUCHGpCZgrV
        +AGQhfG4PbuvL8g1Hmv+nbAM2SXk28Rg6XvS2QYZIth/XbCsnvVNZFBw6awrBmjL
        wwFlelfwB+f/tXG99R896I2ay9AAfFdAfTXO/qQlF9UEHF1L3iPVTvxNr99b0G0W
        QErV7sq/nmSbaGKXLrVHjfQkpkX7yRLfJHUuRe5NZ2ecv+T+BqTAYO3Gt0FqlSjW
        o67vm+xS70UUe9FNTuoDM/Fu/2b2JjuMxEn77/eqevQMR/8k9rCBvIdz9CcI/5Vp
        rLz+ZqtOzD1TDpx6ZczxZa//g5DBHXhLo9a3LKPzPQRLcwvBweNNzfmxw49OS9qG
        3xLNQCRDVniK6Qa83o8tM4g1YTayozkx/Nbhy8O+E+kdNZ73wA1RK5nHg2dEQX32
        qY03DxkSrpxwrNWJ0DM8NpV0XsRbBe69ndOdPuBYHZbHn7CW57qoeK4zXtapVqSW
        bTtDvBCYsytm0klg8gsigl+dKHX9q+UDgPkyJiKspq6RpTsIpevL/joRsCUI1dfU
        aAEJAhCcK7rjXcAPwDabt2F1PO0FPTP5dFKyNT0/cgrbLoJTpIoSG8XAwngv29Zi
        8ggvbGZaAAM01MBRs3Wn7mW99CIXriO+pv7J6Az4ZJLwu/a6e36mcJq1/fHnCIRl
        CasCWOdfKZ9R
        =Tnmt
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: ${BASE_DOMAIN/./-}-sso-client-secret
  namespace: filebrowser
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:aZh1VVjzpEf5u3KhvRh+38hzul4BiPhujflC4KUciaM=,iv:MPicjzwKXXUq+KHVut2YfTPnmFjkuM15fYHeqvv+Eb4=,tag:KIKwf1s8H18SpPaGIQ2nuw==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:12Z"
  mac: ENC[AES256_GCM,data:XttKID23gVroODKE9EiN/v3qwDPfCI4VwGY5v//6TPKdqLOq9/PlWZEfwMxyhGHF3wEvwWOWRLfpSnrYOA/GcXOaj4yNknXNsbOXJubMORfTG9jYdlFrXANRVa6Js5K2ScVbAAFYbVxv+xR6srrvc+Ryk5ZzDnjBeEEgXuyWea8=,iv:MovOfZq7QiQJ6XMzsKdsc0itFu2Dtmj67Coe0yZ6XbQ=,tag:vIjjx3mCjaI1FWc4gN8UAA==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAAqpwrrZW/jUXVsWxkqXTdPhv4I2TGGqd9wMj5XFu24wJb
        ERdmup78DCFmpZlsJ4nEdyhqyMQrK3w9iFccaSSIQDK9ZC0zBBxB5gVNj6B9ELVz
        fiS9XYOomMtythQXrWdOAMAU8rJ0jsvA5A4WfiKHHe7ODry2gDXvPLUCHGpCZgrV
        +AGQhfG4PbuvL8g1Hmv+nbAM2SXk28Rg6XvS2QYZIth/XbCsnvVNZFBw6awrBmjL
        wwFlelfwB+f/tXG99R896I2ay9AAfFdAfTXO/qQlF9UEHF1L3iPVTvxNr99b0G0W
        QErV7sq/nmSbaGKXLrVHjfQkpkX7yRLfJHUuRe5NZ2ecv+T+BqTAYO3Gt0FqlSjW
        o67vm+xS70UUe9FNTuoDM/Fu/2b2JjuMxEn77/eqevQMR/8k9rCBvIdz9CcI/5Vp
        rLz+ZqtOzD1TDpx6ZczxZa//g5DBHXhLo9a3LKPzPQRLcwvBweNNzfmxw49OS9qG
        3xLNQCRDVniK6Qa83o8tM4g1YTayozkx/Nbhy8O+E+kdNZ73wA1RK5nHg2dEQX32
        qY03DxkSrpxwrNWJ0DM8NpV0XsRbBe69ndOdPuBYHZbHn7CW57qoeK4zXtapVqSW
        bTtDvBCYsytm0klg8gsigl+dKHX9q+UDgPkyJiKspq6RpTsIpevL/joRsCUI1dfU
        aAEJAhCcK7rjXcAPwDabt2F1PO0FPTP5dFKyNT0/cgrbLoJTpIoSG8XAwngv29Zi
        8ggvbGZaAAM01MBRs3Wn7mW99CIXriO+pv7J6Az4ZJLwu/a6e36mcJq1/fHnCIRl
        CasCWOdfKZ9R
        =Tnmt
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
