apiVersion: v1
kind: Secret
metadata:
    name: db-backup
    namespace: gitlab
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:AMhKbfhTV26yrew=,iv:+FdslVlq/RRWfDx8NBSgCpjmluHOJdGC/Oyx2d3uY5c=,tag:hekWhwb+H7qAuNbgjpUY9A==,type:str]
    secretKey: ENC[AES256_GCM,data:Y1JlXX+4Ah1CcSwX7iw+kybrok7aJtlsuBo/U94vfQGz9f6LqCAmUA==,iv:3/mPArjuo1u43VXkXd8fh7K3a36GKLdeLQUaNJGJDPY=,tag:fsENdemIOPthQvuHBYyayA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:39Z"
    mac: ENC[AES256_GCM,data:QAoaqIIJyB6MPHyFj6TLuHx3hGH6GmLsAG+0D+ymbaGeX/hM8s7p+hIFPpg02QY04s5Gpj/RklQQvaHu0kp8eJI/BoNHjPdf6tJr64rAWxTVmdSizOgIHr2D0tP1gyZOvDpIBJou9sD7ixu4uPGMiX4jaGCkshxniZTP93amPr8=,iv:7aCnBne2OXSgt+jxpEofhnflwLoEBHaGlHqxZLlRLJ8=,tag:oIWFWFTZmLuJXNuiSrMF6Q==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//f2bfSZS8nLSQ+hciyBCyBWLruZl1hItAb+5tBcS6ORfp
            RWIMauP6kHTdXmu+AK7PsUSIK0m+mPYorMXikcrG3YrZKW5sKe2fbIjm++BKtDGD
            ss0OTN5UoYlLuIJPbrWK5b+GbdnMn5J3PWvH3+5Dn7/gfDdqRLrgwEysocEnJ2+S
            nbrOLt6b3dGBm+bJHSv+CGJ3qKxItyDQuiKS4pPKoD2si3FSgyyAX9+0kX7mwNnc
            CmUEWy7tGUPZz2wGN8Awc3zCpXj+tINCWwVKv5il5D5MXpc64/q9KDr7hlJuk1j+
            xxdXeQQA68TJ41FQfwm/C5C7heiAsIzcSyrCDi3U9ZRXH7KYZVJ2K0kRBJJhFf5S
            ++o1amsUtxlDy3J+bfOJEs3CZJ90sVC0mE84uME4OfV/FJf8B6P8OyBO3J/gVUM+
            g6fXayFLou+AsO50Tiq+RvIIkmQyc6DvW14i2j5L8VTHl++JsaxhRlXTbaK9VMVs
            l29W2F6aMNnjWUrWSf3F0puxqaaaQTZU4ewKeL/BhGxr7uUcgB2OhBV0WxQRAm8O
            MUakbEfE5P9CvLXdwd20YaU8oqVo12wFwtFOH6tvAa0WI9hEtOPuAFJneCBGg+nV
            MaboTKJRVw0qE0RtEPRpeKlrUrXh/FDpiPEYZLQZELVr3CIuNm2SUCKRz0vgOGLU
            aAEJAhBhrnLLLcJR35Ie5gNB5SvNiHa/F/f++06T1PWBVJCwlsc1MKRbnpCZ6T/m
            Dvq5urs7BvvwOV2NKMJeYMnh7DIkSnFbpvdT7dsYHZoUYYUEC+5jHS349nNzeo7T
            Z0V4Hyktcxim
            =icyy
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-postgres-registry
    namespace: gitlab
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:F28T4Ru/HUA=,iv:dY5uJb/YKKP9Ggn0jDYEQ2aMhZtHV1kG19EeC7dKfwg=,tag:PDm/DgVfZKlykr/Ig5YD6g==,type:str]
    password: ENC[AES256_GCM,data:lzATAqffAbVBNXLgUIDiOvPmG53o1TQ2G8WNTXtYsT/9up5miQ1AUS7m1Qo=,iv:QsniXCAMok6NDyAceh3sJcrOTwaWU3wFgi2rvDqEjh4=,tag:OAXNYL2fPQnVWRISlM7row==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:39Z"
    mac: ENC[AES256_GCM,data:QAoaqIIJyB6MPHyFj6TLuHx3hGH6GmLsAG+0D+ymbaGeX/hM8s7p+hIFPpg02QY04s5Gpj/RklQQvaHu0kp8eJI/BoNHjPdf6tJr64rAWxTVmdSizOgIHr2D0tP1gyZOvDpIBJou9sD7ixu4uPGMiX4jaGCkshxniZTP93amPr8=,iv:7aCnBne2OXSgt+jxpEofhnflwLoEBHaGlHqxZLlRLJ8=,tag:oIWFWFTZmLuJXNuiSrMF6Q==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//f2bfSZS8nLSQ+hciyBCyBWLruZl1hItAb+5tBcS6ORfp
            RWIMauP6kHTdXmu+AK7PsUSIK0m+mPYorMXikcrG3YrZKW5sKe2fbIjm++BKtDGD
            ss0OTN5UoYlLuIJPbrWK5b+GbdnMn5J3PWvH3+5Dn7/gfDdqRLrgwEysocEnJ2+S
            nbrOLt6b3dGBm+bJHSv+CGJ3qKxItyDQuiKS4pPKoD2si3FSgyyAX9+0kX7mwNnc
            CmUEWy7tGUPZz2wGN8Awc3zCpXj+tINCWwVKv5il5D5MXpc64/q9KDr7hlJuk1j+
            xxdXeQQA68TJ41FQfwm/C5C7heiAsIzcSyrCDi3U9ZRXH7KYZVJ2K0kRBJJhFf5S
            ++o1amsUtxlDy3J+bfOJEs3CZJ90sVC0mE84uME4OfV/FJf8B6P8OyBO3J/gVUM+
            g6fXayFLou+AsO50Tiq+RvIIkmQyc6DvW14i2j5L8VTHl++JsaxhRlXTbaK9VMVs
            l29W2F6aMNnjWUrWSf3F0puxqaaaQTZU4ewKeL/BhGxr7uUcgB2OhBV0WxQRAm8O
            MUakbEfE5P9CvLXdwd20YaU8oqVo12wFwtFOH6tvAa0WI9hEtOPuAFJneCBGg+nV
            MaboTKJRVw0qE0RtEPRpeKlrUrXh/FDpiPEYZLQZELVr3CIuNm2SUCKRz0vgOGLU
            aAEJAhBhrnLLLcJR35Ie5gNB5SvNiHa/F/f++06T1PWBVJCwlsc1MKRbnpCZ6T/m
            Dvq5urs7BvvwOV2NKMJeYMnh7DIkSnFbpvdT7dsYHZoUYYUEC+5jHS349nNzeo7T
            Z0V4Hyktcxim
            =icyy
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
