apiVersion: v1
kind: Secret
metadata:
    name: db-backup
    namespace: nextcloud
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:DiCXGED6ftWw/kghYsY=,iv:9P3/4THMycmMa3XzMBkjOc9tDdpIVCYCJ+QnsXYqlzo=,tag:rbbojwCXsTS8ZydlL7zpzw==,type:str]
    secretKey: ENC[AES256_GCM,data:QLx8vIVBqYZaxJCu/Ql8bJd9tuFzGArv9QnV/b+ayyoXyD6z3j2Lsg==,iv:TGTrOrGYcQzBs1kVxWF6E8he7LNXZHXJ6Zvzup68qFA=,tag:Xa9nInsjN1ivcI1NXy5TSQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:30Z"
    mac: ENC[AES256_GCM,data:v80MR3d34qVHDkRBDFVD2PR3qwpVtxaj7quZU/NgUEwe1f1ApJ9j6FlPqYvur3rKzda6RpYi1QjoodmkSyYWPkEyEsv/TqkXoefZ1p/4C56wUTs0IPZwgLMUScT9o7BwRq4R2yBcWB/dmKFgKGFjKhRWz0faBxeZ/w1C2FtiPJQ=,iv:u1RLSOXkNkBPUg2fKAkbHQoko+UsCGjm+712SkZe5gk=,tag:kLKKm32BS/XoEFvnRPNQpQ==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//fwep07WB9ivq4Ko26NrAqRqQOipVOS3q2gCQuDZw8lNy
            gfK9cGFk5SbSd7wIZVxnAXHX8gIY/x1UQW50rkE6esFIIPmTO7ocG4eLCRsFlMfk
            jwp/dNDN3sLRAN6xOznKoN+nXNpyWv//cM38O7mIX6ZeQf/kd1wH3Why6sdh0Qui
            j0qMnrPg/tcNhMbuIKBhyjsGbE3+bTdCpVShk04Uvbpn36p9I0oaS3JyOF9q0+OA
            y8kKvK99P1YP1rAMcHfxXtCmeGsSjAiYJwq8bbqVjhLVEh5iGUGyXyqSgq6aoE6c
            zgWees3AeaKFYWcDTjlQVtKpWwU6T1ziRDeZ40F1cLa8J1HjPE7onITUIp8S1xP2
            XAFM5ncbE6OE7ZOpfaOfOSJaQVl4o8Slzubd5P9MRTudm9N9Ru9TAhYE9I70ccvt
            GTDxcI+UpYIA7hlhGb6kafV6DGUQi4k3OfKSG/o5wR1HNSt51woS/ImiHtbt7dMs
            sb93zemtnh+Ae69p3kBmu7UYkkWCaz/+mHdotfV90xHu/l+BZwQxMaPbpR6R7IB/
            jfPoxKNRGrKOAOMRhiqEAOlOrC+I1T6xaehOLlYu40nGymVhOPmPw1/eXLbCaROP
            3f3U53eFh4a5tEHEHe3gFLOhCEYU61AzbVq2iRFcPRKGxRL4nrrlk8PYwMQkQoHU
            aAEJAhCflBXyH3jedtbNkDJz8Eowmm7pf2mH0A1adVI1k0F9FVz5Nrs/oBVHXxjR
            wza2d4cmHSKqMTjNh1D5dC/yh5MkqKEwV3JW0p3+jnqPpv6ZPe+wF1uv+mHwuflC
            HzlmC8Z3XZsO
            =N2GL
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
