---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads
  namespace: metube
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd
  resources:
    requests:
      storage: 200Gi
