apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:e95O2bONL0f5N6qcMMXtKsN4XXnLuYI66jcGHDO/WWpBsXxu+MOFHSA0k/gOn51GB2QWGn2dPfYvjrnPi0zHguzkyzElPIuoo4jIUhidqQTE+1cfhL/ZHhtJPk+27CJHRHgDQikhvPdP2wYSHfugYukB6lZYkhmMQz4DxMDIzioc9E4gXQvYCCpoSdV7WAeMQKtekrZkdMIlvxxKVER+ZO6+9sfnO2VZbB9BzdN8bqZCMtjSUGnT68qwgMH3taX0E1m98pgUNBtMvE9O6snov/vSRvvCdXr3IT8bCs+syaEo31iGnJyKWITW9xcBaRsboHZmAMatZMiFyRCBnghn9h1CsBZpBkgfE+x0rFNaIDNxxFk/ZSeh3ZDiRvEz2MdB7NL6O04o9ZdqqbANIVlcffByrhPIojcT+6pQG6dC+1iDAiB6Xvj+Zo1iaeaAxn0Uq+ylZFCS8wt8RaQQQ9zoXfgJO6N0wwaCWtwP9WSCuOEqr9DxlpWxoKia6usOu8YloO6mRpw5T6o5tgOmAevvH8wN7jPtKHpe5KbdGEPr2Vyq9LBv3rOCPy3XkxNnqc4j5kABduZKjqh2TrRuxqTr4o0jFJDsFNKK0Yxn/2PUr58P9VuB/w7u3sYS4MlZJrOIHI8HYewpdBCfB9xQGeTdATY7TIQiIWb8yGvLpsl8kHz++nTezBeFO9U4XJjY3rq6DBu3lHgWOJcJYdsAD3wp52d4t9xWKh1yqnmDLoTl2dB9WgsEbKzmawaqUSos+5s2d/tUj87w11pL4ChSQ7vrcNN7or+tik+ljz/sls/VRZwotirhTUAi/GjYLA40O9KFFZXADOlb9QSfm79oRSbTA40bLQevP+7MN3YvovOCDFswJaU0bk5HBK06hs3uOQ5CHHcd/fO3Dd7+voGwnrTIIkiqGVCMfDquoCn7nO56OMGYXK6N0bmvJbxmR2uqKKSmIUSfFH5VK/0ch2j4ky/dqAMNZs3J7iL8kls4zbN/Wb9P622n+eGRL2dWObxf0wGnTZJy77hmgnFapjMc/zL5PARdCFo6aY6rGus3dZNXYOI28JRUiZFcyOWcmCKfqcNf4uM1t2+bDWac+Zf2MJM65wD+F6RhlqcQFdNlj0EXbeJJDXTTOCCsBrH9TXFl4gzJZe+fGPuZoFJJdEP2,iv:ITNLDP29IcGuw+eIURnV8ae/lb7lKhsDOCKmRgt8cPc=,tag:bR301x50B0rriay9K46L5A==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T14:18:36Z"
    mac: ENC[AES256_GCM,data:bkUxiCbfuT3bGn8b9rwf3kIvJ37QAaSJ1tmDjsJ9zDmGAe94NMi5XvvhTLkbzLNQ7SwuAdE0V+C0jc9QjPDiS4SLGGHMOXohbWZLVGrSSHMnPVGLGNPxgglWyV+BQjp76HNCVuEJFx2QE+3MOqP2WeVWbg2hWPdJxifTcBDV6Bc=,iv:QYX2a6srrZ+NrrPuLVMRYwuwE8+0/H64yCjWk012YN4=,tag:dqQ2QtiefxIrA9cia6EefA==,type:str]
    pgp:
        - created_at: "2026-06-06T14:18:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAomrhgAbAlGXzUzxj7kPU1QUT6SA8sRH4KansY86+WsMB
            2vrZ31280CcWqbJPriwdKe1Tedz/aCSxTfkiiSsYX3yo25eJrWCAgf+06L8pMqMp
            h62rsoHHFQFuzzwqVTotwqIDSTyzIa7NO3SjKZgjmPHjXb10bEXz4fqlraBiBYIU
            9aEew9Vi3+WmxGpNj2Z7chVrfFaHSy6aYrumn/hKpor03K7YWhiNU7rIbKlBYKWS
            j5uDXdcaS6lh1S5tGO7RXmW6ar6C10efHTu29ujx6akUr/7P7xtoFqXubabkXq9A
            HAMcaZf5IYECz3rbWeJljj3ZvIY7lnbzGVLM5LheVaUeNXRrUq7vutsa2sWkCO6c
            1GLOJFUYPoxPlZ2X/pYK6mHJsajxPfTAzAwZJ4GBtw5ObWUM0Cs4ofEI4q5PKIke
            vjS0ATDj6MCxK4+DplHweWXHaO9iIfVODwhIJqxl65Oaxl/0Fl+krny6rZI363Gg
            E4lsJw21hSQv529bec4XuGL64kVQqXFtzqZkHhLg86dOlWOwbppiLAlydRcWL5VD
            75CCMs33a9fsiesjfq3ayAwzj0Mp1zewNbziG+/sIYwhKVvDG11erWFR9z4ZR8Ya
            lD8wWjgEODTipzIljCw7Ppe0URPwe9F+oEImDEKg4l1Liw5wDK1s1I2o+ctH5ezU
            ZgEJAhCBrkLEoF3rwV8Gs99eI+fVK/Fm4weXAwZyZm9ielrvWevhwCQyunXT6YDV
            df81vByiEvbs0ChfJkMm5d2ZUqcOOFBb6outId3TxHbqkdI2oyoP7lr0zRpfR4j6
            NRbS1B49MA==
            =/UVQ
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cleanup-gitlab-runner
    namespace: gitlab
type: Opaque
stringData:
    GITLAB_TOKEN: ENC[AES256_GCM,data:aS5D+M+xHHF5KYfFLVD/qOPt7U0=,iv:ohLBiLCYG2/BmhfMCa+RCtrTmCaCM4QccLNa5TPuTZg=,tag:VkHyl+XEPnXlzfMGm0E8nA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T14:18:36Z"
    mac: ENC[AES256_GCM,data:bkUxiCbfuT3bGn8b9rwf3kIvJ37QAaSJ1tmDjsJ9zDmGAe94NMi5XvvhTLkbzLNQ7SwuAdE0V+C0jc9QjPDiS4SLGGHMOXohbWZLVGrSSHMnPVGLGNPxgglWyV+BQjp76HNCVuEJFx2QE+3MOqP2WeVWbg2hWPdJxifTcBDV6Bc=,iv:QYX2a6srrZ+NrrPuLVMRYwuwE8+0/H64yCjWk012YN4=,tag:dqQ2QtiefxIrA9cia6EefA==,type:str]
    pgp:
        - created_at: "2026-06-06T14:18:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAomrhgAbAlGXzUzxj7kPU1QUT6SA8sRH4KansY86+WsMB
            2vrZ31280CcWqbJPriwdKe1Tedz/aCSxTfkiiSsYX3yo25eJrWCAgf+06L8pMqMp
            h62rsoHHFQFuzzwqVTotwqIDSTyzIa7NO3SjKZgjmPHjXb10bEXz4fqlraBiBYIU
            9aEew9Vi3+WmxGpNj2Z7chVrfFaHSy6aYrumn/hKpor03K7YWhiNU7rIbKlBYKWS
            j5uDXdcaS6lh1S5tGO7RXmW6ar6C10efHTu29ujx6akUr/7P7xtoFqXubabkXq9A
            HAMcaZf5IYECz3rbWeJljj3ZvIY7lnbzGVLM5LheVaUeNXRrUq7vutsa2sWkCO6c
            1GLOJFUYPoxPlZ2X/pYK6mHJsajxPfTAzAwZJ4GBtw5ObWUM0Cs4ofEI4q5PKIke
            vjS0ATDj6MCxK4+DplHweWXHaO9iIfVODwhIJqxl65Oaxl/0Fl+krny6rZI363Gg
            E4lsJw21hSQv529bec4XuGL64kVQqXFtzqZkHhLg86dOlWOwbppiLAlydRcWL5VD
            75CCMs33a9fsiesjfq3ayAwzj0Mp1zewNbziG+/sIYwhKVvDG11erWFR9z4ZR8Ya
            lD8wWjgEODTipzIljCw7Ppe0URPwe9F+oEImDEKg4l1Liw5wDK1s1I2o+ctH5ezU
            ZgEJAhCBrkLEoF3rwV8Gs99eI+fVK/Fm4weXAwZyZm9ielrvWevhwCQyunXT6YDV
            df81vByiEvbs0ChfJkMm5d2ZUqcOOFBb6outId3TxHbqkdI2oyoP7lr0zRpfR4j6
            NRbS1B49MA==
            =/UVQ
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
