apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:MB2adJ7LhMnJmzZVZTagsL8v+iIh4utYbwWQuFbpePRD9WSQgs0Xsvo4Ihz67XmTVsWDJr3EWU9HLLST+68pp/WIlUn2dSWo1k6UEhDm2pl+cElkQaXhMGP1wRaeii3Vp2IWbsXO0HzGzl00GMT2YRETsez0nWdSGCS02M/vZCx0Rfj69+R3YEuXZE2PssnQWdt/Ass0+qOnn8w/WP0evjDGcOHPTnE4vEFfzu6TM9Q63dyodJ3sI0sebndmog3JlMhkUDzXe1inz+wVcclGEZidEPUaEP8pVExEYg13fQy8L64Iys5g2tCrLozqD8ypYK3dyxDzY8v/vw0cpvPlc9FwjdxnHt2T4G5DsMMCe4wX/Iclh5BOc5lR7ODxILvyA/By9Idml3wBsRdKGYC/5OKq18MN7qEaaoHVyd+LWouFsg4VjUuuSW0XvC0abI4OBIJCnwvFD+pqcAiuO4P5Dg17nw68rnbn9dPprnsklR7kzhQ7lhR4cj0kV3bXYn5ODxsqenu7xHnamw1F6U3Od/80UYEfjfygJ5MkV7LpDjD4BD5eO9gFqufxzr6IMbOBwX8cXgDPQ9kHXB/OMuv6eXJ+bale32CkpEZoW5DH3P8fA928jctaoHSrr+jROwxpwuJYIxjCtjaSyOVXl3+P+5WDpBrnc5qmr3JqV3X9FULnQqS3rlmUQAd3NkA+27mT7Cb/qUHvT8pfRdqziNlTL0RApTDzUVnKmM6po3FkKH6AYAqLs4u1J0jUQAeFthGY+PBgF/SwMAT0xXma3enl5jCI+cmYi6+GLf16SlKYGCmCnZCzGWxHF01FH3//lW+U0789yKE59Vv7Y0tomNhk/utCz/L6V0MXgNdl8WGRMsPDr+tqi/BmsYsTz4ZzjRwFA/Fc7eTpfrZBnTplRMKYe7c1aQfpsRULbWl0T0mgaG6MrZmyCyNhlB0QKxh4RR3/6MZ9AkqIHpsw//bYDHWkovDyTz2KWBy5polH378Gh5y+rHBryrHCGcbzJWPutbybbIyPNAWdodHQr3vQN/0T5CSjuzgV9mX3YL7WN0yF2QiQIN2vYTWPP72gCXixh4HGLh5ccyk+NPT5Qwb537WoODAdAXSRVqXkrn8bQ0L1vXof6uvYe0JYpsOLMOKigLagwxzTdsuitEriM9FzQcYbEazWz06PYxwDMv94XdBQxYKp2KGqs9TPaHN6ZM6fEN/nTWpWwvTINAQpMalR11dTSwDJsNQtfAiKKIlJ5dI+rITOdWZHNztTBqEDOWk2EIY5iBM=,iv:b/UVovvAb5MgkJza0r4U1xXjIwI6YoU6fAagFoYzdrY=,tag:Ok4PFOimUwsEfFsIX6nrKQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-08-19T13:43:18Z"
    mac: ENC[AES256_GCM,data:d2XK7ypOqKFepuzQQh8kQQstKt80lg+4fiOIB6af4AujlFtj9YdwBuKrIpSY8DMsa3Lr+3ersb4IQIrmGnBwgJBrRp0ZbN4jLIKgHQ4u7R/Me42+w9Fh9hcJnef+WMR0Ha6k9bEh3c6oYegK9EYN8AGWLaVleU0KQj0ArM4DQGk=,iv:gWUxZavRi1Sjfo4whSx68rqCMRxIgK99Z0RJQPh+fEA=,tag:6wSx39WBnFWDDMC8dNvEOw==,type:str]
    pgp:
        - created_at: "2026-08-19T13:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9Er/nCXHeico55eo6kvctEg8l+4LUPn9UhIsc3NnqRHRM
            4/XkKrP/7QwrS45tEYiXvRytTYmU7cu2MrNDLo6UiPW9GWQgu4hz3hB/LUXFgXa4
            YQYM+xHO5/dPZ58eQrxqAw8Fxtr3zcXclbJrmn/i9ze+6/lBN2xjMocE/NIDOuJZ
            7vXgntyMX5JjIvouRmZAcljJy2E3Y3Ok0dNVY8qU97uGlkQ4DAZP/PPg+LPyBKzS
            T4ba27KZUsB1Ri6OrhT5g3MofP0iM2nQjDq7XMeGVKMKRlpuFnxCOzDA6wSSWJIU
            kyl5KHTOCyvK1G6R3K8cBFkkZQ8W5Juy/ni9UCyTPE3WYMFe1/6pfuo8jhY/fHiK
            UuvAFKMmH1/fmvtWbvB2TSTWhMGaTmWzoIZC7T3txygR+8oUpVkEK44w+XEC+bFK
            DFW/3VYqzqyJLZHtT02nIpO3Lo56iJ8KwuIxtkIETr/F3L26w7HYzpjhgEEXCWrC
            Ju42NPjxPY2ZZR1JVCyAiHszTaAWZfLLhiofq1VR8MZPGHTwIxrN5LspF4caPq8M
            6FYQpH7po0xpSk9GiQIA1nUEZ+svr6NWV2QRty1HDyW2Nn6t3e0K4zwO5mH/PBGf
            +DYiP18+WftopvxzvFO2FF2z89M3iKHjZyxCUCm65ifOi6dfm0rWxAqDkRxOgTrU
            aAEJAhDHMbb6ofQ+x4jdjF8QCJhNdk3EfiKl6la1vAA4bOzAXS8mRUYjHRxS7P8n
            xoUHkmRU9oECs3KDTFq3Gb1VrOKquhNzt9/GZzmg2y0Oe1i8Y7tgja/Rg5b4BG7B
            4V05ME4uzBNt
            =aGqG
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cleanup-gitlab-runner
    namespace: gitlab
type: Opaque
stringData:
    GITLAB_TOKEN: ENC[AES256_GCM,data:sGOl10SlpMGnwacfmdIqJdqpcOk=,iv:sXb9w+sEuZMkkhRjKXnwZRWidYSbOuNE04c8z88ThcM=,tag:49eiOWR78MpisJ/0SdjO4g==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-08-19T13:43:18Z"
    mac: ENC[AES256_GCM,data:d2XK7ypOqKFepuzQQh8kQQstKt80lg+4fiOIB6af4AujlFtj9YdwBuKrIpSY8DMsa3Lr+3ersb4IQIrmGnBwgJBrRp0ZbN4jLIKgHQ4u7R/Me42+w9Fh9hcJnef+WMR0Ha6k9bEh3c6oYegK9EYN8AGWLaVleU0KQj0ArM4DQGk=,iv:gWUxZavRi1Sjfo4whSx68rqCMRxIgK99Z0RJQPh+fEA=,tag:6wSx39WBnFWDDMC8dNvEOw==,type:str]
    pgp:
        - created_at: "2026-08-19T13:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9Er/nCXHeico55eo6kvctEg8l+4LUPn9UhIsc3NnqRHRM
            4/XkKrP/7QwrS45tEYiXvRytTYmU7cu2MrNDLo6UiPW9GWQgu4hz3hB/LUXFgXa4
            YQYM+xHO5/dPZ58eQrxqAw8Fxtr3zcXclbJrmn/i9ze+6/lBN2xjMocE/NIDOuJZ
            7vXgntyMX5JjIvouRmZAcljJy2E3Y3Ok0dNVY8qU97uGlkQ4DAZP/PPg+LPyBKzS
            T4ba27KZUsB1Ri6OrhT5g3MofP0iM2nQjDq7XMeGVKMKRlpuFnxCOzDA6wSSWJIU
            kyl5KHTOCyvK1G6R3K8cBFkkZQ8W5Juy/ni9UCyTPE3WYMFe1/6pfuo8jhY/fHiK
            UuvAFKMmH1/fmvtWbvB2TSTWhMGaTmWzoIZC7T3txygR+8oUpVkEK44w+XEC+bFK
            DFW/3VYqzqyJLZHtT02nIpO3Lo56iJ8KwuIxtkIETr/F3L26w7HYzpjhgEEXCWrC
            Ju42NPjxPY2ZZR1JVCyAiHszTaAWZfLLhiofq1VR8MZPGHTwIxrN5LspF4caPq8M
            6FYQpH7po0xpSk9GiQIA1nUEZ+svr6NWV2QRty1HDyW2Nn6t3e0K4zwO5mH/PBGf
            +DYiP18+WftopvxzvFO2FF2z89M3iKHjZyxCUCm65ifOi6dfm0rWxAqDkRxOgTrU
            aAEJAhDHMbb6ofQ+x4jdjF8QCJhNdk3EfiKl6la1vAA4bOzAXS8mRUYjHRxS7P8n
            xoUHkmRU9oECs3KDTFq3Gb1VrOKquhNzt9/GZzmg2y0Oe1i8Y7tgja/Rg5b4BG7B
            4V05ME4uzBNt
            =aGqG
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
