apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:algsRqJby6/N51pjz6FaR2+LRpoXla2SWZBtkJWGR5HVswOBw5/2bJmlb6r6j2j5cQaLbTwkPmH9pDoUmNmublMrXL4QxVlcloeagTe5RBSC75uHjMqfJxjLvYVxM2h8WgHWkKRZ/LtrvcN1CYNXLnVQ1cCINZ25mMz17CpLvf/Nj9KWDPJDzgNHKraLtMED5uSOTL7Io3JcV6ya9ZvVQrwvtkib+uOps3ADtlaumSn0J40b0IgJ4r0Xl13+ogvgEXVXqLgBqAc83OSk2KgdiFIF16LcEVXpJv6+Tcf2blu9uVqnAnEkvRdWn2TDB/c1dLilwu7M1FNohx1cjdNE/lMFZqZ7Tg8CMEEZDl8qcEofKCbQ/cEtBPCC1CLXh3jX7Cf5YE5jl98SUjXLapqSClwipXa5FvunDHTw38tDgiTTfILrGrkbRuarVNK2bSHKVvuzI1dRnS8rVGw9WaSJotfmJpeQXZgPDWOCRZUkDnl90UGhW4FHWpzdbKCoOkU13gBJNpuM9u/LBB1PNY6i4jmRKiAFkFXiP7ASN7D2F88WWltEp37J1FGU7S3VateFAiYe9jfk0bx2yGzqoQBPkuZmIVVg76L0I1qVcab57r8bHBfyINNGifbDSqXU0Cc/lxS9vD6DPjh+KxlST/SbAFgGUXVZzE5yQVw3yOsllVU+NfHV2eCEbdayCvxmM5nyq+9rL2WJxgggnGd4DG4aT4aS6fJEF/HihY1Xve2l4iG6C8Q0Y0I2hPCig8CQBcSssJviaQKRAf/Ws8PFfOFxe5wl0/Vfl1scUbohfOdulUoPiee+vuuoHHQXayNy4Ua8XELJ4acEJABDuDjtcFz+9Yg/0PoFgCHbXMx2CSeIGBp5mXPdNTuWr7xv4Egt+aGGBtkkZIrrAU2oPSwUo06hXTgSJk4anPplYkxDrQzO3046trUO8Y+fxmipbVk3mT1wZbOjn0VvGoj25+S5cuGtqHUwd0Kmrn3pqBc9k+wpLDCovUNMR3QfRRv83eIu2ucoyxz8N2ISoisNBNNM+4wcNqYT1TCS9lzS5qMpSi3m1MK6AxrVR3f+VEDcJB3jLGpD93e0imozOWMoVyAvw+rWVVXfRfbh,iv:kAHQbI1EyI5vKm+1gslMiZp4I81Zyi/9dZc5zG4rlrM=,tag:IwVsNXgrUe5991/RkUbuyA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:15:32Z"
    mac: ENC[AES256_GCM,data:Rdx4oT+7eapHSk8+5zUiBEOMX5iXXt667n2uQA+cyRs6FrGpHtWdo02NaMD5wg4pQuA/cc8/I3IhSeCzlSxzcz3qcMKzRSgZz/7owAsMG+dGzsTLK4h0PhqInxeYQpW9gGZPEaohrypNACT8ZbA5mhNAvUEP2EWPbrleU8hrmqg=,iv:kzZ5qftl+exYRl9E/RQh1rvvuhOmeiosH3iEBoV1G1Q=,tag:yMq1Ck6RFRHyx0eF2gHZKQ==,type:str]
    pgp:
        - created_at: "2026-06-06T12:15:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAoASkNBcJGGD+uE719PF9LaiPisPCaZeq7AtVNguRDn3K
            Qza1EmBxqonAVzi/egyLGK+sriAoDvlO2X3liIwoqnKmgewEenxCXuAdex3fRVoA
            q8dCN9KJDtSpmBVTbN4cpG78IDd4lqQuUgDx6Yym34jWogYx7+7ur66441CmqTPm
            ZPRxufjJVroEOVmdZcZ1nlNtPd/bleUiQlKoCfeUl7C2JOhkYVqEzGzmgL75F5Ib
            5V3aZ/zAl/F0pFHMgwBFMyudYZ1hr7VS9tDwtoR5dt8924d9ATzsbKUFqZ7Mx+1F
            lfjmyX5cTjFFS8Zwx3vnCPHX4a4HU9+Zrama6nQ0668xQYAkr1/X7mRGz4o47mQ0
            jGlYyww0QuIBRLgr24gU1fiZz+GETrHqTqpd7PYK8FVxm8YkvRhrI4vYchfy+rPC
            P4UN9RecPB5q54uRj/CJxgmciHjJjr8vrnycpaNcX24iaxWCQ5QrbXb5onzTGDUa
            DOdvjok3Rsx45zvyMyOyptn8x3fFtoEgoozX2dBOfNAUNS7WC5hlkw0rF0MpxV9M
            9SJgChRQKmIfanW0WKo3FoblaSDEMjbp1NTgMdhL8uasJ9mHGqZppaghm3hNCy+T
            Yz8uEBD/mbAR11dq7TeAVnioGYiyXYSGWs6rqPFGpJHOiTv9ReJlpCJr3JoeSD3U
            aAEJAhDsAG2HuB6PRKQkdwkac/acH3ypSCU0+g981hA7p12s+qgpQ16+tdORvQ3f
            jqDNH3BropTNwVGOLtPWvZCS7Ld7AH6EWVv2wNiKx2ZpWKJgivZZea4+DXL20C43
            OwtfSb/yrLjv
            =l+Je
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cleanup-gitlab-runner
    namespace: gitlab
type: Opaque
stringData:
    GITLAB_TOKEN: ENC[AES256_GCM,data:gp5nKWR6+fdAdy1UgoAdjGKgsSs=,iv:WQnZyEbd6rUI0JhktTt1uuvcZmBlConUtJOwgsKs9Q4=,tag:jYEIylngH7dE5RGyRSaCJA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:15:32Z"
    mac: ENC[AES256_GCM,data:Rdx4oT+7eapHSk8+5zUiBEOMX5iXXt667n2uQA+cyRs6FrGpHtWdo02NaMD5wg4pQuA/cc8/I3IhSeCzlSxzcz3qcMKzRSgZz/7owAsMG+dGzsTLK4h0PhqInxeYQpW9gGZPEaohrypNACT8ZbA5mhNAvUEP2EWPbrleU8hrmqg=,iv:kzZ5qftl+exYRl9E/RQh1rvvuhOmeiosH3iEBoV1G1Q=,tag:yMq1Ck6RFRHyx0eF2gHZKQ==,type:str]
    pgp:
        - created_at: "2026-06-06T12:15:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAoASkNBcJGGD+uE719PF9LaiPisPCaZeq7AtVNguRDn3K
            Qza1EmBxqonAVzi/egyLGK+sriAoDvlO2X3liIwoqnKmgewEenxCXuAdex3fRVoA
            q8dCN9KJDtSpmBVTbN4cpG78IDd4lqQuUgDx6Yym34jWogYx7+7ur66441CmqTPm
            ZPRxufjJVroEOVmdZcZ1nlNtPd/bleUiQlKoCfeUl7C2JOhkYVqEzGzmgL75F5Ib
            5V3aZ/zAl/F0pFHMgwBFMyudYZ1hr7VS9tDwtoR5dt8924d9ATzsbKUFqZ7Mx+1F
            lfjmyX5cTjFFS8Zwx3vnCPHX4a4HU9+Zrama6nQ0668xQYAkr1/X7mRGz4o47mQ0
            jGlYyww0QuIBRLgr24gU1fiZz+GETrHqTqpd7PYK8FVxm8YkvRhrI4vYchfy+rPC
            P4UN9RecPB5q54uRj/CJxgmciHjJjr8vrnycpaNcX24iaxWCQ5QrbXb5onzTGDUa
            DOdvjok3Rsx45zvyMyOyptn8x3fFtoEgoozX2dBOfNAUNS7WC5hlkw0rF0MpxV9M
            9SJgChRQKmIfanW0WKo3FoblaSDEMjbp1NTgMdhL8uasJ9mHGqZppaghm3hNCy+T
            Yz8uEBD/mbAR11dq7TeAVnioGYiyXYSGWs6rqPFGpJHOiTv9ReJlpCJr3JoeSD3U
            aAEJAhDsAG2HuB6PRKQkdwkac/acH3ypSCU0+g981hA7p12s+qgpQ16+tdORvQ3f
            jqDNH3BropTNwVGOLtPWvZCS7Ld7AH6EWVv2wNiKx2ZpWKJgivZZea4+DXL20C43
            OwtfSb/yrLjv
            =l+Je
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
