---
apiVersion: cloudflare-operator.io/v1
kind: DNSRecord
metadata:
  name: ${BASE_DOMAIN/./-}
  namespace: cloudflare-operator
spec:
  name: ${BASE_DOMAIN}
  type: A
  ipRef:
    name: external-ip
  proxied: true
  ttl: 1
  interval: 5m
