apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:4dn2sOlAg4mNds2u0vD1T/aekkYGTKZ34kyoEQWqBDAHdUvRy44RjLpt34FP2cva8lOtzKXieKi31J+MDnuf5hEmCsbwmHUO4rsRHeCmaaHa668=,iv:CeDhQ7p+sipQZsXAYDBtUlHbthPowbu5sJmN2wS8KtE=,tag:bK72deA5v9PHKc2wb5i0EQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-05-22T11:17:01Z"
    mac: ENC[AES256_GCM,data:82gUnKfInTpfx9zjh18PwPSA8+5bmPr2y7Vph5bdMVUr9KTltWcezWissfsf5Zp17j3g9xJ7AE2jvcrfdjqogRCl7Ni+RnatWR+fCng5ZAxNhtCT/l6h1Cr9iAcZVvWajP79b59a6bEdUQh3mZBlqnZx0ZRY+eswAWky4UbkN5I=,iv:78ouYN53wnaCbMoZUz4ofNXJVi8DsNOMOKr4/ACL40I=,tag:GqPwxXZFtA8nmWH+e55P5g==,type:str]
    pgp:
        - created_at: "2026-05-22T11:17:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+Mp6WUMbbKDmbyTL9BwTzA7bJpFS6Ftp/AAOOH4hQuwZ8
            UXKQoTPRLoKuvbuxhqWSYFEM7iO0mClG/gUPUUN7haa+alUjtXFef9/qO7PubRBk
            3to3X+lK0sdgjIVwpKwxMebQk/ZPCfwj/eaCqe/OKdn4PPnQP51q+owJUtY/pUCz
            PrvXQq0GQTU4vPjPFRXbcldssdXIQ06GmhKYp7+xW3DG2fvP63fxxIGPBQyVrZUL
            ZW7OitDOt+BsRrZcgTtmQ34kClyq43pIG/IrKy4B4hDbvlyNmaZrJdRqd1Dbnfqj
            vjxQtgKP+ZflJOBJMCLt83Jetl5Uww4RddJYcHs5w8ecfmHOJsvPfoA1Yt1E5dMZ
            1Irz2fLHvY8wPY4yDtNwn13QPfycTAk9v44jXazfl/EPnwJLkogJxxeI5IomFW9F
            vrUZ8iTuf30HK1YYkZsTObg/DReZZ1Qou9WApE20BcthMU3hN/zFxWGrmOtkUwqm
            o1dAmtXoUXNh/yB9a8wvtujCTu5CP3ArQ5eB7wi2Jic4WBaZCsvA3NmhfmmFOH1J
            JRX5j0aOOxbrPZ1/29mtISKtKEsFXONTEPTegyZtT+VFBWVRH+jGvGJ7cL5sU5xI
            tGdqa09TX83A1JDZyiFN3Stq6NnQdZ7cOCGqaOjBLSoZ3AWB1kLW3kqxmxlosF/U
            ZgEJAhCl+8CNsRi9+PEe8UbopwvaPV1lFqZf+YjkjWFN9cu32tLV4G7HsCoovK5t
            i+ckbEX/L7ejTJinn9bLq1cfovPYOoW3nbnYMcqh8dadDS5fdu1VMe7GMc7tW6yT
            fjQ5/PZYFg==
            =3M8L
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:9bso3Z+/q6+UbNruZFnZsg==,iv:/AO5BextxA3HJUjybcQu+NwU2MVkuQcIBN6ckZFQ5A8=,tag:qoG+E19+Zen3OpkCkh1Dqg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-05-22T11:17:01Z"
    mac: ENC[AES256_GCM,data:82gUnKfInTpfx9zjh18PwPSA8+5bmPr2y7Vph5bdMVUr9KTltWcezWissfsf5Zp17j3g9xJ7AE2jvcrfdjqogRCl7Ni+RnatWR+fCng5ZAxNhtCT/l6h1Cr9iAcZVvWajP79b59a6bEdUQh3mZBlqnZx0ZRY+eswAWky4UbkN5I=,iv:78ouYN53wnaCbMoZUz4ofNXJVi8DsNOMOKr4/ACL40I=,tag:GqPwxXZFtA8nmWH+e55P5g==,type:str]
    pgp:
        - created_at: "2026-05-22T11:17:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+Mp6WUMbbKDmbyTL9BwTzA7bJpFS6Ftp/AAOOH4hQuwZ8
            UXKQoTPRLoKuvbuxhqWSYFEM7iO0mClG/gUPUUN7haa+alUjtXFef9/qO7PubRBk
            3to3X+lK0sdgjIVwpKwxMebQk/ZPCfwj/eaCqe/OKdn4PPnQP51q+owJUtY/pUCz
            PrvXQq0GQTU4vPjPFRXbcldssdXIQ06GmhKYp7+xW3DG2fvP63fxxIGPBQyVrZUL
            ZW7OitDOt+BsRrZcgTtmQ34kClyq43pIG/IrKy4B4hDbvlyNmaZrJdRqd1Dbnfqj
            vjxQtgKP+ZflJOBJMCLt83Jetl5Uww4RddJYcHs5w8ecfmHOJsvPfoA1Yt1E5dMZ
            1Irz2fLHvY8wPY4yDtNwn13QPfycTAk9v44jXazfl/EPnwJLkogJxxeI5IomFW9F
            vrUZ8iTuf30HK1YYkZsTObg/DReZZ1Qou9WApE20BcthMU3hN/zFxWGrmOtkUwqm
            o1dAmtXoUXNh/yB9a8wvtujCTu5CP3ArQ5eB7wi2Jic4WBaZCsvA3NmhfmmFOH1J
            JRX5j0aOOxbrPZ1/29mtISKtKEsFXONTEPTegyZtT+VFBWVRH+jGvGJ7cL5sU5xI
            tGdqa09TX83A1JDZyiFN3Stq6NnQdZ7cOCGqaOjBLSoZ3AWB1kLW3kqxmxlosF/U
            ZgEJAhCl+8CNsRi9+PEe8UbopwvaPV1lFqZf+YjkjWFN9cu32tLV4G7HsCoovK5t
            i+ckbEX/L7ejTJinn9bLq1cfovPYOoW3nbnYMcqh8dadDS5fdu1VMe7GMc7tW6yT
            fjQ5/PZYFg==
            =3M8L
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:Ghyf6361oIw/avCDu79fBcnFmq7fVt3gE81NLN55z4QII1N12ZLCAYPZTCf+VV7JM1z9vT7chZ1wQgjdirE3pblxhDsAOayP9qQ2Z7MhqE7YKl4crQ4PVvDU49mcmOlCL6PC2a6cSClTXscgQRjSrz0GytFZY6OVj8eysj6xlrOePjyFm3M3mcv4asV4z/qwTI2X9uczmh/17s4daU8CAQDawge5JnNNcF7pMIV73idrub7gbQPGubsgZlwMHOqRYeDXwZFJxu0elCXeo3si2GS7sPOGByTJP4ArwmIBjNI2vqMIXjtcDn/RI2cjb/U3ql11XFhUvnxMlSo01+Td8TcaRxeOqz7kkT2slmRR+hepQSwQxXvQO+YyduqSmXI6rILBS5r/T8awVlMYEYQ1G9yqRnUOKQ2VlhOuzf/2xkI6xihAOlh+YRVyPrkhVhXVyRThwp7Jeni+9fufvJuH2JnOF1n4zhKOzaDIzC32qPEzMVZFMjhIgPwE7brEdbcs1c13Id/6y87EiDv4GGVEkcyz7DMz8SV+U9THyTgFK4SDPDtdJkgoiCvttzoQW02wby7mi+PTxkXDkSdeEA38/eaCQeYaSNMf+4k=,iv:YFUeHCYKG8FgD2WC7JR6m/Q02ioyWuC/KSfg+Y6gZl8=,tag:q4osdpchtzEDh8buif/VhA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-05-22T11:17:01Z"
    mac: ENC[AES256_GCM,data:82gUnKfInTpfx9zjh18PwPSA8+5bmPr2y7Vph5bdMVUr9KTltWcezWissfsf5Zp17j3g9xJ7AE2jvcrfdjqogRCl7Ni+RnatWR+fCng5ZAxNhtCT/l6h1Cr9iAcZVvWajP79b59a6bEdUQh3mZBlqnZx0ZRY+eswAWky4UbkN5I=,iv:78ouYN53wnaCbMoZUz4ofNXJVi8DsNOMOKr4/ACL40I=,tag:GqPwxXZFtA8nmWH+e55P5g==,type:str]
    pgp:
        - created_at: "2026-05-22T11:17:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+Mp6WUMbbKDmbyTL9BwTzA7bJpFS6Ftp/AAOOH4hQuwZ8
            UXKQoTPRLoKuvbuxhqWSYFEM7iO0mClG/gUPUUN7haa+alUjtXFef9/qO7PubRBk
            3to3X+lK0sdgjIVwpKwxMebQk/ZPCfwj/eaCqe/OKdn4PPnQP51q+owJUtY/pUCz
            PrvXQq0GQTU4vPjPFRXbcldssdXIQ06GmhKYp7+xW3DG2fvP63fxxIGPBQyVrZUL
            ZW7OitDOt+BsRrZcgTtmQ34kClyq43pIG/IrKy4B4hDbvlyNmaZrJdRqd1Dbnfqj
            vjxQtgKP+ZflJOBJMCLt83Jetl5Uww4RddJYcHs5w8ecfmHOJsvPfoA1Yt1E5dMZ
            1Irz2fLHvY8wPY4yDtNwn13QPfycTAk9v44jXazfl/EPnwJLkogJxxeI5IomFW9F
            vrUZ8iTuf30HK1YYkZsTObg/DReZZ1Qou9WApE20BcthMU3hN/zFxWGrmOtkUwqm
            o1dAmtXoUXNh/yB9a8wvtujCTu5CP3ArQ5eB7wi2Jic4WBaZCsvA3NmhfmmFOH1J
            JRX5j0aOOxbrPZ1/29mtISKtKEsFXONTEPTegyZtT+VFBWVRH+jGvGJ7cL5sU5xI
            tGdqa09TX83A1JDZyiFN3Stq6NnQdZ7cOCGqaOjBLSoZ3AWB1kLW3kqxmxlosF/U
            ZgEJAhCl+8CNsRi9+PEe8UbopwvaPV1lFqZf+YjkjWFN9cu32tLV4G7HsCoovK5t
            i+ckbEX/L7ejTJinn9bLq1cfovPYOoW3nbnYMcqh8dadDS5fdu1VMe7GMc7tW6yT
            fjQ5/PZYFg==
            =3M8L
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage-s3cmd
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:uK+M6ENhoZVuG36Zh4fxVT9XRyp7tU9nvn2Isj8ryZ8cALdGb4zw+DgMhdpkK1KSGdPOEwJQWoewR10jP/bnEoNA+jZcAdI3udoreimVKUX1KbznlD6yX+JmVOSRilFZS2X59CfAENWsyMSmekO/QcN89BFkMHQXAnmlj4QlWGA2nh7zfEyfg2o8qz2TOVPzgMUTtKbFnEBnr7TCLagKlz8O8RIaBYVn51lRVoV7Tk2it/1UQ6zckItRlHByPe3DO/1Cx3MPbW3T7YzNcLshnN/ZszovB1rNdZExwSm8jxW60/GIQmmfY3Khu7Jc0u+sJuo989xHoEgLl84dKKftnVtfDqo=,iv:cVTtaE0vVDmlXK6XNMlhN5PgyZFi27Day2q9StQSeeg=,tag:rcg6AqtZnZmlstPePReZ9g==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-05-22T11:17:01Z"
    mac: ENC[AES256_GCM,data:82gUnKfInTpfx9zjh18PwPSA8+5bmPr2y7Vph5bdMVUr9KTltWcezWissfsf5Zp17j3g9xJ7AE2jvcrfdjqogRCl7Ni+RnatWR+fCng5ZAxNhtCT/l6h1Cr9iAcZVvWajP79b59a6bEdUQh3mZBlqnZx0ZRY+eswAWky4UbkN5I=,iv:78ouYN53wnaCbMoZUz4ofNXJVi8DsNOMOKr4/ACL40I=,tag:GqPwxXZFtA8nmWH+e55P5g==,type:str]
    pgp:
        - created_at: "2026-05-22T11:17:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+Mp6WUMbbKDmbyTL9BwTzA7bJpFS6Ftp/AAOOH4hQuwZ8
            UXKQoTPRLoKuvbuxhqWSYFEM7iO0mClG/gUPUUN7haa+alUjtXFef9/qO7PubRBk
            3to3X+lK0sdgjIVwpKwxMebQk/ZPCfwj/eaCqe/OKdn4PPnQP51q+owJUtY/pUCz
            PrvXQq0GQTU4vPjPFRXbcldssdXIQ06GmhKYp7+xW3DG2fvP63fxxIGPBQyVrZUL
            ZW7OitDOt+BsRrZcgTtmQ34kClyq43pIG/IrKy4B4hDbvlyNmaZrJdRqd1Dbnfqj
            vjxQtgKP+ZflJOBJMCLt83Jetl5Uww4RddJYcHs5w8ecfmHOJsvPfoA1Yt1E5dMZ
            1Irz2fLHvY8wPY4yDtNwn13QPfycTAk9v44jXazfl/EPnwJLkogJxxeI5IomFW9F
            vrUZ8iTuf30HK1YYkZsTObg/DReZZ1Qou9WApE20BcthMU3hN/zFxWGrmOtkUwqm
            o1dAmtXoUXNh/yB9a8wvtujCTu5CP3ArQ5eB7wi2Jic4WBaZCsvA3NmhfmmFOH1J
            JRX5j0aOOxbrPZ1/29mtISKtKEsFXONTEPTegyZtT+VFBWVRH+jGvGJ7cL5sU5xI
            tGdqa09TX83A1JDZyiFN3Stq6NnQdZ7cOCGqaOjBLSoZ3AWB1kLW3kqxmxlosF/U
            ZgEJAhCl+8CNsRi9+PEe8UbopwvaPV1lFqZf+YjkjWFN9cu32tLV4G7HsCoovK5t
            i+ckbEX/L7ejTJinn9bLq1cfovPYOoW3nbnYMcqh8dadDS5fdu1VMe7GMc7tW6yT
            fjQ5/PZYFg==
            =3M8L
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:PzoxpE2/kPQKTq3LjXFc07QRs5LEZ4s1n9Tconjq6RHRqUrscSObLkH55FSR9ZzxLEPiVvY0DKxlTPUxkkFhJU9hFtW3xLpeCF1L0iufpNvPhhg4jsieukfawJoGyxlRvkjQmes9bJ0alRP/GofZMQ7JBOKYoYpUP0RC6KJ+6/G0Jkw0qQOU/sm2WzqZxRybUZTc7Y4/HkjLEV7/xRPy7/3Tch5QMnQWk3zhsJihtbvxaaUm0J3d6N2ypDK3v9OojhRwxGS0OIU4CjcSHIPst/SsdpXs6afPxg3CSH9WAwyAGJCfKMB2VeEBzJb83PNMr3U+,iv:mw9/kcNdcGKD8lQtmaEI+BSW+Ut+JhLFmSNBlAf2xs0=,tag:I24mfdFts3Ocpx2JxPSVdg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-05-22T11:17:01Z"
    mac: ENC[AES256_GCM,data:82gUnKfInTpfx9zjh18PwPSA8+5bmPr2y7Vph5bdMVUr9KTltWcezWissfsf5Zp17j3g9xJ7AE2jvcrfdjqogRCl7Ni+RnatWR+fCng5ZAxNhtCT/l6h1Cr9iAcZVvWajP79b59a6bEdUQh3mZBlqnZx0ZRY+eswAWky4UbkN5I=,iv:78ouYN53wnaCbMoZUz4ofNXJVi8DsNOMOKr4/ACL40I=,tag:GqPwxXZFtA8nmWH+e55P5g==,type:str]
    pgp:
        - created_at: "2026-05-22T11:17:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+Mp6WUMbbKDmbyTL9BwTzA7bJpFS6Ftp/AAOOH4hQuwZ8
            UXKQoTPRLoKuvbuxhqWSYFEM7iO0mClG/gUPUUN7haa+alUjtXFef9/qO7PubRBk
            3to3X+lK0sdgjIVwpKwxMebQk/ZPCfwj/eaCqe/OKdn4PPnQP51q+owJUtY/pUCz
            PrvXQq0GQTU4vPjPFRXbcldssdXIQ06GmhKYp7+xW3DG2fvP63fxxIGPBQyVrZUL
            ZW7OitDOt+BsRrZcgTtmQ34kClyq43pIG/IrKy4B4hDbvlyNmaZrJdRqd1Dbnfqj
            vjxQtgKP+ZflJOBJMCLt83Jetl5Uww4RddJYcHs5w8ecfmHOJsvPfoA1Yt1E5dMZ
            1Irz2fLHvY8wPY4yDtNwn13QPfycTAk9v44jXazfl/EPnwJLkogJxxeI5IomFW9F
            vrUZ8iTuf30HK1YYkZsTObg/DReZZ1Qou9WApE20BcthMU3hN/zFxWGrmOtkUwqm
            o1dAmtXoUXNh/yB9a8wvtujCTu5CP3ArQ5eB7wi2Jic4WBaZCsvA3NmhfmmFOH1J
            JRX5j0aOOxbrPZ1/29mtISKtKEsFXONTEPTegyZtT+VFBWVRH+jGvGJ7cL5sU5xI
            tGdqa09TX83A1JDZyiFN3Stq6NnQdZ7cOCGqaOjBLSoZ3AWB1kLW3kqxmxlosF/U
            ZgEJAhCl+8CNsRi9+PEe8UbopwvaPV1lFqZf+YjkjWFN9cu32tLV4G7HsCoovK5t
            i+ckbEX/L7ejTJinn9bLq1cfovPYOoW3nbnYMcqh8dadDS5fdu1VMe7GMc7tW6yT
            fjQ5/PZYFg==
            =3M8L
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:vRaeA2FXCKFQFSgBhS2zdAy4eM2ARirkvUEqOG2YOdRMO+tork4GbsDFFprqtKxhNS8ekuekiaf6i1LwC2t9H4cV7n3L0wq3UqLn9NT5Z3ZkYRJYqK+yIae17ZzewTuSYlHWwVLIRk1TyPkoHGLY1uaRO5VrF2Ton61io13opK8fV2IizIc8WMId4AobVsPOUloZnI++34bZZBRtAOc5VXDC1I1krZfedpESfDSQ0xEAoKffV/zTbdy4oo5WHWytfv9xe4gNdw6+mRrkmaQhkPYjiMeQh84UGfgLn4llAaDIsuqnnJixwq99MgrAxXuJaGZXKG2rZvqo2RJIq2+M+O1/pmYA4w==,iv:nHPUiKDdNKP6Ov4U5IVapo6QCX7KtS2D2gv+GY/wFpY=,tag:0OWYdagLeg9GsTXYFkyZbw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-05-22T11:17:01Z"
    mac: ENC[AES256_GCM,data:82gUnKfInTpfx9zjh18PwPSA8+5bmPr2y7Vph5bdMVUr9KTltWcezWissfsf5Zp17j3g9xJ7AE2jvcrfdjqogRCl7Ni+RnatWR+fCng5ZAxNhtCT/l6h1Cr9iAcZVvWajP79b59a6bEdUQh3mZBlqnZx0ZRY+eswAWky4UbkN5I=,iv:78ouYN53wnaCbMoZUz4ofNXJVi8DsNOMOKr4/ACL40I=,tag:GqPwxXZFtA8nmWH+e55P5g==,type:str]
    pgp:
        - created_at: "2026-05-22T11:17:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+Mp6WUMbbKDmbyTL9BwTzA7bJpFS6Ftp/AAOOH4hQuwZ8
            UXKQoTPRLoKuvbuxhqWSYFEM7iO0mClG/gUPUUN7haa+alUjtXFef9/qO7PubRBk
            3to3X+lK0sdgjIVwpKwxMebQk/ZPCfwj/eaCqe/OKdn4PPnQP51q+owJUtY/pUCz
            PrvXQq0GQTU4vPjPFRXbcldssdXIQ06GmhKYp7+xW3DG2fvP63fxxIGPBQyVrZUL
            ZW7OitDOt+BsRrZcgTtmQ34kClyq43pIG/IrKy4B4hDbvlyNmaZrJdRqd1Dbnfqj
            vjxQtgKP+ZflJOBJMCLt83Jetl5Uww4RddJYcHs5w8ecfmHOJsvPfoA1Yt1E5dMZ
            1Irz2fLHvY8wPY4yDtNwn13QPfycTAk9v44jXazfl/EPnwJLkogJxxeI5IomFW9F
            vrUZ8iTuf30HK1YYkZsTObg/DReZZ1Qou9WApE20BcthMU3hN/zFxWGrmOtkUwqm
            o1dAmtXoUXNh/yB9a8wvtujCTu5CP3ArQ5eB7wi2Jic4WBaZCsvA3NmhfmmFOH1J
            JRX5j0aOOxbrPZ1/29mtISKtKEsFXONTEPTegyZtT+VFBWVRH+jGvGJ7cL5sU5xI
            tGdqa09TX83A1JDZyiFN3Stq6NnQdZ7cOCGqaOjBLSoZ3AWB1kLW3kqxmxlosF/U
            ZgEJAhCl+8CNsRi9+PEe8UbopwvaPV1lFqZf+YjkjWFN9cu32tLV4G7HsCoovK5t
            i+ckbEX/L7ejTJinn9bLq1cfovPYOoW3nbnYMcqh8dadDS5fdu1VMe7GMc7tW6yT
            fjQ5/PZYFg==
            =3M8L
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
