apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:OG7JHTQXu6aN4zJXdMhyJYY3nbFTOkyNj6l3dsCiM5e7Kt6zesJHDgkj/f+jJetQ5ot6AFudghOVfnixvy8TZrNx9YZXVinmx3IN4HmmvaaA7pc=,iv:9i+UhVoVpCKAA2pvA78xr1pz3+83XiX2y78p8diBEgY=,tag:bPBbkZBOnkaxR4ZQu2Xsww==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:35:12Z"
    mac: ENC[AES256_GCM,data:AzsfiUP0xpPhuqBIgYxzhazNtRZ6ZAcS+MQYVMHAdC+AnuKk6Kgr0n9Nncs6W64OE1em41L07YvfbbLfKLm05UMI5+l61AMXZH3cy5Vp7ILR9Xbaxt2mykKqfShjqevkYTqemX3bFMbBQtlOr2WoJRGNcqC66LFxfXzUu0GDjd8=,iv:97IbYin64iGBugb+Z9mQYvxlbgrPZeANmqgsJItWvXs=,tag:NJ6rHL8DV0qGUJUDnOefLg==,type:str]
    pgp:
        - created_at: "2026-06-06T12:35:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArOeI0xt0BUjVsVNh724lYHYw6rJkz4tsTXlpqrw+65TA
            1Yqqx2C7liRrhqzLlvowxgoXTKpbRqrYjns0seVPzKvLCp+YeLePLXQTDRlDQcg4
            z7pUHtfpL84zrU7XPN/cccOyOeZdhNtrCWTuuy97e8RmLsqyrjujZm3kvlLwT/hY
            rSHFndPcrrs4nZ/cT48qgmsw0BMg5Gw4iSMo3W4/PGYX1VWeY3CN4+MtueGl90II
            M1nMZuuaH66NZfO+5YHt91JYZxLjIG1ruwz+K67zfuznimUvXU37Bfu53m7xnp67
            az57Iwssmryi4O6jL2t351+wVNP0r7UmCBAkMO/R+G42pdqwrRGS7LBgiMcFcWEv
            FYSyCZGeFi1IHNilnXgln2JC/FV2FYIt2V2q0CA4wk2D9RGzHO1ZoEDms92s9DNc
            7QR9K4AdBkY3B0RearSATVcjPxleVEMrPprQq5PY3H2HnOmCo2yhu6GLIa6FOVVg
            bx0LNr8+xDLYmTnQsL5vwI+u3eEMlP625EcGpVCaP5fzluoh9CvsM/JHk07DrKK3
            zS/LDKWrXTOAMOauwLD30+EKpIYXDGv2HHGEeaVq9EVYxFjuNuN/GbRb8hWiQie6
            C/leRjgZFpyONThtaiLiDzMOPvwlsr9ZuoKLjZZLfnGbynzG6t8YO8LTBwlZ3i7U
            aAEJAhAMCthGALXaKHHbQVPzKu0tO8RnVij2iDlfGpLpSbeIfJws/bToVgtt0zjJ
            CACje++0Ho3qUZ1NTlVHXon+IBj0r1qfnvIGkZuXvK0X0PdhhCLT0kETsQIpRXco
            4/pHSiUpQ7DU
            =qj5H
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:p9146bkLPnn/j8dHkZMRKg==,iv:TFfljVtg5IavdJH5LYojJ8xYOXitoAj5HMOQhdoVuXE=,tag:yipZalmA0cPmwHLeRXaY6g==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:35:12Z"
    mac: ENC[AES256_GCM,data:AzsfiUP0xpPhuqBIgYxzhazNtRZ6ZAcS+MQYVMHAdC+AnuKk6Kgr0n9Nncs6W64OE1em41L07YvfbbLfKLm05UMI5+l61AMXZH3cy5Vp7ILR9Xbaxt2mykKqfShjqevkYTqemX3bFMbBQtlOr2WoJRGNcqC66LFxfXzUu0GDjd8=,iv:97IbYin64iGBugb+Z9mQYvxlbgrPZeANmqgsJItWvXs=,tag:NJ6rHL8DV0qGUJUDnOefLg==,type:str]
    pgp:
        - created_at: "2026-06-06T12:35:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArOeI0xt0BUjVsVNh724lYHYw6rJkz4tsTXlpqrw+65TA
            1Yqqx2C7liRrhqzLlvowxgoXTKpbRqrYjns0seVPzKvLCp+YeLePLXQTDRlDQcg4
            z7pUHtfpL84zrU7XPN/cccOyOeZdhNtrCWTuuy97e8RmLsqyrjujZm3kvlLwT/hY
            rSHFndPcrrs4nZ/cT48qgmsw0BMg5Gw4iSMo3W4/PGYX1VWeY3CN4+MtueGl90II
            M1nMZuuaH66NZfO+5YHt91JYZxLjIG1ruwz+K67zfuznimUvXU37Bfu53m7xnp67
            az57Iwssmryi4O6jL2t351+wVNP0r7UmCBAkMO/R+G42pdqwrRGS7LBgiMcFcWEv
            FYSyCZGeFi1IHNilnXgln2JC/FV2FYIt2V2q0CA4wk2D9RGzHO1ZoEDms92s9DNc
            7QR9K4AdBkY3B0RearSATVcjPxleVEMrPprQq5PY3H2HnOmCo2yhu6GLIa6FOVVg
            bx0LNr8+xDLYmTnQsL5vwI+u3eEMlP625EcGpVCaP5fzluoh9CvsM/JHk07DrKK3
            zS/LDKWrXTOAMOauwLD30+EKpIYXDGv2HHGEeaVq9EVYxFjuNuN/GbRb8hWiQie6
            C/leRjgZFpyONThtaiLiDzMOPvwlsr9ZuoKLjZZLfnGbynzG6t8YO8LTBwlZ3i7U
            aAEJAhAMCthGALXaKHHbQVPzKu0tO8RnVij2iDlfGpLpSbeIfJws/bToVgtt0zjJ
            CACje++0Ho3qUZ1NTlVHXon+IBj0r1qfnvIGkZuXvK0X0PdhhCLT0kETsQIpRXco
            4/pHSiUpQ7DU
            =qj5H
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:NMy3phbfybG1LtsBK94ZD5Izs1B+s44Ag6ULpDXn5Hi6OJg+wJTb5iDDhIQ71KZNr5SHLe/QukhyWiCgsjfa1MGD7d2xvVJKQviliNh9LPVngXRG5VHXvrNCAilvrgE/B1065hRuIs2xE8GA4jziBLD97ms7HsNV/NtQCowDKHpkKq+sxByIMvGxcTEAKiRhaS5wwo1Pg9HoaNhzAYoZfXkepshtCJvJ/jLfpkqevPyIXzMoq6uqr9+FW+OMiLAUNikrBbwh9DLTl6NmgXiL0CyMtMcLdO3UQqF+LnGrQmABOr+f8jWxVI2pOEMtJbPgPDlXBTQCF6Xk0p/1C8UexuDa9jsZZZG26pX1YxIjijinkzknk9ID3z78IWnFyGAXqjJ3TchFvxplZHDFg7PPbRifThARjq0vE4D/errsuNGLp0c0NP+6tWFIsPDvRnuo2QIwEBeuuYKBGqI+TsKIs8G0OuN0gM3ujobGfjLFmiIPDWk/Q8tYGMximXFSELV2Nx9jJfU4wYLnpNPE0D2RQjmE/cX1txy7hQnx74vF+oSZc1I/9O5vPKO8FESTiW6e/49Dy5qtCzdGYWQ1PSQdxMy5l55GhKXAQgs=,iv:Zq//gotsHRHka3AboyJUbotDouyl78K7ODkQcPI56sg=,tag:/rChWbJSiZyZkJffbrffcw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:35:12Z"
    mac: ENC[AES256_GCM,data:AzsfiUP0xpPhuqBIgYxzhazNtRZ6ZAcS+MQYVMHAdC+AnuKk6Kgr0n9Nncs6W64OE1em41L07YvfbbLfKLm05UMI5+l61AMXZH3cy5Vp7ILR9Xbaxt2mykKqfShjqevkYTqemX3bFMbBQtlOr2WoJRGNcqC66LFxfXzUu0GDjd8=,iv:97IbYin64iGBugb+Z9mQYvxlbgrPZeANmqgsJItWvXs=,tag:NJ6rHL8DV0qGUJUDnOefLg==,type:str]
    pgp:
        - created_at: "2026-06-06T12:35:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArOeI0xt0BUjVsVNh724lYHYw6rJkz4tsTXlpqrw+65TA
            1Yqqx2C7liRrhqzLlvowxgoXTKpbRqrYjns0seVPzKvLCp+YeLePLXQTDRlDQcg4
            z7pUHtfpL84zrU7XPN/cccOyOeZdhNtrCWTuuy97e8RmLsqyrjujZm3kvlLwT/hY
            rSHFndPcrrs4nZ/cT48qgmsw0BMg5Gw4iSMo3W4/PGYX1VWeY3CN4+MtueGl90II
            M1nMZuuaH66NZfO+5YHt91JYZxLjIG1ruwz+K67zfuznimUvXU37Bfu53m7xnp67
            az57Iwssmryi4O6jL2t351+wVNP0r7UmCBAkMO/R+G42pdqwrRGS7LBgiMcFcWEv
            FYSyCZGeFi1IHNilnXgln2JC/FV2FYIt2V2q0CA4wk2D9RGzHO1ZoEDms92s9DNc
            7QR9K4AdBkY3B0RearSATVcjPxleVEMrPprQq5PY3H2HnOmCo2yhu6GLIa6FOVVg
            bx0LNr8+xDLYmTnQsL5vwI+u3eEMlP625EcGpVCaP5fzluoh9CvsM/JHk07DrKK3
            zS/LDKWrXTOAMOauwLD30+EKpIYXDGv2HHGEeaVq9EVYxFjuNuN/GbRb8hWiQie6
            C/leRjgZFpyONThtaiLiDzMOPvwlsr9ZuoKLjZZLfnGbynzG6t8YO8LTBwlZ3i7U
            aAEJAhAMCthGALXaKHHbQVPzKu0tO8RnVij2iDlfGpLpSbeIfJws/bToVgtt0zjJ
            CACje++0Ho3qUZ1NTlVHXon+IBj0r1qfnvIGkZuXvK0X0PdhhCLT0kETsQIpRXco
            4/pHSiUpQ7DU
            =qj5H
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage-s3cmd
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:9w2ymZEo6QhkRbPZgx6+APZQpUl/C/j1Vjug8hp5GWokR55/+le3W4C5lxMkzbsyoB/ns+RZiMFzLqqoIRLM6q+5a8r2DA1rtsfNmN+fc1ttzpPSMbV6yuRBF+p182F3fNwJQbtd66HtFEbc/dYZz1m9oAvThDWZ221GcWbYbVWp/ygUt1ICXxS1qmivmPS2oRiWcZzkj8yfVONGER5HC3AorlpHvrYEP7e0kz5QBBaCMmasLQuxXPXJz5TUp0rlCC6o7kS4OwkvZppaWaWvC06gYscCksFclII9uJ0m5EoCIpg8a4lQHzKaQfvcyo5QShrmcnhf6hwkEAyxA2kNItM4tTk=,iv:iZJm3vkIIln0CU7Pq3DhkzpWxi1l+6Z69OBdUpArlNg=,tag:d8Pt1acsM1EOWHDE3wONrQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:35:12Z"
    mac: ENC[AES256_GCM,data:AzsfiUP0xpPhuqBIgYxzhazNtRZ6ZAcS+MQYVMHAdC+AnuKk6Kgr0n9Nncs6W64OE1em41L07YvfbbLfKLm05UMI5+l61AMXZH3cy5Vp7ILR9Xbaxt2mykKqfShjqevkYTqemX3bFMbBQtlOr2WoJRGNcqC66LFxfXzUu0GDjd8=,iv:97IbYin64iGBugb+Z9mQYvxlbgrPZeANmqgsJItWvXs=,tag:NJ6rHL8DV0qGUJUDnOefLg==,type:str]
    pgp:
        - created_at: "2026-06-06T12:35:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArOeI0xt0BUjVsVNh724lYHYw6rJkz4tsTXlpqrw+65TA
            1Yqqx2C7liRrhqzLlvowxgoXTKpbRqrYjns0seVPzKvLCp+YeLePLXQTDRlDQcg4
            z7pUHtfpL84zrU7XPN/cccOyOeZdhNtrCWTuuy97e8RmLsqyrjujZm3kvlLwT/hY
            rSHFndPcrrs4nZ/cT48qgmsw0BMg5Gw4iSMo3W4/PGYX1VWeY3CN4+MtueGl90II
            M1nMZuuaH66NZfO+5YHt91JYZxLjIG1ruwz+K67zfuznimUvXU37Bfu53m7xnp67
            az57Iwssmryi4O6jL2t351+wVNP0r7UmCBAkMO/R+G42pdqwrRGS7LBgiMcFcWEv
            FYSyCZGeFi1IHNilnXgln2JC/FV2FYIt2V2q0CA4wk2D9RGzHO1ZoEDms92s9DNc
            7QR9K4AdBkY3B0RearSATVcjPxleVEMrPprQq5PY3H2HnOmCo2yhu6GLIa6FOVVg
            bx0LNr8+xDLYmTnQsL5vwI+u3eEMlP625EcGpVCaP5fzluoh9CvsM/JHk07DrKK3
            zS/LDKWrXTOAMOauwLD30+EKpIYXDGv2HHGEeaVq9EVYxFjuNuN/GbRb8hWiQie6
            C/leRjgZFpyONThtaiLiDzMOPvwlsr9ZuoKLjZZLfnGbynzG6t8YO8LTBwlZ3i7U
            aAEJAhAMCthGALXaKHHbQVPzKu0tO8RnVij2iDlfGpLpSbeIfJws/bToVgtt0zjJ
            CACje++0Ho3qUZ1NTlVHXon+IBj0r1qfnvIGkZuXvK0X0PdhhCLT0kETsQIpRXco
            4/pHSiUpQ7DU
            =qj5H
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:4LsDGdbM/G3cVkW0xnG6511RYDSYeb9cqPa1ALGZthtfWiU2oaXtZUUsRqyjxw0RIkD3wlNNMd6KszwDVBr+xWC5P0CavKiLWvFQV4Uzctfu9C9PKh3Plail3WTRadrtO/QKNh7b1K9tvSDeUl9TX8WyxUGAPMG8wkeNW+OX99WrYblyvby4mCrxF1QyJxCnpkCjO94qZTtLTEt231OEbtfGmf6f9kI3jMp663eRdej/zThxK6n96uEBbwduulj5fPfU8N8d+EwYTquK4VB6JuBn1FceK6kZddbTC/CyxV4hKWkmAH2ayqqqZGnPcNNJdsV5,iv:odW5Y41dixZCAO9u63fJwQOcvP5D/DvabgogwK5CuH4=,tag:feibwZGBS5+N8fgp+Kxw4Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:35:12Z"
    mac: ENC[AES256_GCM,data:AzsfiUP0xpPhuqBIgYxzhazNtRZ6ZAcS+MQYVMHAdC+AnuKk6Kgr0n9Nncs6W64OE1em41L07YvfbbLfKLm05UMI5+l61AMXZH3cy5Vp7ILR9Xbaxt2mykKqfShjqevkYTqemX3bFMbBQtlOr2WoJRGNcqC66LFxfXzUu0GDjd8=,iv:97IbYin64iGBugb+Z9mQYvxlbgrPZeANmqgsJItWvXs=,tag:NJ6rHL8DV0qGUJUDnOefLg==,type:str]
    pgp:
        - created_at: "2026-06-06T12:35:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArOeI0xt0BUjVsVNh724lYHYw6rJkz4tsTXlpqrw+65TA
            1Yqqx2C7liRrhqzLlvowxgoXTKpbRqrYjns0seVPzKvLCp+YeLePLXQTDRlDQcg4
            z7pUHtfpL84zrU7XPN/cccOyOeZdhNtrCWTuuy97e8RmLsqyrjujZm3kvlLwT/hY
            rSHFndPcrrs4nZ/cT48qgmsw0BMg5Gw4iSMo3W4/PGYX1VWeY3CN4+MtueGl90II
            M1nMZuuaH66NZfO+5YHt91JYZxLjIG1ruwz+K67zfuznimUvXU37Bfu53m7xnp67
            az57Iwssmryi4O6jL2t351+wVNP0r7UmCBAkMO/R+G42pdqwrRGS7LBgiMcFcWEv
            FYSyCZGeFi1IHNilnXgln2JC/FV2FYIt2V2q0CA4wk2D9RGzHO1ZoEDms92s9DNc
            7QR9K4AdBkY3B0RearSATVcjPxleVEMrPprQq5PY3H2HnOmCo2yhu6GLIa6FOVVg
            bx0LNr8+xDLYmTnQsL5vwI+u3eEMlP625EcGpVCaP5fzluoh9CvsM/JHk07DrKK3
            zS/LDKWrXTOAMOauwLD30+EKpIYXDGv2HHGEeaVq9EVYxFjuNuN/GbRb8hWiQie6
            C/leRjgZFpyONThtaiLiDzMOPvwlsr9ZuoKLjZZLfnGbynzG6t8YO8LTBwlZ3i7U
            aAEJAhAMCthGALXaKHHbQVPzKu0tO8RnVij2iDlfGpLpSbeIfJws/bToVgtt0zjJ
            CACje++0Ho3qUZ1NTlVHXon+IBj0r1qfnvIGkZuXvK0X0PdhhCLT0kETsQIpRXco
            4/pHSiUpQ7DU
            =qj5H
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:tj7fvgv0uEPvT42MdQcjuAz9JFPLi+3fOO+6B8cS3rou6VGmcUJ8arFGip4FfyZsF9zAcTh5MUIcSjGFkdiorW+Q4S6nBIIKJjhAqIOZdiKp5+nzAKa46La7jA/la2me+UEB5AEWj2ABM3YSEpBmUEFNYijGqKu0TiItNbi2Vtt/z0KYpAPRGxKtU+XqU0Xp4+Ni1mRpqM3sbSml2oV0Tq9IrUHBo3JhsnfLxc1WzTDJ6w81fG5mZNQaQrmjtOiHVEzsMKETWXPcof7y/bF7mOmLLbqAlti0y5z6cgIXWcarM/82b7ZO2Nx5cVgvEe3d4WbhBO0DxPpWRhH9BbNV83n3g/mEtA==,iv:kzHvYSDic0q25gWiXFg7Z2JXdc/UfxXR+bSEAgKWeKg=,tag:LvhIJmhtENLeolzFz5uj1w==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:35:12Z"
    mac: ENC[AES256_GCM,data:AzsfiUP0xpPhuqBIgYxzhazNtRZ6ZAcS+MQYVMHAdC+AnuKk6Kgr0n9Nncs6W64OE1em41L07YvfbbLfKLm05UMI5+l61AMXZH3cy5Vp7ILR9Xbaxt2mykKqfShjqevkYTqemX3bFMbBQtlOr2WoJRGNcqC66LFxfXzUu0GDjd8=,iv:97IbYin64iGBugb+Z9mQYvxlbgrPZeANmqgsJItWvXs=,tag:NJ6rHL8DV0qGUJUDnOefLg==,type:str]
    pgp:
        - created_at: "2026-06-06T12:35:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArOeI0xt0BUjVsVNh724lYHYw6rJkz4tsTXlpqrw+65TA
            1Yqqx2C7liRrhqzLlvowxgoXTKpbRqrYjns0seVPzKvLCp+YeLePLXQTDRlDQcg4
            z7pUHtfpL84zrU7XPN/cccOyOeZdhNtrCWTuuy97e8RmLsqyrjujZm3kvlLwT/hY
            rSHFndPcrrs4nZ/cT48qgmsw0BMg5Gw4iSMo3W4/PGYX1VWeY3CN4+MtueGl90II
            M1nMZuuaH66NZfO+5YHt91JYZxLjIG1ruwz+K67zfuznimUvXU37Bfu53m7xnp67
            az57Iwssmryi4O6jL2t351+wVNP0r7UmCBAkMO/R+G42pdqwrRGS7LBgiMcFcWEv
            FYSyCZGeFi1IHNilnXgln2JC/FV2FYIt2V2q0CA4wk2D9RGzHO1ZoEDms92s9DNc
            7QR9K4AdBkY3B0RearSATVcjPxleVEMrPprQq5PY3H2HnOmCo2yhu6GLIa6FOVVg
            bx0LNr8+xDLYmTnQsL5vwI+u3eEMlP625EcGpVCaP5fzluoh9CvsM/JHk07DrKK3
            zS/LDKWrXTOAMOauwLD30+EKpIYXDGv2HHGEeaVq9EVYxFjuNuN/GbRb8hWiQie6
            C/leRjgZFpyONThtaiLiDzMOPvwlsr9ZuoKLjZZLfnGbynzG6t8YO8LTBwlZ3i7U
            aAEJAhAMCthGALXaKHHbQVPzKu0tO8RnVij2iDlfGpLpSbeIfJws/bToVgtt0zjJ
            CACje++0Ho3qUZ1NTlVHXon+IBj0r1qfnvIGkZuXvK0X0PdhhCLT0kETsQIpRXco
            4/pHSiUpQ7DU
            =qj5H
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
