apiVersion: v1
kind: Secret
metadata:
    name: gitlab-helm-values
    namespace: gitlab
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:NfQxXPCK7/Wf+ZyLnDZ8eRYixO0L1kYHVaOv8AvqLJIWDa/PhPGHVy0AHIUCVUzVTuKd0HdI0Zw21w1TIMU3a3HdKuo+PikviADSL93ePWByZu4=,iv:V4UPIAveDWTH6vrtmphV4OSTtiwQuHgBwLQWv3odFx0=,tag:qefSxBq633lf1tqYnf9xVA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-24T11:31:19Z"
    mac: ENC[AES256_GCM,data:jj97mIXTYTfhBoyHfx2S6d7YSRPHCjnm3L4/m2Mk5UtjwFPqJxa153qTcd787y53oMmr/Q407J9FiHjBhOB1q88XqgE63BNL37NK9Ac3NdMo3/zyoThCQqWR6huMs70OVMyF65ic67TwrskYS4+AmdZA76kucVvAipQYyuVX+a8=,iv:U8jySAaGvnLQNwHlwrjBeeobylR6zHH7OwXsI+eev28=,tag:1D7ylul7Sscl8fLqC66vCw==,type:str]
    pgp:
        - created_at: "2026-06-24T11:31:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAApjOT7XqOI0SmwZe26btW9a+cOnZKSMGadWFYq6XLX67m
            24TsBs+FARnOoSKAJb5uijkb5MARdoxwWN8474ekyui+cy0bR5rLjZEy78f0dmRV
            hCUCTaVE2rcTStwasmHMzlHZbcJKtxdOTIww45wI+W6Js8Hl6B7o5oBucgygFUQn
            jumH0q8eCZOm+5p+mHdDUYuL3VsXKYmxo2/kHaZN310+TdshAxMcuosjwHiLfb/9
            EnQIpVhOBINbKDJENTBpJ9057yFCyqgpOVafusHk7y/uxAlll5uyUyCzHmVyCxy1
            gJJr+HuR6z34KjXj9Hq3EyDwVFU0wMPGRwb08Frz2N4s1V4YGPVtzViKT4U9u3zZ
            5CSws2oXZzmCBpUr9NsIrBWN28yzdg8AdeYzfwmqbmImU3BJK6hjOqRfxlwMixa1
            ivh37VW3cuEWd0jbyYlkl3e8Z1vcd2ZPo8YeMoSF7rWnvfEHsUqQGnuwxgXFAOCN
            g4Vd3UksSSGvJL4fiz2w1HZ+f2Ti9sS2QpR3fr+UR0wWdWi1n6WjWsYfDOZabrPg
            HuckPdd8572CBbk88OJhds9kGhT4bFjMiEOrajwkGRuyPIF7Fl8EKLOdDCzlmAJ3
            tmwnYp9dcHICXl61dNw8HOttVBO6pYzEuL4PrOczdCHt2PBPnKN0R3OdKrfOwN/U
            aAEJAhAuVbGGXxJQCjHgu1uQrAkIcC6AtCBGf1CT25PsVRvdJ0SvaSV3TvvkmZ3/
            FpSMMB4cqv48FjyW+I1olJGTYiKO+NfkfHuEBSPddwW/5YugDxfcrAxnMrT6OgXf
            P4g7dkGu5knW
            =NNMF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-mail-password
    namespace: gitlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:A7xu3Bld2FFA10So6CjegA==,iv:sxLBsqOLn9b1kNqjVnqOnOIwO5cWWW+AOXKEucyxU84=,tag:rYmHr3z3Ox7GnfCFROOQeA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-24T11:31:19Z"
    mac: ENC[AES256_GCM,data:jj97mIXTYTfhBoyHfx2S6d7YSRPHCjnm3L4/m2Mk5UtjwFPqJxa153qTcd787y53oMmr/Q407J9FiHjBhOB1q88XqgE63BNL37NK9Ac3NdMo3/zyoThCQqWR6huMs70OVMyF65ic67TwrskYS4+AmdZA76kucVvAipQYyuVX+a8=,iv:U8jySAaGvnLQNwHlwrjBeeobylR6zHH7OwXsI+eev28=,tag:1D7ylul7Sscl8fLqC66vCw==,type:str]
    pgp:
        - created_at: "2026-06-24T11:31:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAApjOT7XqOI0SmwZe26btW9a+cOnZKSMGadWFYq6XLX67m
            24TsBs+FARnOoSKAJb5uijkb5MARdoxwWN8474ekyui+cy0bR5rLjZEy78f0dmRV
            hCUCTaVE2rcTStwasmHMzlHZbcJKtxdOTIww45wI+W6Js8Hl6B7o5oBucgygFUQn
            jumH0q8eCZOm+5p+mHdDUYuL3VsXKYmxo2/kHaZN310+TdshAxMcuosjwHiLfb/9
            EnQIpVhOBINbKDJENTBpJ9057yFCyqgpOVafusHk7y/uxAlll5uyUyCzHmVyCxy1
            gJJr+HuR6z34KjXj9Hq3EyDwVFU0wMPGRwb08Frz2N4s1V4YGPVtzViKT4U9u3zZ
            5CSws2oXZzmCBpUr9NsIrBWN28yzdg8AdeYzfwmqbmImU3BJK6hjOqRfxlwMixa1
            ivh37VW3cuEWd0jbyYlkl3e8Z1vcd2ZPo8YeMoSF7rWnvfEHsUqQGnuwxgXFAOCN
            g4Vd3UksSSGvJL4fiz2w1HZ+f2Ti9sS2QpR3fr+UR0wWdWi1n6WjWsYfDOZabrPg
            HuckPdd8572CBbk88OJhds9kGhT4bFjMiEOrajwkGRuyPIF7Fl8EKLOdDCzlmAJ3
            tmwnYp9dcHICXl61dNw8HOttVBO6pYzEuL4PrOczdCHt2PBPnKN0R3OdKrfOwN/U
            aAEJAhAuVbGGXxJQCjHgu1uQrAkIcC6AtCBGf1CT25PsVRvdJ0SvaSV3TvvkmZ3/
            FpSMMB4cqv48FjyW+I1olJGTYiKO+NfkfHuEBSPddwW/5YugDxfcrAxnMrT6OgXf
            P4g7dkGu5knW
            =NNMF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-oidc-sso
    namespace: gitlab
type: Opaque
stringData:
    provider: ENC[AES256_GCM,data:6SNSJD3oA9Mi+JhLVq+PFC7ad8DHPf5nOUxEN7FcLqqf1WO5r95JDT0R2+JtWqg20JSDkz2c1eNWCrX1fQpb7FAxrfurEiR5QIeH5RtVbpH05JXqF3Yzy+d9vjZNdNgdz/2mvycRPvJ999DEWjxXv7wvM6hGHClvA6MQ+PNkpfKclFTJEkOYj4xCyqD1njIOuODMYLY0i+1k8+ilE8ACgN3caRqhgBtpxfN1ODOrHUaoz0hIXHUBtfs2wGqyxiR8Z4vCPh9TfCLCtIb1YpCQGeu/0OYDJXre/dpuRtI2O/INg1gz9r84g9DboM7rYCWD+Aq1vB2X1o+ikJqWuwPtxs3YnTqJb4nDf1UiKy/BdgqgI01dE387fZ/O814+B2W79jxyt2bC8qj6B8gmTq0QW3MCSLsBZiu1zEdChiyw1PrEXpAslrG3sWzlLXuLLoI3/yf6Enn4ytjaxZxOnDjdUhQ4Zwj8aJxzrPa40oT9D8XTF2T4mHbjaFZTMb+jRLzgt3kXj30Rfo4j9Mjf1I1oZ1SfZGlOSkvWXmqputZSlkVnkp0NX98WWzshLicagTqblhSQoJQShu8XOh1CwvWn+ouYbncIoMgp+WI=,iv:fi6SAAMKwhbpD6gGTnyDQColirz3uv9KKiWtk4okVjU=,tag:U64AMJL5QdTTkMtH8AmCOg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-24T11:31:19Z"
    mac: ENC[AES256_GCM,data:jj97mIXTYTfhBoyHfx2S6d7YSRPHCjnm3L4/m2Mk5UtjwFPqJxa153qTcd787y53oMmr/Q407J9FiHjBhOB1q88XqgE63BNL37NK9Ac3NdMo3/zyoThCQqWR6huMs70OVMyF65ic67TwrskYS4+AmdZA76kucVvAipQYyuVX+a8=,iv:U8jySAaGvnLQNwHlwrjBeeobylR6zHH7OwXsI+eev28=,tag:1D7ylul7Sscl8fLqC66vCw==,type:str]
    pgp:
        - created_at: "2026-06-24T11:31:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAApjOT7XqOI0SmwZe26btW9a+cOnZKSMGadWFYq6XLX67m
            24TsBs+FARnOoSKAJb5uijkb5MARdoxwWN8474ekyui+cy0bR5rLjZEy78f0dmRV
            hCUCTaVE2rcTStwasmHMzlHZbcJKtxdOTIww45wI+W6Js8Hl6B7o5oBucgygFUQn
            jumH0q8eCZOm+5p+mHdDUYuL3VsXKYmxo2/kHaZN310+TdshAxMcuosjwHiLfb/9
            EnQIpVhOBINbKDJENTBpJ9057yFCyqgpOVafusHk7y/uxAlll5uyUyCzHmVyCxy1
            gJJr+HuR6z34KjXj9Hq3EyDwVFU0wMPGRwb08Frz2N4s1V4YGPVtzViKT4U9u3zZ
            5CSws2oXZzmCBpUr9NsIrBWN28yzdg8AdeYzfwmqbmImU3BJK6hjOqRfxlwMixa1
            ivh37VW3cuEWd0jbyYlkl3e8Z1vcd2ZPo8YeMoSF7rWnvfEHsUqQGnuwxgXFAOCN
            g4Vd3UksSSGvJL4fiz2w1HZ+f2Ti9sS2QpR3fr+UR0wWdWi1n6WjWsYfDOZabrPg
            HuckPdd8572CBbk88OJhds9kGhT4bFjMiEOrajwkGRuyPIF7Fl8EKLOdDCzlmAJ3
            tmwnYp9dcHICXl61dNw8HOttVBO6pYzEuL4PrOczdCHt2PBPnKN0R3OdKrfOwN/U
            aAEJAhAuVbGGXxJQCjHgu1uQrAkIcC6AtCBGf1CT25PsVRvdJ0SvaSV3TvvkmZ3/
            FpSMMB4cqv48FjyW+I1olJGTYiKO+NfkfHuEBSPddwW/5YugDxfcrAxnMrT6OgXf
            P4g7dkGu5knW
            =NNMF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage-s3cmd
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:PyBxKyr0JH+O6t+WQWHxlWcyuvaKuN7eEfSR8iiysDgMPPBXsqzNArdFzSu9zNzA1bUx3Cp2QCNoZc66fsW5KlsizmHeKHoCJgbXM20/8SzfOFV5QcrUG8kJRlDq1arx2MHn9DbvSizi7Zjkmh4xePe2RQ9pYLj8YzljF2vPQ25oD2t/ODsNE8bjUmrRxYkqYFGGY+YpjWhK+vLOZpNgPNUP0ng5O5BwUTFyg4a6fmabNB/55PX+g2UBHi2pRwDbxfRUGk0IVkss9ZPfpxC3KalTjcuky5pP028qgWkqFjpBRlMW2jV2v6C+a8tVO62BJVAyiQ0kRERZ9Nf5pnEEh2IV/TY=,iv:Ie86mMfL59poDkPzSzO8U0rQQUhRvMA7J3IhTNHoy4w=,tag:VDB5X7uWTsgmYKO0iF1VxA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-24T11:31:19Z"
    mac: ENC[AES256_GCM,data:jj97mIXTYTfhBoyHfx2S6d7YSRPHCjnm3L4/m2Mk5UtjwFPqJxa153qTcd787y53oMmr/Q407J9FiHjBhOB1q88XqgE63BNL37NK9Ac3NdMo3/zyoThCQqWR6huMs70OVMyF65ic67TwrskYS4+AmdZA76kucVvAipQYyuVX+a8=,iv:U8jySAaGvnLQNwHlwrjBeeobylR6zHH7OwXsI+eev28=,tag:1D7ylul7Sscl8fLqC66vCw==,type:str]
    pgp:
        - created_at: "2026-06-24T11:31:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAApjOT7XqOI0SmwZe26btW9a+cOnZKSMGadWFYq6XLX67m
            24TsBs+FARnOoSKAJb5uijkb5MARdoxwWN8474ekyui+cy0bR5rLjZEy78f0dmRV
            hCUCTaVE2rcTStwasmHMzlHZbcJKtxdOTIww45wI+W6Js8Hl6B7o5oBucgygFUQn
            jumH0q8eCZOm+5p+mHdDUYuL3VsXKYmxo2/kHaZN310+TdshAxMcuosjwHiLfb/9
            EnQIpVhOBINbKDJENTBpJ9057yFCyqgpOVafusHk7y/uxAlll5uyUyCzHmVyCxy1
            gJJr+HuR6z34KjXj9Hq3EyDwVFU0wMPGRwb08Frz2N4s1V4YGPVtzViKT4U9u3zZ
            5CSws2oXZzmCBpUr9NsIrBWN28yzdg8AdeYzfwmqbmImU3BJK6hjOqRfxlwMixa1
            ivh37VW3cuEWd0jbyYlkl3e8Z1vcd2ZPo8YeMoSF7rWnvfEHsUqQGnuwxgXFAOCN
            g4Vd3UksSSGvJL4fiz2w1HZ+f2Ti9sS2QpR3fr+UR0wWdWi1n6WjWsYfDOZabrPg
            HuckPdd8572CBbk88OJhds9kGhT4bFjMiEOrajwkGRuyPIF7Fl8EKLOdDCzlmAJ3
            tmwnYp9dcHICXl61dNw8HOttVBO6pYzEuL4PrOczdCHt2PBPnKN0R3OdKrfOwN/U
            aAEJAhAuVbGGXxJQCjHgu1uQrAkIcC6AtCBGf1CT25PsVRvdJ0SvaSV3TvvkmZ3/
            FpSMMB4cqv48FjyW+I1olJGTYiKO+NfkfHuEBSPddwW/5YugDxfcrAxnMrT6OgXf
            P4g7dkGu5knW
            =NNMF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:G6b2t2MgpZN9MwLzbZwhbS6o+VB60Y4kE6ZCtIYjeN18sdvJEJmcQ7FHVny+1+A/r+EsOP9V6RVsMAg6GFWtssigtt3ZDb6hiH9YCZAwkAKURZ1YqqDE55Z0uhaVu7gxiRW3v+OajbHTcrJ9Z1cwt4iimW5zjLKEMUiH75ut0bcj2BhPVCq5QwbtwOEJd2sr3uODIFAUiJgcBtqLO/umR9R/jjoMBx4HYQ8AKAEnEoHWy6HnqBBh0JhXsTF7KFeemC1Kzq7dWW+pAOtmGnTn8apswBjLTfTCCexG8F+3+SIwn3ZEkwZZ40DCkwLwN8iCnNpk,iv:9h04WFzqQQhIkgSPmXiKk0xO2JivV1NvH7qsHCqtbsg=,tag:Avdrc9hzmypYSzlhiIZ4KQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-24T11:31:19Z"
    mac: ENC[AES256_GCM,data:jj97mIXTYTfhBoyHfx2S6d7YSRPHCjnm3L4/m2Mk5UtjwFPqJxa153qTcd787y53oMmr/Q407J9FiHjBhOB1q88XqgE63BNL37NK9Ac3NdMo3/zyoThCQqWR6huMs70OVMyF65ic67TwrskYS4+AmdZA76kucVvAipQYyuVX+a8=,iv:U8jySAaGvnLQNwHlwrjBeeobylR6zHH7OwXsI+eev28=,tag:1D7ylul7Sscl8fLqC66vCw==,type:str]
    pgp:
        - created_at: "2026-06-24T11:31:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAApjOT7XqOI0SmwZe26btW9a+cOnZKSMGadWFYq6XLX67m
            24TsBs+FARnOoSKAJb5uijkb5MARdoxwWN8474ekyui+cy0bR5rLjZEy78f0dmRV
            hCUCTaVE2rcTStwasmHMzlHZbcJKtxdOTIww45wI+W6Js8Hl6B7o5oBucgygFUQn
            jumH0q8eCZOm+5p+mHdDUYuL3VsXKYmxo2/kHaZN310+TdshAxMcuosjwHiLfb/9
            EnQIpVhOBINbKDJENTBpJ9057yFCyqgpOVafusHk7y/uxAlll5uyUyCzHmVyCxy1
            gJJr+HuR6z34KjXj9Hq3EyDwVFU0wMPGRwb08Frz2N4s1V4YGPVtzViKT4U9u3zZ
            5CSws2oXZzmCBpUr9NsIrBWN28yzdg8AdeYzfwmqbmImU3BJK6hjOqRfxlwMixa1
            ivh37VW3cuEWd0jbyYlkl3e8Z1vcd2ZPo8YeMoSF7rWnvfEHsUqQGnuwxgXFAOCN
            g4Vd3UksSSGvJL4fiz2w1HZ+f2Ti9sS2QpR3fr+UR0wWdWi1n6WjWsYfDOZabrPg
            HuckPdd8572CBbk88OJhds9kGhT4bFjMiEOrajwkGRuyPIF7Fl8EKLOdDCzlmAJ3
            tmwnYp9dcHICXl61dNw8HOttVBO6pYzEuL4PrOczdCHt2PBPnKN0R3OdKrfOwN/U
            aAEJAhAuVbGGXxJQCjHgu1uQrAkIcC6AtCBGf1CT25PsVRvdJ0SvaSV3TvvkmZ3/
            FpSMMB4cqv48FjyW+I1olJGTYiKO+NfkfHuEBSPddwW/5YugDxfcrAxnMrT6OgXf
            P4g7dkGu5knW
            =NNMF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:H8MyyhRfInHA29Cspm1Y5QQSOmBRTLwmhTAo2GQRBOlaFJ/nhGRialNnlODPumqTKm7aR1o26U0n+bE5GX+g44kCUGRKtTc65f6Wt/FlUtQ3HOTheUrI8Nr2PT7yarPARzNj6iqWFlHcSMQCSsjct8nbnkty1JGAQ2E78b9dskZ19CumDKJjE9RG+H+EEQf20kN5QN1nI+ONlwbxgSIqzAZ+YmHsLi/ZfGFfcmtX1kZ0VLBZk6y2MAODNL0I9namF7UfNa1AuFaZKCvC8/BL2Bg1RZjwWVZ8R43kku6PkLV8CLJsUNZKHaIrEuNShfN3ptjqDitKLeznbGLzflHes/fyPh30CWyTf4aTZX8i6CjaxFEpoKOBtBfV/aIIBUiy,iv:TCVQwnSwHz1jS062UyBm3dNL2TiEHdoK8CxiaP9hNI8=,tag:8BGFx/gkrriQdgWDqZLcmw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-24T11:31:19Z"
    mac: ENC[AES256_GCM,data:jj97mIXTYTfhBoyHfx2S6d7YSRPHCjnm3L4/m2Mk5UtjwFPqJxa153qTcd787y53oMmr/Q407J9FiHjBhOB1q88XqgE63BNL37NK9Ac3NdMo3/zyoThCQqWR6huMs70OVMyF65ic67TwrskYS4+AmdZA76kucVvAipQYyuVX+a8=,iv:U8jySAaGvnLQNwHlwrjBeeobylR6zHH7OwXsI+eev28=,tag:1D7ylul7Sscl8fLqC66vCw==,type:str]
    pgp:
        - created_at: "2026-06-24T11:31:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAApjOT7XqOI0SmwZe26btW9a+cOnZKSMGadWFYq6XLX67m
            24TsBs+FARnOoSKAJb5uijkb5MARdoxwWN8474ekyui+cy0bR5rLjZEy78f0dmRV
            hCUCTaVE2rcTStwasmHMzlHZbcJKtxdOTIww45wI+W6Js8Hl6B7o5oBucgygFUQn
            jumH0q8eCZOm+5p+mHdDUYuL3VsXKYmxo2/kHaZN310+TdshAxMcuosjwHiLfb/9
            EnQIpVhOBINbKDJENTBpJ9057yFCyqgpOVafusHk7y/uxAlll5uyUyCzHmVyCxy1
            gJJr+HuR6z34KjXj9Hq3EyDwVFU0wMPGRwb08Frz2N4s1V4YGPVtzViKT4U9u3zZ
            5CSws2oXZzmCBpUr9NsIrBWN28yzdg8AdeYzfwmqbmImU3BJK6hjOqRfxlwMixa1
            ivh37VW3cuEWd0jbyYlkl3e8Z1vcd2ZPo8YeMoSF7rWnvfEHsUqQGnuwxgXFAOCN
            g4Vd3UksSSGvJL4fiz2w1HZ+f2Ti9sS2QpR3fr+UR0wWdWi1n6WjWsYfDOZabrPg
            HuckPdd8572CBbk88OJhds9kGhT4bFjMiEOrajwkGRuyPIF7Fl8EKLOdDCzlmAJ3
            tmwnYp9dcHICXl61dNw8HOttVBO6pYzEuL4PrOczdCHt2PBPnKN0R3OdKrfOwN/U
            aAEJAhAuVbGGXxJQCjHgu1uQrAkIcC6AtCBGf1CT25PsVRvdJ0SvaSV3TvvkmZ3/
            FpSMMB4cqv48FjyW+I1olJGTYiKO+NfkfHuEBSPddwW/5YugDxfcrAxnMrT6OgXf
            P4g7dkGu5knW
            =NNMF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
