apiVersion: v1
kind: Secret
metadata:
    name: lore-oidc
    namespace: lore
type: Opaque
stringData:
    LORE__OIDC_ISSUER: ENC[AES256_GCM,data:GK7CTLgDeA0aH97p2ngCR/nqjWKPzpmZGthKxALz+CnYqs4C,iv:Kh7EFLbdwLoiebXYks/N5JOtPTeZ9UXjDJ2gzrTru3w=,tag:O060pAVoS2gOV4zqRqwvuQ==,type:str]
    LORE__OIDC_CLIENT_ID: ENC[AES256_GCM,data:9hfAWywT5A==,iv:JfqNp+L+ESVML9ZVZx+YOA6lbyBSZZpxTnC1Uq0Ra+4=,tag:o5wcZwnVOC1g0w99xhAcDQ==,type:str]
    LORE__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ePNmFnWNCNomRrPOalUcTa+XEVYa22IlEgLU8ki/+n3vjcvLfGNMATC2QPxSpA4ukL4cuI2t1lVPoXMN8qf2DZEvL+t6ELc4H7NU33fsKuUJQdzA6/8=,iv:iOUbtp5x/KCkfi8MmYSALZ+WV3dSKtiKl4b5J+JM4GA=,tag:qfU6Y7+YyCIqWf9X9I+81A==,type:str]
    LORE__OIDC_SESSION_SECRET: ENC[AES256_GCM,data:AdXVVSypkh7tc3kkVpOyespuo8RcjGK7SXc2RbjoYQM=,iv:qolIpCQhg21mNa7CoQTQfe2gxUvXZrV4QZoH/LjGWck=,tag:4pt5z5Kw6P0cmI7/6gVSDw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-16T13:02:48Z"
    mac: ENC[AES256_GCM,data:1QnxoFpMvKiTxBsGUPq8W1qTb5Ny0BZVC6c7WKHth+CzXpH2zu0GQw/tajhm9xMU2ldMKaEH7kcC3tGfa87dDYdi/KlNiuOlnYFdejzo4uVd0nZIzwks7kq+TvJHd5OrNSfq3S5JtYJlvfWC7FDvI9/CdsEFNjkVmFNev49t1Ug=,iv:ww8r5C79QYLGuoGRInfgiO9+A08mVNuLaoXZ3lCl03s=,tag:tjn0YhOfeENwx9AGsGKU9g==,type:str]
    pgp:
        - created_at: "2026-09-16T13:02:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9EGTwNPhZ0dntm4EWfa0J4UHAkO/ZG5v77Ey5vNlUgATe
            GOFqL+FiNDEt+NF9TsuLCUdCyEy5Sr+P3jf4+E6m1ZKeFiE7LziQg4yqWdOPeTcG
            vzlYIrJuYxNEv1k8dr7sqqFwJGWJe5TFhnemGBsbecYiY6Cp2cVeT/mqGTOJLA9D
            I+fyUiZrbIwII/XJGJy7xkMQV6KvNVy2pElhYruykI5AU0ANDF5BoO836KGE0DdR
            3LczxL6dRFUzhkASnKIS7ZKzUjj8QJMw9zMOlu/8ZRjM4eoVXYnGKfJbB9a+jzHH
            mtKIp+ozlFehTHiVzHnez9oSTYv34KZJ9vrZCgXUPfxv8EMsi4j+6OcqvihgWOY+
            EUn3ZbMEC7JBmtr3E56Xwlm0s3x93xTh6wPY/lMEUD7lBvamIut+oNjeU6edp74R
            8OXmHCCJEiPFGoGV/7lPae/PzUfdGInnWT6mAq3jjvoQijJ3Iz6zvL2ctajBYvnQ
            TB8g58qfYt3o8CVyX1ezHSL5KpjC3ZWCZfyQHVLSz64t+LpHxR6WbR4XAueiBe/o
            inZzKV7+Hgb3hsy+bMVRa2AY9lTa0XMi917oG9V4JQ2dsyhG8wGrURztByQkW4pO
            G0QotWaPxzLKyjFRpoRPc3wRAhD3hdc9GuW1IvBwTgqK2kEdi53faBdObxyuFAnU
            aAEJAhBSMD7gJ3BksuqYeHDhqwDheoBfXIA92lmzkQ84WNkyvkZwmJ9kl0CsACxm
            CEztiiNFknP44fUwO7Zw53f2/J6ueMJ/WL61TYGpV0WFFzTRAampjDF8TxDHpQKv
            Nbq/AL2wbGLz
            =XMGW
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lore-config
    namespace: lore
type: Opaque
stringData:
    KUMBUKA__ENCRYPTION_KEY: ENC[AES256_GCM,data:llvWo5HPKMcSEpYXDAPkvZyRzgFovgGpjKNGeUqghkHXTs7+sZKj+AKWPlM=,iv:Mct+Swyt/6fDFVVj3F0bikKs3Gu2NTY0z+UG5iAUYlY=,tag:bwGYMctUuo685BiCmcOYBw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-16T13:02:48Z"
    mac: ENC[AES256_GCM,data:1QnxoFpMvKiTxBsGUPq8W1qTb5Ny0BZVC6c7WKHth+CzXpH2zu0GQw/tajhm9xMU2ldMKaEH7kcC3tGfa87dDYdi/KlNiuOlnYFdejzo4uVd0nZIzwks7kq+TvJHd5OrNSfq3S5JtYJlvfWC7FDvI9/CdsEFNjkVmFNev49t1Ug=,iv:ww8r5C79QYLGuoGRInfgiO9+A08mVNuLaoXZ3lCl03s=,tag:tjn0YhOfeENwx9AGsGKU9g==,type:str]
    pgp:
        - created_at: "2026-09-16T13:02:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9EGTwNPhZ0dntm4EWfa0J4UHAkO/ZG5v77Ey5vNlUgATe
            GOFqL+FiNDEt+NF9TsuLCUdCyEy5Sr+P3jf4+E6m1ZKeFiE7LziQg4yqWdOPeTcG
            vzlYIrJuYxNEv1k8dr7sqqFwJGWJe5TFhnemGBsbecYiY6Cp2cVeT/mqGTOJLA9D
            I+fyUiZrbIwII/XJGJy7xkMQV6KvNVy2pElhYruykI5AU0ANDF5BoO836KGE0DdR
            3LczxL6dRFUzhkASnKIS7ZKzUjj8QJMw9zMOlu/8ZRjM4eoVXYnGKfJbB9a+jzHH
            mtKIp+ozlFehTHiVzHnez9oSTYv34KZJ9vrZCgXUPfxv8EMsi4j+6OcqvihgWOY+
            EUn3ZbMEC7JBmtr3E56Xwlm0s3x93xTh6wPY/lMEUD7lBvamIut+oNjeU6edp74R
            8OXmHCCJEiPFGoGV/7lPae/PzUfdGInnWT6mAq3jjvoQijJ3Iz6zvL2ctajBYvnQ
            TB8g58qfYt3o8CVyX1ezHSL5KpjC3ZWCZfyQHVLSz64t+LpHxR6WbR4XAueiBe/o
            inZzKV7+Hgb3hsy+bMVRa2AY9lTa0XMi917oG9V4JQ2dsyhG8wGrURztByQkW4pO
            G0QotWaPxzLKyjFRpoRPc3wRAhD3hdc9GuW1IvBwTgqK2kEdi53faBdObxyuFAnU
            aAEJAhBSMD7gJ3BksuqYeHDhqwDheoBfXIA92lmzkQ84WNkyvkZwmJ9kl0CsACxm
            CEztiiNFknP44fUwO7Zw53f2/J6ueMJ/WL61TYGpV0WFFzTRAampjDF8TxDHpQKv
            Nbq/AL2wbGLz
            =XMGW
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
