apiVersion: v1
kind: Secret
metadata:
    name: kumbuka-oidc
    namespace: kumbuka
type: Opaque
stringData:
    KUMBUKA__OIDC_ISSUER: ENC[AES256_GCM,data:lNrVEnUQabrkwXiRXT+TVJMS9c5f1OdAAh/EEiWTwAMxICxQ,iv:pV0+mYZWa6kuPyVu7L16MUpkd5obE7RChlh0pNOSWKI=,tag:06qO/PkFwdsuXQQO45Dj0g==,type:str]
    KUMBUKA__OIDC_CLIENT_ID: ENC[AES256_GCM,data:ygwWB5JqRg==,iv:eqFdjohJo+eKTeFTiFI/wcVbwyWv0qKzXybSuzAR6lI=,tag:1LbYZc12IgqXP3VyV2Yyfw==,type:str]
    KUMBUKA__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Q69uBU9PKcmkMGa0GmGSw7ZjlpQzYnslXnsxdtKkZC1g+ihsZvzHYn0n4ibBWsKft+zjucSEa5W4xuWJ6oMkwR6NH98gK6U0LRSKtNvp+orVd1MJE9c=,iv:kN3SaMcBUCyaaWLsoLWGS+yeehmTgyUxkXyH7T9Y4OQ=,tag:FWqkzfxd6rmDqZvGEshfSw==,type:str]
    KUMBUKA__OIDC_SESSION_SECRET: ENC[AES256_GCM,data:eSewBAOdhoTKCBqGBmBaMHkKVFkqSN6g+H8SOa8fAyY=,iv:FtQq3GqFxQ5QLSOUaPrV1TKwG2nWwczd1oQ+JUn3kG0=,tag:JOkeLqMN3iRf9jVfeh1JJg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-17T06:11:41Z"
    mac: ENC[AES256_GCM,data:oeYejI9/SPxkxptx00F+axX4C6Ds3MJIbvaSjX4kCJMLI9L1Eb6wijadG6hkEckQRx/RAmhRf7WaxEFI1yoTUwGyePTqdHYL1SkUssCI+M1Vc2GiZYLgwmSJQPApASrWRdVvSsomu3Nt9++aYf69m3yFBTMYJWsxwrMFgSdv0n8=,iv:K2zmox7+TxmUXOMk0M69qO5O+Wn9GyUl4UcHiMg+Nx0=,tag:ZO8vkaeYWQVUucfiIGghkw==,type:str]
    pgp:
        - created_at: "2026-09-17T06:11:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+JAFI66wqI0Wqc0XNXF6mBdmtLASLpayd2131XCl0lvkM
            GQYzX993jZMV3J86hzje/1Sa6UIjaLtnCgEwRsHoYCTh3AoooYGyYJERAC5HndRO
            ZE/l916hqqa4g9o4DC5xA8qAc6ybCbywK9Fa/cuFa7qXRpZdfRchUvEWO5sHM1sI
            tECT6ZLVjmbetedFuTU9+D4gZGAM6CMldTtu5lfHLxMM0l5MF4uSxFKs7kD+rqKU
            9HAN+s2oPJzxfr6soJKojTGphTVbpIC366hSN0lMnZHvZN3kR+EiU0SGUkedaJiN
            y6vSDD1YRGb77WlMLx7f/OARNt+lTu0D8FY4aRt0+G/o5t+dE2V/1KRx3R1VyIlF
            9GsZe1uDPaSlR7GiHo/w9a0WhMIjbWQbK3SIvY/u601nbNY63T7uyLZSdVTJOptR
            HQVDfRyr6CulWvCTYvqsNd01c+baQZjXnQqCOPYmB7UyxoPkWtyv5il7LzzhZ2VI
            UqkW/CmmNZufEhkdZfZLimIW5N9WyIc3Cor0T6vVUTDXkrTuCATY1sdQHFwr1DL4
            f6kS6AyOCtHPl4fZvMy7SRHEoqpSojmpiYlfmV7/pKfq1hR4m3f3H2z7QmHJvtc6
            q9Ccozr1YP84SDpLYBg+3ymt5EbRbmpQ952tuxTy3S4OoId4xcpHfeX/rxY7uR3U
            aAEJAhDg/5qGPI8uaTes9gj4y4A9dxRIcMHHA5MW4HrDYM0CrK5dsEFt/wnp6UzR
            lz0hgdKNxHPT/qMm7S7P6ulaz3BIi6cMfuPI4UwmgNFHbX14O1m2QsgTZ5N+F6VJ
            Qz//aobLQ2iw
            =+dIv
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: kumbuka-config
    namespace: kumbuka
type: Opaque
stringData:
    KUMBUKA__ENCRYPTION_KEY: ENC[AES256_GCM,data:fb0lksS+iamoMnMiKOFc8WhQtp/kXfIFgL08kdrQKoRdFQXefurGka/+feQ=,iv:4bMG6BvIWZjbp9V7az/CQ/vOjooJm2nYhenOv9pajic=,tag:bXpTsOIiwEabhwQYlw0yOA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-17T06:11:41Z"
    mac: ENC[AES256_GCM,data:oeYejI9/SPxkxptx00F+axX4C6Ds3MJIbvaSjX4kCJMLI9L1Eb6wijadG6hkEckQRx/RAmhRf7WaxEFI1yoTUwGyePTqdHYL1SkUssCI+M1Vc2GiZYLgwmSJQPApASrWRdVvSsomu3Nt9++aYf69m3yFBTMYJWsxwrMFgSdv0n8=,iv:K2zmox7+TxmUXOMk0M69qO5O+Wn9GyUl4UcHiMg+Nx0=,tag:ZO8vkaeYWQVUucfiIGghkw==,type:str]
    pgp:
        - created_at: "2026-09-17T06:11:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+JAFI66wqI0Wqc0XNXF6mBdmtLASLpayd2131XCl0lvkM
            GQYzX993jZMV3J86hzje/1Sa6UIjaLtnCgEwRsHoYCTh3AoooYGyYJERAC5HndRO
            ZE/l916hqqa4g9o4DC5xA8qAc6ybCbywK9Fa/cuFa7qXRpZdfRchUvEWO5sHM1sI
            tECT6ZLVjmbetedFuTU9+D4gZGAM6CMldTtu5lfHLxMM0l5MF4uSxFKs7kD+rqKU
            9HAN+s2oPJzxfr6soJKojTGphTVbpIC366hSN0lMnZHvZN3kR+EiU0SGUkedaJiN
            y6vSDD1YRGb77WlMLx7f/OARNt+lTu0D8FY4aRt0+G/o5t+dE2V/1KRx3R1VyIlF
            9GsZe1uDPaSlR7GiHo/w9a0WhMIjbWQbK3SIvY/u601nbNY63T7uyLZSdVTJOptR
            HQVDfRyr6CulWvCTYvqsNd01c+baQZjXnQqCOPYmB7UyxoPkWtyv5il7LzzhZ2VI
            UqkW/CmmNZufEhkdZfZLimIW5N9WyIc3Cor0T6vVUTDXkrTuCATY1sdQHFwr1DL4
            f6kS6AyOCtHPl4fZvMy7SRHEoqpSojmpiYlfmV7/pKfq1hR4m3f3H2z7QmHJvtc6
            q9Ccozr1YP84SDpLYBg+3ymt5EbRbmpQ952tuxTy3S4OoId4xcpHfeX/rxY7uR3U
            aAEJAhDg/5qGPI8uaTes9gj4y4A9dxRIcMHHA5MW4HrDYM0CrK5dsEFt/wnp6UzR
            lz0hgdKNxHPT/qMm7S7P6ulaz3BIi6cMfuPI4UwmgNFHbX14O1m2QsgTZ5N+F6VJ
            Qz//aobLQ2iw
            =+dIv
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
