apiVersion: v1
kind: Secret
metadata:
    name: kumbuka-oidc
    namespace: kumbuka
type: Opaque
stringData:
    KUMBUKA__OIDC_ISSUER: ENC[AES256_GCM,data:6njBCa7EHmQX/qLlzZw+b5GCZ1cTWY8yFpRkMKoYw6470ROf,iv:p778p2G7H3Z7vpVlvhLXvcCD8fnu/Wbn8Jjno5LXjRI=,tag:pwwDZNUuLv8XZiE6eyamBw==,type:str]
    KUMBUKA__OIDC_CLIENT_ID: ENC[AES256_GCM,data:48aeQgUcDA==,iv:XvlfmasfKNhfBbZLL17ehNNc8SH1AQZLQ8ePn9edeA4=,tag:NusjsgXnTTBbB1T3l7VH+w==,type:str]
    KUMBUKA__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SW/Vwq0sE6zIN/Vx7UPP1gcZssI5yEldNwVou0WVyJ1VnLLD9V3JJg9dm48zQvoars34nql1hJHpcHrETFT155oVGs/LlDHxS8126XzmQn9RDm1Pztc=,iv:PFtqFxo9lTpX8HIVRW18r9s1C+Fs51SWerNe2ftQ+7o=,tag:RdMFxvEO8lyXywLzVucXJA==,type:str]
    KUMBUKA__OIDC_SESSION_SECRET: ENC[AES256_GCM,data:5akch4MMeNS6y/f8Lf5jJHGQA8XLT1v/VZ5f7MmgsBc=,iv:AOI92ZRrsyU973LNeGt9chBwdsC/z5Jd4K55IxY03p4=,tag:S+7pZN3ZIsu+2YadvBeETA==,type:str]
    KUMBUKA__OIDC_GROUP_CLAIM: ENC[AES256_GCM,data:fc+IsCH2,iv:gFVtDl7gSvQnxkk9DTQ5/a0dB8WcKaVmqu4lvBmcgWs=,tag:DK64nuy0lm19cXWeeQH4NA==,type:str]
    KUMBUKA__OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:/JNcTIhHU8puBVz5AGSP,iv:7o/TGiS4/zMY64csngxFQLnghyqGHikyVw8D9AmP+Sw=,tag:VrfEJsFTFbpOdfSO5VHcuw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-10-07T12:45:28Z"
    mac: ENC[AES256_GCM,data:/PTy1mNoVYCZlseMJrPM14pbaxWLEOrifD+E9N3s6ZT95yZqnfqeGXUzL+VL1/ahixWmmECWE76NCZZSOPQuoixiybYt20XkfJu4dFQjdbi6q9vBEzHqmkzPJQ8x8/c5urFD6+Wa0kxHHsbzwqQzjDDPkLVIUcnwwzQroD20Amc=,iv:zDWXGD0kPxxPJn8RrUMiU0xOl8gw3yL+igEvARmaaTY=,tag:x6q8hAYNLzebq/CwXeGkNA==,type:str]
    pgp:
        - created_at: "2026-10-07T12:45:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAugANB79sLcNp4+nM1+eLBFa7rWsTOjhUWvHIY5rKOqTR
            E22jG2ZcCClJpr5Wz7N9CkBqPYx2P51rMh8U8KlRHp++I3Feye5tEdPKm9Qx89z+
            84ymW8e5l86gFqx2xqF3IwMsDTKRsu1koQgu9whiUrmIVFL/DwL05270ug6SF4bm
            /NESWEIvIwaqjd3PE+Z4BhzKxxxj4QQ/P5Lka7rYXpjJzCUIwX5DnHOMpB8GiFQy
            e3XucpRioIzOthbGTsIHB7ewOUEFSHpAljyz59gpw88R5aIDVxYAgWqwDk9p4GWY
            yNf1YPWCW82HxfDUP++eYnog9FFR8j0EEtuSBOOV4OoeNo+LTGnYDtkEewNdvgWK
            nHaVwNFnhVwH6Hxaufbd0M0l0kXiG44RRrQPi7DZzD4zj65UGbO1uFU28WmqT5Bd
            jmEWhnaAXUrE2W7lXt2sie4Lq8834/xs813L/qip1o+tRtWBR2e1wB5C31A2MjIc
            blLktzFa7p8kyqEs1aPbMLYtx9C3rJrlGJSwSIggiYKudQO1yrRj+UMfl9KMEg20
            j7ApPodlss5aku74esgXwR++rEVzAcHn9v8mEzAvvOWb3SHzZM2J0idWUwcpW2ku
            tzCvukeHBgKlccn2Lqc32NacPq/wIkGdqlOLRbBWKPfFYoPAydc7VKrijVgTZMnU
            aAEJAhCTThHeQqPee/VArhIERA2mPOLSVyeZbtSrQV95/VeG3M6AFnLx7Gi1RI+4
            IwTIrjgPqpSCcVM3803ypKpwZZ7jEO2+/BNLUuAEAPOZY7R4l+kxalY81Vx9iiXB
            6f0/mVIUdVkY
            =bDWx
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: kumbuka-config
    namespace: kumbuka
type: Opaque
stringData:
    KUMBUKA__ENCRYPTION_KEY: ENC[AES256_GCM,data:YpJqZjihWSydW6XHhymbvP/L5wUd3HD9yug8nbR4dccGmrqnJcGlPjq3GiA=,iv:zB15iB7uRaAGTu8XxEPapk0CK1gOhZ4L5qQzcJmSWwc=,tag:8eQXhcklSDJAebS3catMRg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-10-07T12:45:28Z"
    mac: ENC[AES256_GCM,data:/PTy1mNoVYCZlseMJrPM14pbaxWLEOrifD+E9N3s6ZT95yZqnfqeGXUzL+VL1/ahixWmmECWE76NCZZSOPQuoixiybYt20XkfJu4dFQjdbi6q9vBEzHqmkzPJQ8x8/c5urFD6+Wa0kxHHsbzwqQzjDDPkLVIUcnwwzQroD20Amc=,iv:zDWXGD0kPxxPJn8RrUMiU0xOl8gw3yL+igEvARmaaTY=,tag:x6q8hAYNLzebq/CwXeGkNA==,type:str]
    pgp:
        - created_at: "2026-10-07T12:45:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAugANB79sLcNp4+nM1+eLBFa7rWsTOjhUWvHIY5rKOqTR
            E22jG2ZcCClJpr5Wz7N9CkBqPYx2P51rMh8U8KlRHp++I3Feye5tEdPKm9Qx89z+
            84ymW8e5l86gFqx2xqF3IwMsDTKRsu1koQgu9whiUrmIVFL/DwL05270ug6SF4bm
            /NESWEIvIwaqjd3PE+Z4BhzKxxxj4QQ/P5Lka7rYXpjJzCUIwX5DnHOMpB8GiFQy
            e3XucpRioIzOthbGTsIHB7ewOUEFSHpAljyz59gpw88R5aIDVxYAgWqwDk9p4GWY
            yNf1YPWCW82HxfDUP++eYnog9FFR8j0EEtuSBOOV4OoeNo+LTGnYDtkEewNdvgWK
            nHaVwNFnhVwH6Hxaufbd0M0l0kXiG44RRrQPi7DZzD4zj65UGbO1uFU28WmqT5Bd
            jmEWhnaAXUrE2W7lXt2sie4Lq8834/xs813L/qip1o+tRtWBR2e1wB5C31A2MjIc
            blLktzFa7p8kyqEs1aPbMLYtx9C3rJrlGJSwSIggiYKudQO1yrRj+UMfl9KMEg20
            j7ApPodlss5aku74esgXwR++rEVzAcHn9v8mEzAvvOWb3SHzZM2J0idWUwcpW2ku
            tzCvukeHBgKlccn2Lqc32NacPq/wIkGdqlOLRbBWKPfFYoPAydc7VKrijVgTZMnU
            aAEJAhCTThHeQqPee/VArhIERA2mPOLSVyeZbtSrQV95/VeG3M6AFnLx7Gi1RI+4
            IwTIrjgPqpSCcVM3803ypKpwZZ7jEO2+/BNLUuAEAPOZY7R4l+kxalY81Vx9iiXB
            6f0/mVIUdVkY
            =bDWx
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
