---
apiVersion: v1
kind: Service
metadata:
  name: kumbuka
  namespace: kumbuka
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kumbuka
    app.kubernetes.io/component: kumbuka
