---
apiVersion: v1
kind: Secret
metadata:
  name: html2pdf
  namespace: kumbuka
type: Opaque
stringData:
  HTML2PDF__TOKEN: ENC[AES256_GCM,data:bvbNJEEwKRyJxX/LDgIpdU6o+HlWzWiirDsbU2oAoB0eQZBxjDOb1e+tbEc=,iv:42VS+y4YPwHmehXdme5QHl7u9r7N6IpXW8vRX400eVw=,tag:YyGgvFCgYhHxWIFdwzl2VQ==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-10-09T13:32:29Z"
  mac: ENC[AES256_GCM,data:Z9yICspN/1h3IOeaxsVq3ljBNMMbfoazl4jlsMCo2qO4YZa/ctXyfSUt+aKEpTFsuObzIqI+pTlYJrDOrAaeRePEz/hCWxz99HmXIZy+VoDUDSz9YwynCVFgkoqQSSokxP8g6STX32nsoIyY5GHdnGw6YECxQLuHMyJLV5eMU80=,iv:2nQHNUfwdBEtnkCnJ5WcMPY3wQeESkMLbEJDRwtqps8=,tag:DLGpP2h+OFwJVxpeVAwKrA==,type:str]
  pgp:
    - created_at: "2026-10-09T13:32:29Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ/+I/t0YT7wpvOsP+GQwBInGBvcCV/UIKCpxua5xe1d8/P0
        0oRXeskDZms46tmtD93r30Js0pjUqqNi/ypuwY0webfyMhS8jLIWz6IEVRt6E0F+
        ppCtuwB3ZUZ/mHukXMuutkHzR+6oQgKA0tMTcchqZndQcoKEYSorrZNCIjKLpoX+
        Y4ye8vJUGe3i7HJwffSKmD8KPo1Hj2JEYk3rEcx81Q9doYh0hdxbt1YjduTsqM9L
        JU0OikXH1tEleveQ7qtXl7piQRiRlY1vKfaqONyA/J9U6iwjlmRdtvwQv2lR5n2y
        pD3sXO8dmu7+lFO7ZKY9wmIY7gXmUxtJ913mDvpiVK2X2YtY/P8VetlzNUmoZ3XG
        9Gob0JqkGKyiPnlrYSNF917GXouw9xbidBYcZRtcKFLYR4tsB/ygsBbByeJ3hz8n
        UCJ/hrymle+QdoyEuONDpjSl1w/1pxXgldgxkdXBk5uGw3zXVwP4O8TiZ0Sa5KwG
        QOWSaJ7dxnvh/7PX2XMQMSPqwVYZWMwiygZPBUzsmg19ne2cTkLnBMzSGlODdTaK
        6KwtGxCHBvWYlydA9ctQUDrWvup2kLYhAs44/xZc56IptFUqhEIqPOLclCaKJX7+
        2FnamkNDrAgCQ3WJtTiGdQmWU/NNX+mfRiN9wIdmcHUzahHgLbyLNOM0oVnj0rLU
        aAEJAhDY9QadJ4Suq6c8wY1V1+T5XHlDm5bqr0CQsVoj3Y7zXY34HclB1kC15+O/
        oeZhp4u+/qPBhHNCBVygvHSlMHMJSx1QODkQy6yEdRQtmkohVzPxw29YhFcFUpTW
        GLBHaH4RBPnb
        =M86o
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.3
