---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicies/
  - clusterrole-kube-ephemeral-container-exporter.yaml
  - clusterrole-metrics-auth.yaml
  - clusterrolebinding-kube-ephemeral-container-exporter.yaml
  - clusterrolebinding-metrics.yaml
  - deployment.yaml
  - role-leader-election.yaml
  - rolebinding-leader-election.yaml
  - prometheusrule.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
