---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ephemeral-container-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: kube-ephemeral-container-exporter
    app.kubernetes.io/component: controller
