---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicies/
  - deployment.yaml
  - httproute.yaml
  - secret.yaml
  - service.yaml

configMapGenerator:
  - name: lore-external-access-controls
    namespace: lore
    files:
      - lua=scripts/external-access-controls.lua

generatorOptions:
  disableNameSuffixHash: true
