apiVersion: v1
kind: Secret
metadata:
    name: lore-oidc
    namespace: lore
type: Opaque
stringData:
    LORE__OIDC_ISSUER: ENC[AES256_GCM,data:JVt8JTgayJFy2gt1IvQKuMWLu/JbWkYt3U96gPOianaPjTC2,iv:Eh/jvK6+DIHq397TO2Sg1XUVcVGG81/E8ReppcWX/go=,tag:9SqWHJH5rVsfFQjGk6rppQ==,type:str]
    LORE__OIDC_CLIENT_ID: ENC[AES256_GCM,data:5Wu+oA==,iv:mUJl9tkgHvGxw70/WjxSRyGSqS2nMTq3Max51UiZ1uc=,tag:bLdHYqXW/opnNK5Qyp+2sQ==,type:str]
    LORE__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:DAb8cHR9Su6cUZiq64UloD6rdn/4IVoL53X1iq+PCs/0AvSHpUnJfQDMfa9C46bAjGvUcSGLP4bzDuHNny7PEuTirH0tuv1CzefF4Ab/O2Yl7nD3rqc=,iv:Zepdxli79j4wWdOseQmNWSDJA60zzKoQf5jF60daTSM=,tag:Q5k3js1VJzh6z8lun2vs/A==,type:str]
    LORE__OIDC_SESSION_SECRET: ENC[AES256_GCM,data:aLjhiKI2JB1hsk/goMNyLab2wQddekDTKJ91fCDE9Pc=,iv:5ftWly0Q5+Z7vzR/AvafFU5MO1+pH046kIL9Sv91VlE=,tag:MsawewEn8IgZ721qxq3QVg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-09T10:45:36Z"
    mac: ENC[AES256_GCM,data:YfXSdM4z4F032zRXvKcuxzd4i4FaLEkOBbH/ShEw29Wglh2G9PgmKPIptXe3RHt1FqcnesogjkX6OCeRQdyh+iPRWxN7odm9u//3Tj1TBfv/coWcnCwoRBCX1oHQ62wAgJsd6jfZiSHyaKEHSaK83jMihT2KJo5hxq7BGt8B6+U=,iv:0/nfz3CWp1FtV/mSk1Pe2dvdhjFXWm9O9tJdLzPjXtE=,tag:xY3hPICZKLNh34PMaaG5uw==,type:str]
    pgp:
        - created_at: "2026-09-09T10:45:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//QalYvZA8w3RjQVSwAJq27fJWTeqrOPPGoEgWDilow9jL
            2UPgJRyR4X9UDBZ6IxD52dDi5jtQDvY3ofq0zm8lp7Y+qLs21kkH7y0C7pEyjd44
            4oLRRMHQkBWDY8qLTsVLDSO28HBC73n8NfvlfFZazun4kWvZgBHxQ5sxiZT57mJI
            pbR8+TLvhs8zmjz6RtcinYiuR/2lpsVNSaP8EsDtHN2ZonyATV4PoGP4hLy4v0MH
            8z4O1/Vol994NtJIdJS/BPbzpLkixiizCISrZNQGG5WOVc4luMW8PMgIKNt1bsb3
            2W9f2XOgRn1Zu43l5Mkul3//5AzFuxy6ap8nNSxRwDYuaQyn+V4jZqKA3BB9Vy7s
            x5QWeFLh1l4nKPFHLeai3hpUlFGvRCb4Ncg6Izect+Xp3eszDzuBSdF4o6ldyz+r
            2JVUfPXAg9Wgx9n5y7XlK4djVl2BnC2JFGXw75nHQS+up1KZVajQBEfpl5OtKs0n
            bUggkj3TfvXgbNVuoltKwJZxUwxSLhGVyYGW1yQGkCC3RYZ/fD9vX5RTetq/tGyV
            nmTTTHkS/GpxqNxbDLrFEkQjVSLLGWN37e5S4LstAcAf9YbZOuFsLTk/Yoqczvp/
            kagsDpPetR0pmR0/ahockjXNEPjdzUFICCqVDQfl8KzJAzivNaAnDFo5FGMLQDjU
            aAEJAhAXhCVQu0StCa2ruLCNH5ZvfZ7LpLTU4vHPfwUO7fmufa46G61jnLfSieNL
            RrcNQHsbLdBk534dYtFo/XUDnSmvXQAqem16m71HkQehp7zJ62pQ+Zym74pTfn1l
            PmeuNpaWR7aG
            =bQ72
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lore-config
    namespace: lore
type: Opaque
stringData:
    LORE__ENCRYPTION_KEY: ENC[AES256_GCM,data:rc2EUZN5kKJp3E0aNIvjjl8Ja5PHsksLqX6kLTvIli0=,iv:Lgg4TrzBo1bCtodo569zAFfmz4Z1ifShJiTEGRHR2jA=,tag:UGaEj0N/lkLGOYeNhkgwXw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-09T10:45:36Z"
    mac: ENC[AES256_GCM,data:YfXSdM4z4F032zRXvKcuxzd4i4FaLEkOBbH/ShEw29Wglh2G9PgmKPIptXe3RHt1FqcnesogjkX6OCeRQdyh+iPRWxN7odm9u//3Tj1TBfv/coWcnCwoRBCX1oHQ62wAgJsd6jfZiSHyaKEHSaK83jMihT2KJo5hxq7BGt8B6+U=,iv:0/nfz3CWp1FtV/mSk1Pe2dvdhjFXWm9O9tJdLzPjXtE=,tag:xY3hPICZKLNh34PMaaG5uw==,type:str]
    pgp:
        - created_at: "2026-09-09T10:45:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//QalYvZA8w3RjQVSwAJq27fJWTeqrOPPGoEgWDilow9jL
            2UPgJRyR4X9UDBZ6IxD52dDi5jtQDvY3ofq0zm8lp7Y+qLs21kkH7y0C7pEyjd44
            4oLRRMHQkBWDY8qLTsVLDSO28HBC73n8NfvlfFZazun4kWvZgBHxQ5sxiZT57mJI
            pbR8+TLvhs8zmjz6RtcinYiuR/2lpsVNSaP8EsDtHN2ZonyATV4PoGP4hLy4v0MH
            8z4O1/Vol994NtJIdJS/BPbzpLkixiizCISrZNQGG5WOVc4luMW8PMgIKNt1bsb3
            2W9f2XOgRn1Zu43l5Mkul3//5AzFuxy6ap8nNSxRwDYuaQyn+V4jZqKA3BB9Vy7s
            x5QWeFLh1l4nKPFHLeai3hpUlFGvRCb4Ncg6Izect+Xp3eszDzuBSdF4o6ldyz+r
            2JVUfPXAg9Wgx9n5y7XlK4djVl2BnC2JFGXw75nHQS+up1KZVajQBEfpl5OtKs0n
            bUggkj3TfvXgbNVuoltKwJZxUwxSLhGVyYGW1yQGkCC3RYZ/fD9vX5RTetq/tGyV
            nmTTTHkS/GpxqNxbDLrFEkQjVSLLGWN37e5S4LstAcAf9YbZOuFsLTk/Yoqczvp/
            kagsDpPetR0pmR0/ahockjXNEPjdzUFICCqVDQfl8KzJAzivNaAnDFo5FGMLQDjU
            aAEJAhAXhCVQu0StCa2ruLCNH5ZvfZ7LpLTU4vHPfwUO7fmufa46G61jnLfSieNL
            RrcNQHsbLdBk534dYtFo/XUDnSmvXQAqem16m71HkQehp7zJ62pQ+Zym74pTfn1l
            PmeuNpaWR7aG
            =bQ72
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
