apiVersion: v1
kind: Secret
metadata:
    name: lore-oidc
    namespace: lore
type: Opaque
stringData:
    LORE__OIDC_ISSUER: ENC[AES256_GCM,data:81AMKBVEpM9GqbfzmJOLcePcEE/eFgKScijmnKZtdj4a4Ygx,iv:YlF/pE1UmO5COWrJ2MtQTVcUrr86t7snXj37IaiTbso=,tag:DZK5PcVPBgjJiBwzTRAODA==,type:str]
    LORE__OIDC_CLIENT_ID: ENC[AES256_GCM,data:8qvN4w==,iv:eKzsbCer2EaSFbRAsmr/lt93bQYU7vHmJ440VFtUnSs=,tag:37jAumYiudrXcUFZRBMyTQ==,type:str]
    LORE__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:my3lx+PIaMw6xq/ULbl+S4KVOG7yWvq97jE4edmx6XIIVmlmvQn/yB6YiUZw8wYD05Zoe5WZg2OTcV9cVYvf/gjtZ3xpONlt8ohXThMSRuyXkLJYPoQ=,iv:8aa7lKjJydzK/1Xgfco9GKbsR939bw2LUXmHtiWrM5U=,tag:3JHeyYOcE2DuGLvEefWUtw==,type:str]
    LORE__OIDC_SESSION_SECRET: ENC[AES256_GCM,data:tduG3cDoNIZhEebsWyHjo3c9B/kYez8qkJHBANLSLLQ=,iv:M/b/9Wsp5DnWBozYzfuQ1YbyViipdCtCKfI0Y0BoSvc=,tag:U3BqTeSSKO+mXyvj4Le6jQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-09T13:01:38Z"
    mac: ENC[AES256_GCM,data:7CO2ApeZpMNnJm7ojaBNTzdQrJgzUxEEU9OzTlkzyH7HPNbaN2ElS/seoCAxv/+W+DgU6twhEiiREJUECX9v6k5LZkfpZJmythk3kE6D7ekuk0bIRQ8xFD1TlB7oVK57hOq04Lflki+CKC7RYxVs+a5nOjqggFKNZrKVllIrb9s=,iv:eiCRhQCICDL3jE22sb+/EOOOn0QtoJo4XFIVqbvVekk=,tag:7X+eiIeyaWCWrYuYxhNSkA==,type:str]
    pgp:
        - created_at: "2026-09-09T13:01:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+JK9JYZyEQj+ZCmkBGwVt65LXe0v3LPCWKiv7HmAEB/I9
            0/pQMG/Z2E9xM60f3Sat5zDxFkypTJJWCGXdBxeWxtD1VKamHyQeISeYq6peAsNv
            Nz5IfGlATvt9qYjpfFZsIIuOuPhNs2NMMqiAhWJ4wKHSDvbYkpIJGth2dhRdpclQ
            c7DgtTmAGRC6Zu3su/cVbSKpJlhCiheblpJ9QDzZXEZL6E7qFzeHKGnD2p07h5yv
            eSq0qgtGx307c5DNNZ15UgrTkQUs2yvIiv9XFW2apo6b9yf6+wLT+Yv5cs5MxhD+
            9JHRpDxpoLIfMIWx7zBUpFap/u5DP9x/Nhi65aZCSdif0rmWFdrIgueBdEg2NgNV
            IJvtZqbnTrU80a3niVEE+FI2FTgLjKW05UVAv6Y3+fXqYSh1JkWH8t5ON86Z8sPA
            Znh50N3jJenIWU4WTHuWxjSYKourxy2mjeP3HvpWJfuIAJtokeYACQjXQoAf1W9o
            tGE4ebqglPi659aZFXh9gASFsG7l1HKWHw9IJHpEGdf1ekRf8cCBiDCsjyqbOB8t
            Fz7HK5sIjrLnC+e/mKHvg28Vdb+9jlb+2NcUiElmIClei/5g69kxQp5mE/9wz7aQ
            Fi8c6ZPk8JJsS+o2ndmuPEDwkZOBzC2cOkbzQVddNQXTM666+DYlcpltGRbHeKHU
            ZgEJAhDmvqxpLtPptIvACpOsQ6ZLQ6j/0ocYKJNoMp96IwEinCf+ui/fmgmHXoEq
            uqCfXNFnefF2P3MKJB/xEDxCC/YHwZSXhiUwnI8pl+uF3NnUCmSMISoluTX52FV5
            kOfVrn7grQ==
            =sjf/
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lore-config
    namespace: lore
type: Opaque
stringData:
    LORE__ENCRYPTION_KEY: ENC[AES256_GCM,data:r7+wune/un1rGKYzptik0CabZY730JZZkSATnb14U/5CdUhN5mP+gir+rz0=,iv:7nfkGbR8DTWZGiPmJslV+0yw6vWeP54gEd0oO+1m5zs=,tag:cZAdMOsnYa4T1L21xopoMw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-09T13:01:38Z"
    mac: ENC[AES256_GCM,data:7CO2ApeZpMNnJm7ojaBNTzdQrJgzUxEEU9OzTlkzyH7HPNbaN2ElS/seoCAxv/+W+DgU6twhEiiREJUECX9v6k5LZkfpZJmythk3kE6D7ekuk0bIRQ8xFD1TlB7oVK57hOq04Lflki+CKC7RYxVs+a5nOjqggFKNZrKVllIrb9s=,iv:eiCRhQCICDL3jE22sb+/EOOOn0QtoJo4XFIVqbvVekk=,tag:7X+eiIeyaWCWrYuYxhNSkA==,type:str]
    pgp:
        - created_at: "2026-09-09T13:01:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/+JK9JYZyEQj+ZCmkBGwVt65LXe0v3LPCWKiv7HmAEB/I9
            0/pQMG/Z2E9xM60f3Sat5zDxFkypTJJWCGXdBxeWxtD1VKamHyQeISeYq6peAsNv
            Nz5IfGlATvt9qYjpfFZsIIuOuPhNs2NMMqiAhWJ4wKHSDvbYkpIJGth2dhRdpclQ
            c7DgtTmAGRC6Zu3su/cVbSKpJlhCiheblpJ9QDzZXEZL6E7qFzeHKGnD2p07h5yv
            eSq0qgtGx307c5DNNZ15UgrTkQUs2yvIiv9XFW2apo6b9yf6+wLT+Yv5cs5MxhD+
            9JHRpDxpoLIfMIWx7zBUpFap/u5DP9x/Nhi65aZCSdif0rmWFdrIgueBdEg2NgNV
            IJvtZqbnTrU80a3niVEE+FI2FTgLjKW05UVAv6Y3+fXqYSh1JkWH8t5ON86Z8sPA
            Znh50N3jJenIWU4WTHuWxjSYKourxy2mjeP3HvpWJfuIAJtokeYACQjXQoAf1W9o
            tGE4ebqglPi659aZFXh9gASFsG7l1HKWHw9IJHpEGdf1ekRf8cCBiDCsjyqbOB8t
            Fz7HK5sIjrLnC+e/mKHvg28Vdb+9jlb+2NcUiElmIClei/5g69kxQp5mE/9wz7aQ
            Fi8c6ZPk8JJsS+o2ndmuPEDwkZOBzC2cOkbzQVddNQXTM666+DYlcpltGRbHeKHU
            ZgEJAhDmvqxpLtPptIvACpOsQ6ZLQ6j/0ocYKJNoMp96IwEinCf+ui/fmgmHXoEq
            uqCfXNFnefF2P3MKJB/xEDxCC/YHwZSXhiUwnI8pl+uF3NnUCmSMISoluTX52FV5
            kOfVrn7grQ==
            =sjf/
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
