apiVersion: v1
kind: Secret
metadata:
  name: lore
  namespace: lore
type: Opaque
stringData:
  LORE__OIDC_ISSUER: ENC[AES256_GCM,data:QmA6Wzr3dNK8fWW7W2tCInkNcwfgwQRSyc4/B3lqNJ/qskni,iv:eNaiiG6UU4WNUHunl9SFNwc7nW9k0eqLI2hvkAmcXM8=,tag:D2X/hiQcjmCgKUjzai2g3w==,type:str]
  LORE__OIDC_CLIENT_ID: ENC[AES256_GCM,data:1/omWA==,iv:PbxUQkatAlVpAyfrcwMyO1I2bUjrmo+pN77I5EQY4y4=,tag:ZCQtOBSniAJb79+4aEuGOA==,type:str]
  LORE__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:4N8rd64Gz7RHm6m7hMBWbgrGB55lSBhK0TyZk5T/zEHsW54qKiMprO5MmhT7T8oqRhu6npgt/UeP8B3876Xdikb/bfZQ8AfyH2kPdTR2Pg3LOOaBSr8=,iv:bjEXC0vbSv/pBsHbjKr/8h7QVqZftL41Cg3j9Xq4qgI=,tag:AWeMOKxei/cyYD4n4LzeZw==,type:str]
  LORE__SESSION_SECRET: ENC[AES256_GCM,data:kiaXg+nf2uvUZh1NYucMVkYlL9x5tbaOOLlmkJaGX5E=,iv:a6AXpoI0TmxZ+EiKaMRm59gemrxkVe5CJRgA+jYV7xQ=,tag:dtdWIf81T7fPOJnMXctDPA==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-09-04T15:01:35Z"
  mac: ENC[AES256_GCM,data:dyx+aUPypyRz3mXaV5Hc1JDb6usfrT8/FMsfYeKNVwY1unWsPlPacTWx8gwuGfLd3qHGh+nVA4+avmVRg7NiyzWcsVhwxprgLN/wBunqn4IUoHyHKKq95KJ6iEoej7HRkf4hkSyAIpZFjJ1I8HzB0tgxh++OWQy7oHlBXgMuuM8=,iv:nri8jISCZ0pIw7pperv6YKdqCjX2RZUJSnlcM7wgw2Y=,tag:ybXR27cfAVRnFNO4AOjZQg==,type:str]
  pgp:
    - created_at: "2026-09-04T15:01:35Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAAmsu484aSjTQKIxkw1fV4LD5ftpt2CHRZkEvXQIjC9vZo
        0m/F2+v9yCFmNPLbb+WOLtbSIjQqVMNQD/am3RbbtWRB2Qt7peMrplh94I6GUwXQ
        akXExBfOsGv7Rkl3u8EmszISn3Ksv8t4ogaBqnAS1jyBmGuSUjmV0BAGtSEylcdA
        SV3sAkWp9vG5YQg4g2IrYARORLeRXNzzOHzP9j9Y6wOsSR/MYqATlhDB11t8Q5al
        L17Ly+53acNZ6JujMZWaCZIhOuDGZhYL79gSSXwzQ1YFq5vj5GBNBh0xOW0ZiTHp
        sn2c/uwd1vSZNfw6qEMr870dFsWvt37BPOVTQ2THLZSme4j0fQolsjnD9o/IBKrI
        80UmeFHDClATi3h1cV1PNe63+TfbetVE2+OItzKgDnywgG2pr6GpUlj/doM8M3Jk
        9FSh5Bfh0yk1d2wt1eFrRsporW96n3Sa9PWRaG1PYdQT404hEsDmVikVY//oefv1
        dY2L9f5g9BkBe+XxtYB3dn1vxiz/QCjEcmSFm4gmJ5HItVD0hyYOxZKkwrAUIQAN
        KDDXsM+boOcyM7oC/BhA6QY/vbRKxJDeRBKjmbLgBfh9YPdYbjaePCRshOQQCXNI
        PmgiaxcEgikrxuHa8R73J9bGCqh1CA5eI/rjgEwXVz8Q80NieMETs6UqpKDHLb7U
        aAEJAhA2By2nILsmNQr8EoHLI0+MHf45zJlwsX00fei3PIKORyMrKWJtFKyVe1hm
        FXI52xVIpnHfPpWSmIlHNHfpsbiq8X1g0rneOrLu1GYU1SgfpJM8S+BNN4Xins4l
        Nq3H+xD2WzkP
        =yOQt
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.3
