apiVersion: v1
kind: Secret
metadata:
    name: db-backup
    namespace: kumbuka
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:6aGATHOcEg==,iv:30K0BPCeQ6NWnhBJp+gMsCPFh1NYGV208SdtOPhNYAk=,tag:AUl0vf1ep2M8rieC7sHniw==,type:str]
    secretKey: ENC[AES256_GCM,data:XZDB5p+N7nhsylk15pXaHn793LqqhqLh9pB9wN0VJL7rf9MlXKIn7A==,iv:lFU0e2/UdBpotrNKoNN1by7Z5e0BL3zHHRlwC7sYS1g=,tag:ng8L/e6leIgK3r9s89Mmtw==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-16T13:02:16Z"
    mac: ENC[AES256_GCM,data:A/Myd/IzO4ZORHwfla+n2GIpmMChrHX7VT6xnnv2wv7uU1gklAKcdKj3qJLTgPoq+yrWuHbaF8tC3a3cWlvu2q81YNTUJtWbUeZbk8mnhFjunK88SQEDcdJcYtk8fUCMk6YwIT/VCeevh2jwv4PKcyi0LgK53hE7Zw4Hg2cxCzE=,iv:xyI6ZpPK/TAyQG9dLHQ1mVbAgMNLEcHaq9hC7B82kxU=,tag:C29B9S0oyeulghIVyGF7yA==,type:str]
    pgp:
        - created_at: "2026-09-16T13:02:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArLLRKbiJi51KKTcbcsSQ0bnzVGQ+fVSbsJ+jWjO06YwE
            KjAi74C5nBRZNBt8Ze33DEZ70iezDbEoJd2XQvhn7CCwh9+xVG36VCximK8jZx4o
            2DQxOFT79jJC6YnpVvYqt62x+oJ00Qh/M/BowvF8oiClHSvHHm6+83/Nqnjgjy1+
            RwNcSBnIZn+EWVkHKV4noR5PJ+g7xDGXkiY+L8bjv4+HXHYCTT4mDwt+DCMWWfX2
            OuG2dDjHyeich8uCFLhvKH3LtPfPbggaA4N0rIGAIFLzaypq6I7Y401zmefv16os
            xNvYKrUQbn91cs85Wb9HSxsDaZqiumL5YkDKaDyoI1gQtFTaaNCRA9d7ZmhxYjk1
            u5pzsYz8+6bjboFCJr9I/4gx1ydp1LUR1T7j1A1SCynkgg9iM7SRmspxu0KQWn4O
            +9RZ55lC1zk4ipehJZhkCg5QPL0fG5ECHNkUlOQke9q7fvB1LyVS9O2NCZr+gci8
            jVY9wZyrGSj1apgPkVJcVmVLVNokQEPfRQTyeeYcFoHjgfrdBWji8oYioFzbR82m
            P32WAjHsSxTN5DHG/Drg9Dz8mWaCI3roffxZMhTDQwqZVtC6G8xcdubaLTOqjDIk
            Do9rvBoRUJjBPOTyOJ0E4NiDRpeMild37ngekznFkbQw1rNUulVjCloJCwkW7+7U
            ZgEJAhDEUrBTMXndLPzSzsio5CytA4B2S1NadtVC1n6Sk8OkVpEESpb+O/eMjMmb
            lbg649A+kexuZnkrx4tQi193t1Fi1lomukq7AmX4uoAWJ41jQYKx5c8MCCOH1nEl
            7oaDVtptLg==
            =shzw
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
