apiVersion: v1
kind: Secret
metadata:
    name: ${BASE_DOMAIN/./-}-family-sso-client-secret
    namespace: media
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:P1SWjs9jW1Xh9iGl5vmLRC4aQSAReOjJPtw6+8vQgrkML0R6w3lxYd9P+Z22vTDLsFuCvMVVjUT2K+Y1P3oEkhkxBgyhmSiFsLaK24vNFg+YghD3VNg=,iv:G/ycag5CQJUw8SgtSPh69R95PJhU8xE+CFsHlWSuRPY=,tag:VhtenMG8Ln/ccpSF/JN4FA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-08-20T12:04:54Z"
    mac: ENC[AES256_GCM,data:aQZwPQIoYC1v7YKaqV3TTfccseiL7KGRICDt6itiEy1xxJVs8tHf+k7dEpQvX1Bv2YNk4tsN//kZbMWfZAsn50uSAFB7GuS5CkJLUyvz+5F3urjpVnH7RcSNAEiVNwtBR3mOELZrp9W+DSiL/ZGiDoXAerwxIdRV/D5CVEG+vWo=,iv:6iehYbQMl43zZExG3HIDywc0jlys59T7YUttfw3Sf6E=,tag:FkNqs5zfbvD9j+kP0CUJGA==,type:str]
    pgp:
        - created_at: "2026-08-20T12:04:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAzXywNY2TJbyMHIyYBNi0SDHoF9amtVItaO4+Gea6oijc
            dQA2wARaqZit5dWoVa0F289X06gPIWVtKAxlLLF7nZQeYjE+DoaCUoqAVvXfFSXg
            ZSnfqXRdlgh8hUtxwbPzQ2elkeTrcrS6xNfLCvi8PglBYTGpRtWjSyBKhhHGIY4m
            oTyX/LeErbMvfv6VFp/mSo/cGW7mYRoJGw5+nXCyhF4+AQ9gHOc0berX2IPYlvHl
            ve94tyQ1WirYwwhqkfdEFYv3jIkPRgcPlLA4lLVlqrDO1fQL1ZMDgJBmYU6ARTp3
            VlavxLfzcpFuMgRY+cx5bu0okpN85yt+n9yEb7PAR2hvWWrWLLeqIRxtEWTMMoO9
            59j06wD7xzCPcGycbnmxAocMXeh17vKbqhpyGV5GIqHr0wif4Q3eoX03OopIdiDi
            V5UXGP5L/bqy48ZOCKvboksTby1Bpfx/p8RLOcS7wJZAD6X6W0vkpnfiBnlsMC9s
            FcQFxDQY/yazt4Hac8lnc8WGMzxINqCmpxR1qJhWd4zwUWOEa+R5CwNPmdapyG9k
            +no3aGrWoOCIFwSnkmabWi2DWn2ha/fXEVOUBhGo71/j4MWCkG8D0gY39y9Rw8mO
            vG/J1LZIENmSvJ/9BEoB1Ve29jR8jjHoipRfMu1+qgZ3UspQyrObPugq+sZ7aTbU
            ZgEJAhD1PolFfvyV3BUNR9VIIr5kaXCPWu8u9MNXXZlsluKI7xRNqUq/PVcSDTR9
            prHLvfJ24tr2m0NiJ4ybae4eHjMUmBW5Zuba3UWYeCOuIW6YaGaDpogdmwdunNax
            61+8XWFsmw==
            =H3gZ
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
