---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html2pdf
  namespace: lore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: html2pdf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: html2pdf
    spec:
      containers:
        - name: html2pdf
          image: ghcr.io/gi8lino/html2pdf:v0.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
