---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: garage-webui
      app.kubernetes.io/component: webui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: garage-webui
        app.kubernetes.io/component: webui
    spec:
      restartPolicy: Always
      containers:
        - name: garage-webui
          image: khairul169/garage-webui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_BASE_URL
              value: http://garage-admin.gitlab.svc.cluster.local:3903
            - name: API_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: gitlab-garage-admin
                  key: adminToken
            - name: S3_ENDPOINT
              value: http://gitlab-garage.gitlab.svc.cluster.local:3900
          ports:
            - name: http
              containerPort: 3909
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /etc/garage.toml
              subPath: garage.toml
      automountServiceAccountToken: false
      volumes:
        - name: config
          configMap:
            name: gitlab-garage-config
