apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${BASE_DOMAIN/./-}-sso-client-secret
  namespace: observability
stringData:
  client-secret: ENC[AES256_GCM,data:TiSgePlyJDmAuuaDbuscKr30wt/muRaBf94TxD8bJBM=,iv:T7uJQqbdAjFKRFDh7gqSX5cfOq5e6KGfHvqVe+vGwhU=,tag:6Np+zV2+qQh5oa6rIUbDtQ==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:33:43Z"
  mac: ENC[AES256_GCM,data:Z/ABaV3nySmNx+Z8aku/r5LEosGXd2PWyXJmDmvphCEdrL8/HZPvYoUNt7Xd2HKY8202ozPzvXDSrmPInGhsGQkuYokAh2yb0ydP3+AywWIbwBa7TOgfOLnd42jjPXpUrNovZu3TznSV70YCvvEGu5pm1FhsWe6on3TgzI107bA=,iv:yNpidq6F5w3+n7blexeKGJzuphCI5ffUKXzo/m973gQ=,tag:CviX7/AboEtpcjgRv3A+fA==,type:str]
  pgp:
    - created_at: "2026-06-29T15:33:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVARAAzVsHF4yuMa/vdEGgMT6VAjF5oaFOrxUohZcHeVCEU3Q+
        C4TuE99d8BoSlvk/BG0Atc3NXaIuLYFuXoMnus9LniDmtCISwVsCTO2QEctkM1Op
        iyvw19ZFAnyJPLvy0pF1pESzutvPQrJYL20fpxAGlyFJxAa7o6fhsg+m0J6rvzRK
        oEVbgZBUrCaw0lTcfkNd13OgaIR8WeUuuiQYvqBATiuPR/kGmpk2rwPGX/ul46w8
        Z1sAVID0tgWXCV/Pi/DTGA9Dwd1UdiSBqGwGxrf4WxFkE1LdW3HQ2ykutPm+ZEvu
        hiogSUzRYT0quXdVRdrhGIJDfVDd1aB23Q30nWTDGj+j0+bqbAVlRM6HmTHQf0cL
        SAW8Ftg5A+A8ALCZhpD0Wkf320F20VgWci7h+bF3op5AqYLYkzXVm4wrw8KXlXRB
        IuTrZj11Xn/wslQGTPjFUeegMqBBEfGrcGb4O+KB620HahWmouEAto3UZq5I8gHG
        ZW3BNkO5/9SwGpYSAD88Q7pQRX1gL99Xc4Ubzmtj0TLBWWSOC+VSkoG71IaOKGxn
        FkxBAYOJavsZMI2Dik4MDWj8//i7AnLZ8+f+4S3UGtV47ElPE8bxkc827J31Z/W+
        8DzAAk63mfI9WYsZJQ0fyaaP9auEimqeObI8r3LxdU1sSasDaNIfxYDZtesCrJfU
        aAEJAhCaoEi2I+PGbXqetg76b9sTk0Jz+nb3eGkWLtpynErJeSqkGosqi+6oSYSk
        bk3tAmpPkxIIRgvoA3Tb3xc5TUsAj2tXHi5wVB7SbBMjiwn9tnWO4Tldz6uhXAxN
        AbkxNEEs2KLc
        =Ivmf
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
