apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: nearly-pro-sso-client-secret
    namespace: observability
stringData:
    client-secret: ENC[AES256_GCM,data:4EzRWPcVdrMUK7zYDlISXv07VyvuMpAIiPDJVfF9R4E=,iv:tO//O/nTUbxx1jKtDZ9yQGZl3Fxx9O56RaCWYmk/854=,tag:c4kXSV9Zn9X0mMOT2KcCBg==,type:str]
sops:
    lastmodified: "2026-03-30T11:55:29Z"
    mac: ENC[AES256_GCM,data:LivbvGMRMqiowCoNNQW2UPJu75xs5Bz6b4HtktHtNyxzIinli1YX+9KQXde6tSzgN5pIkoYVM/7Dic/7EOSy+N2M0lM/VISqOHrzYdqGx+4WQFPqFPuC4wbpl7Wh7xLnUQlLxLYXJpezVRMYjnX7QTiUn3cBh647FnIJDkU4ZXo=,iv:PiWrHId9w4sl8RKUlVlSgD2tQCLCL2KiNmXj+wfpJP4=,tag:DtyzO35co1eUwcdOYaFY7A==,type:str]
    pgp:
        - created_at: "2026-03-30T11:55:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAApqLadgTJ5yNlfUCil7alo3DyC/kLlWHapzguLTTBt4a3
            Xmq9y/pWXH4oWZ2F1DrKFTZKbGIDrpmEBlHfrZ14I+ydeRlaRUtbsEl+QwZRkEic
            ujN4Lj4VXxb+TPzlw/TPZ2a58JxqRo57q63FOjpFHqGq6KY9xEABTSdQywLDT3Jh
            a7Ep6pO1Y46Z3BmR4wXoNIt8on62lSMsPWO9PGHietebptvyHmzXFD9ZUVPC6U3L
            7PkzmYp/8/nXZz68X0S9Gzt4sUOSEaluO9liYOe8NJZufI6BtWNuZPA1Ov2sDqHd
            VdjcgHuej7QZWhUyvarG/exaRQwFMPggb2XNxT4DHEpQIja/tbJtvFz/CFF2BRoW
            QuviU+QNrbTXerRGljnuzmVaAURyfxU0iOvYzJKFawujkrKGcbAGmD1vQYwOn5z5
            tTpil4zdvHd4/3MDyz4oPsriFkF/aDu8DMKBf8sOJhNI6P6SMEWuGhxjUU31SrY7
            hU+5GrZT11yBgn9EMVsGen2ZyQYP41mhxoovCmkY/gcnhWyOlbC5lWloODWTuT8q
            9RaBg9JX0LXSGG/SvZv+YEsXl25i/X3neh3ZjRQVT40aJueNXej+HM5R+ODCoiqp
            TDOKV3SZgzriIMaKYgOBTJ3bZeMT7Jacst4oDUNVfzQqxt8J0rnDve+PKcpSEeDU
            aAEJAhDB2cs2javiZDOdhiCJjUrb13ds4a0H3Y5yGw50BTVWKw6W3gHGCTF2yTsl
            4Tn4GpQ/z+OSdgFt8OCCQWhs8xxfbsq/GbJORONQ/noc4BgTm4MMlu5T7fQz/L7u
            wrNnJKLIVd+z
            =k+do
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
