---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github
  namespace: flux-system
spec:
  providerRef:
    name: github
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: apps
    - kind: Kustomization
      name: cluster
    - kind: Kustomization
      name: crds
    - kind: Kustomization
      name: flux-runtime
    - kind: Kustomization
      name: infra
    - kind: Kustomization
      name: networkpolicies
  exclusionList:
    - InternalError.*failed to call webhook.*EOF
  suspend: false
