apiVersion: v1
kind: Secret
metadata:
  name: ${BASE_DOMAIN/./-}-sso-client-secret
  namespace: media
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:jytOFSlrLD3HoKgOqOpe+smFBJeCF43DA+So0x36Mko=,iv:1gzo/rK11uAGkDxey6Zi6F3/qXFLzw+jdhmamPdecfU=,tag:2a5Rhk4kRB8obi6qzh0gWw==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:30:27Z"
  mac: ENC[AES256_GCM,data:Z2Wp9a6Md+bK67k53hTUw6SyhvYceR2ReVyu4V9qJzn9XOuidE6dwY5Ik7mVo3qwpItMYJEBs+TC/cCOBE13o411i3qXPUFzuOTdu2NLouY4WHbH9wxsXMkMyPh6Fhl+GTHR1Q2poOxkVquJdIMOt8oUun5LTLFHTWjj1Yk2Z6E=,iv:UExcaEQrX/70xE9Kkpk7ZkBsYz2ed/epH4WoktXjLNk=,tag:gwpHpE1/PUJFeoLXGcALBg==,type:str]
  pgp:
    - created_at: "2026-06-29T15:30:27Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ//fpPFLT/4mHPkrOxn5CITpTJtydzGIoU5tF13uxmfgQ/i
        zNPsebUVfNHQfPEipk88Y/boxnNKKK6zB5MilX4yq5CJY0qlK6wTHynTmJUC/bSl
        k5AmGylvsq5iKTPYGSUdYY434ESkewvni2oZORKs8WPtGSX/z0gf7Rf9wQF9VLA2
        OD91qCETVDAaBsln2Pf9lstcXLF7X1Ogr1XErwgVJ8onCLsr2FU4cZs5oPXsuLOW
        sMpb6LqopW3K00fY3aizbw76IzMZdf7ARpW7aR8RlYQQGBK8aas9s17pItgJE3rv
        2B39akIgbNpJIbYfhuEsmwn6s0gDuRFnj1/ZE/0MipcSw8ituZHYUc7n4tsM1sDy
        dkSdJl9b0IclGNvO56j41EDXayjSgag7dFbVi3/xGFSnQWDOvSdli3WFH0cPlFUk
        yTjBDewX8QHIx360HHtMXN4pfPw56ZjrMy5tbQpd4bc3449aSZnkjq6MhdbQphRN
        g6tWEJDEd2TvkbPTbQo4C6GawRw1Gdy/PKT8zhJqYC1dDwp4twP1bqCVcxUDRFsY
        0fT+MIztvaDi7Pt5EgHiVkFhDF+HlFzJxHHTbEvsolElQwfT1awj5ertz+8pz9BH
        gBX+d3wYUlHGdJy2sc42Q6cBnsQJvVvjnC/CqmSbSIW6LOS1pS9lDu4w8UQC1kvU
        aAEJAhC5XlBsJWqnCur0FJdz8ftU2D2M5BvGnqy07d/Z0zsJYK9QmPOLslEXZq9u
        OM8N81nitx50bdqxxBfd+4TqhAh024zL35munG8pW91MGY1YhloWEWqNDmMN2GzM
        Wh7qJwBfPmZU
        =yNqa
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
