apiVersion: v1
kind: Secret
metadata:
    name: ${BASE_DOMAIN/./-}-sso-client-secret
    namespace: media
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:hQSExgKUm/Ds9zddrBGHVzuhX/q4VA4gXaSc+7Ht3aBb4IC7HmqJwVzdwG4mRoWHAmIoerctAwqElKleDXqUx8g9dCJOu8ioc6PIsYsCZ5ZF03qmtLY=,iv:jC5B3C2c9f9sQMNkCAFwslOF3zLit+vWxRY094QZDrU=,tag:mf+ZKbql0nMKYXS+FVc+Qg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-01T10:36:39Z"
    mac: ENC[AES256_GCM,data:FOn34Wjg894GGGVypd07VP+Rv55buaomSl17hqKjlJDOZB43hZY5Mo/Z4nOft3BV6vUGINTev//AoWKDN/6xsqocrEajC3kDFxmgo49KGQE/EoRqeGX88zM1D95Q0PkPaSfEAtnHUFGVgHgeJl/TwTbPx6V3+wDCUT4GR75hGx8=,iv:3ZlOFUZZ+2osQaUcWgRl0agG/LYzHSYNMv4k9v3VNiU=,tag:s8AV9PQ+UaV12BWmmEJrLA==,type:str]
    pgp:
        - created_at: "2026-09-01T10:36:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/8C747Jq3ZjeRD4XjG5rbKyKSQQPrSqUvS60TQ9RshWfd9
            853/1oYj8SqgrqM3TFOxPtb5yiTwmcXhwyYkiavoo0b7H/p6nhen2wgoZL73GMrj
            Vd7ndZKWioPscoF4iEl7B4iu2pdyCbrxPm/ZbP5EQ/BAFCM5aO9667ltvv/QTzCD
            ez8o0eIs6MLDEazV7QX1glcgq4gLYlnYIscf+D11sdBFuiQk15797BYZdw3t+0kj
            /2LYuTPAMBltuo2wXjnfDYxOosm3ruFq+vpTYibvlOMfjxtYuxYrijJDN2dmIFLe
            uN+s40vPTTEzCv036W7cQ6Cb1/KsU8TszPUwt0sdwsKUg75rlsaXYuikpsjisuqW
            lB8a7GFtpH02voOhAu/otRoEUXE4N7vhPll2bv2C0qzxMUMWlLkS3a9CO7VQSEQP
            qVUpqYwgeHcU1i8ZeadzHqoXtjO94du2q9Jh/jXzq+fM8J2z/TjI62Pp/DbDwHyP
            RfILAGotoifJ3eCkKO5Gk/2zUmZUqK0Knd1qLQpW4vUWLGmA3JJZn/utRfRZcIIV
            pty/mZZ+lrcTzQbeJXW8pt1kVZohsmuQO1X13YPdAbD2o+EIy9obGz/y8OFxSAG+
            THCHp2hjPQ5Y0CVd9AErQdS5s1iUD5MDpVFqFGYGLNtCr/3iIHmPz/PuUaan6v7U
            aAEJAhBTLPh3C+E8rzG1vOJCzdkHWzvy1yuUSjLRlVA6mkGwxdwk3RZkhVtTdSxO
            /e9G+2g49QviznE72zZ7NP01FhWRd4d3Twpw3Bb1Apn9ZBCTGMpDAZelXbao6LDq
            7OskTcIHcgoE
            =GGo5
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
