apiVersion: v1
kind: Secret
metadata:
    name: k8up-helm-values
    namespace: k8up
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:zSC+ukUW4NsxazDKqN4ytOxsuzQWbJHHO27DB7ZxT42JmY9KnhW7In9sG3yJaLyPJ4HNPXQCfMeCAxVsdMyozKaIsOBg8bEp4BDWS0DUJZu/ZLVU5Mz9E6VwKmFmzH+/N+oJWCsN9HtyCVax2ra2aVI+kaoEBZamI1BqoL+f+vWZaFZ/PMwKioreHZTjWG+S7V7hVP8K7UhrCVbHeDXUIKqFQM4rohFifdvay4gjQ7KhSl6RpxjTL/4kIDUFhZohTKUTYHt307UWPYoRqRfL2BUW0rCYzy8FGb+153saVnKqKZwkrYkFmnmKA03w/LcJptD15Skx/faEyyt7ivL2DZPvGmWNRjv2TPi2EKfqVlx6zKZLfzQD2hnP5Z9RgTQJ6KqNowqxLW9ejld6fBoSyyobFgO+E/hSJaIHiZCZV6wvkV556rL8w2WcSAb4qsmDSqN0dkpzoBS63kWphS3sm6O4ssZ6dBRlbtF7EFIZ8ZEW4U8wAvZ2ZGEy32VTZpUkyLtA8qa0H5+HShR7khP2nO2liK2Lz+qoIBDGsg2+eGAK89kzBUUApPBet/UhAYvxQd3fI/3SuZA=,iv:rU0XLyptNN7/tZrScQfKag+z8Bl8XOqnoVL4J456Oe4=,tag:GSTcv8Tm2OO4MpoQvcfaYQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-30T11:16:34Z"
    mac: ENC[AES256_GCM,data:IRvY2oxf8a09DIPvRbubZDz2bdsJ6Asnco679eDPG+dWRCCPH1iyrDwD/wnWzXzVd+bkI4nfeya/+ChOd4vEfKgjMBe6Nra6E01MIVX77bD2yYl+IdUkCiKnXaIG2X0uq9cvNCzOw6oIsCmwh2lkg4C3jA3b0GkOSH2GnM8FtLk=,iv:6Gl65C8+f8CjXBDaRjwAI6KPO1a5rgEcwjBkpmyJ0YA=,tag:pWgY+0Lf7bwyPS+9c82uPw==,type:str]
    pgp:
        - created_at: "2026-06-30T11:16:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAA0SpJvgB+CK3rFw2Pnv+dZC6q7ccOnud6ioPXBAj6HOPS
            yaGOklb6tuwztM2DeZsKx6HUz5yXNGpS4HS8QRFb010eW+Nr/j3Q8QBEN04zfZnx
            ffDFDr8HUueYgcJfQh3gklkEOEcXKWL9cSIV+SuRVz29fv5d5fLVDVyVxJqSGRJk
            g6kEYU55FVTGtg3BrcPNquwuXEp/gMGs/fMtwei+5F9fmuOt2xmuZVV9zu/FueOV
            9n/bLDA4aG8ThbqmkqL/U+rrRbJraHpG2G+hKx1lAnORtbTRhvko7/YLOBPfz3Dj
            Rof0IbQpWlUdpBhcJ7Hb7I9EkCpqmi05b1/16FuASJ0ju3PeE+MMiopiYcDukjbs
            BJ8Ml83X8rrks4+A9otu5O4ixtw+B/cU/rWQUiZ3vPkbx45DKsTS4xci7H97swUT
            dnSoU4zyJTwcNjkBlvWB9udq5Y1RzY7+TFV28+fWEKJ+9nQWhbroNpQJcNvhulSE
            DwsMVM23bBSgJDYx+YnWmdawUriX7Cblee/LSCYVui4Jnupt4vW7kIdi3dkTKI2F
            xVIVlSVVg3r5q/TAVySRLYrJTlVVjpB3Btlu+1V2u2N21zCv/Bz3METtpdiwZ5PD
            UTqAHXQBpZKxNELU7PDFX0402tZWCRDws5b+tNF6pjDrnyIYiDb/CODglknff73U
            ZgEJAhAbYg35OI2DI7SIJK322qXE3Gf/oa+WWz2kxLt+tex8U5/gLsAfQadckjvg
            llUAOiQvlqD1TujIVkxhGJTe0ginl5C3mbKXXLRypKqihRCcFoL+6goAg7ol5VgV
            j6P6luZ6JA==
            =dT21
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.2
