apiVersion: v1
kind: Secret
metadata:
    name: k8up-helm-values
    namespace: k8up
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:zQuSoENeNR8RbOOI4wHnNNacMLBPvsG5+//8VFpjt44bfcmXDHQBXV07YDDa7DNmvKQsFlHoi9xITOtD6aJDSYXxheILl2vAcyhadyl58MzX9f2Kw0HYDr7Gon9MhZC5+7WcJ+YjO3MyrHninYI4ZDj/WSiR6QJRJa/ifqLSFgzog9PA7U42mzzVi3yhqE1X1mP5/jMe7FYuxfIJUBFVhTz5Usf964dStDAxAWdOLBAISpnViUPjn2x5lqmCzjC3+Bh9qRaFTLM4J2iE3wmYERVB5aVJ5AupnHNDsYCwMM438GeiZntEJ1uwywE+w48sMzGQgP8vbcjmm5mO5tnZ9eMjtAXIqb0FdnK2D6Y0JosNRegBOyGOe1ksgEEHO4W+5Fl8znaWYBnX/vXpIyuX/J6eIVpBJiAMheJMKdy6mi/nhdWAD+OKQZbjZf21pcW/ZJ3VBPj7XXix05tpKTi7QpCHHBmEjx1ZT1BHRvb+gHitFVyef5UjvSVKGfEp6hkI9K0bOPgunnn56u3RFnMgkEzKRbW2GwtMuEcka2LzJBFAwstkwBMpE/ZrYIOC/Jp2mQ0IpRbaTODFbnWY/Ps15jvzZg==,iv:V2YIZ6z90nzLxlCf7Nth1PRtVVQ5Rseh7ACWHgYgvR4=,tag:G8oqwiTC5qzZ2kA+Uve9ZQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-06T12:33:50Z"
    mac: ENC[AES256_GCM,data:XqTXRkIwDu1cN0hvh7A8M2yrJ83k9r+l6bEstAtpWh3FPfRD2ICdJgevKwIuM68rcbSndkSHBubNa0Pshz1t7bckMz5O4osz78P+8sycvUdyeZ318tEryMJHSiMgBcCvu4VshUCf99f1udtXrhm7sw5iDTBvkGGvmd61iIGgpCA=,iv:eIQH1+gtPSPckajErAgMLImHtMN9PBJIvYVPKF4jkbU=,tag:W5x9cl1OXTTK3wrDGyl05Q==,type:str]
    pgp:
        - created_at: "2026-06-06T12:33:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAlExXLz7hrus/xBkVUOdHfcXdCpiIOxM3JkgUf6yevtWr
            lCiuW1jD3P7GzY2uP2yMMWHvrBAxqVYE8s/59Gs3jHl5ufhINO1i2AeY2IBo/qWI
            7yp3NDb4ldeV7DHC7tbUb8QFORVgVncmtzlj8OLfFV7kJWtz0YmYHep0Gy9eFdwa
            pB4leABRzbDe+9HFQaQULY4//oTk3LuH82r/G3wvqDi0jwbiVK/uWA4HzDUzEVmg
            LfgTBKGhOP7vaBH75SzUMtR4A9Q64YaH5OxNX24jl12q7mZHP85AbaTWU3kdn9rR
            QvRP2kdT0Vg+zpdBnxOpxk4rZLzhr5pidzsCSj8ge4lXO/0xH8h8QLcinniJ1Afp
            RuFcIr9Q1s9s35O952OcPGeC0yY39dUzlPK9f2DHosmR2UYmZzR8Z2sDl3+8KQAM
            0DiF4B8IrG4c6bF2Lkk9iE3M+tV+YOzIiPQK91NqEYIC4lsKXHiWilXKi5i7YOZl
            NG1K9CYX+DjgDVAmpEuU7VwIRLFJBN7NE66qrYgE2W4UtkwPQFUI+mRzdTmwuYgB
            mAZ2V1IGitPJCDdTcKb2OOYHTYnMGEEc8C67FnBBnRCYaqV2jwm2NgWJsthAW+vF
            0hiTrkWeAHyXjQMlPQ9830sR02yFgmuO/6I3cVa6TPT8QmcoUscLpigVfA2Qj1DU
            ZgEJAhBVZKZu+l7568msho6hDieD0fRUHZwdQzYvvR9kjOPzM/DN0HBa02nCTovU
            5modXRKUC/Sw+FbM38mD3/J3PdOEKS88yW2tezuWyL1Dyi6T+9YW2jocYe8v0XVX
            MWtRwzSstg==
            =lggJ
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
