{
 "title": "Cloudflare Firewall eventss",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "World map by action",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clientCountryName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "action.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action=block",
     "timeField": "datetime"
    },
    {
     "bucketAggs": [
      {
       "field": "clientCountryName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "action.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action=allow",
     "timeField": "datetime"
    },
    {
     "bucketAggs": [
      {
       "field": "clientCountryName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "action.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action=jschallenge",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Top blocked by Country",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clientCountryName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "!action=allow",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Top blocked IP's",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clientIP.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "!action=allow",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "Top blocked requested hosts",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clientRequestHTTPHost.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "!action=allow",
     "timeField": "datetime"
    }
   ]
  },
  {
   "title": "all firewall logs",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "datetime"
    }
   ]
  }
 ]
}