apiVersion: v1
kind: Secret
metadata:
    name: mailbridge-config
    namespace: kumbuka
type: Opaque
stringData:
    MAILBRIDGE__API_TOKEN: ENC[AES256_GCM,data:bSpCVeFJneFrPy36kjOY6V/DWJ3n59AdooLVjggE2QOtAiFvr4P3KQoYPJM=,iv:IFIjxvHf+R0MwYIWY9kRj5lcQQfEroUb4zcQWg6TSWw=,tag:9Xd1ZvwDaQTbgvCQIqvnUA==,type:str]
    MAILBRIDGE__SMTP_ADDRESS: ENC[AES256_GCM,data:MZkREUVSwpoCM12VYeE8lqwm,iv:d4B8wxZkhav2wEZL4DyikLPPZWW6hfQOjCWPcM0pDlw=,tag:LgNjN5iklOERqUpjS5D16g==,type:str]
    MAILBRIDGE__SMTP_FROM: ENC[AES256_GCM,data:+JcLeBxZFZc0nPWg0mR9SWNVS6NxLgg=,iv:PLgybRHulsMFpJPeiqCflUPAv4VfznmGB7PbpucQY6Y=,tag:X61U9bATqJd477fxFt6uPw==,type:str]
    MAILBRIDGE__SMTP_USERNAME: ENC[AES256_GCM,data:R9gXXYrlqhQEV5o13CewvbEuUfNZU90=,iv:Rn1VJex4BLEYqb4iiAOrLzRSnJ6/LP9+F/qH6iLHah0=,tag:1dVcL5I/G880SyqDJQxDwQ==,type:str]
    MAILBRIDGE__SMTP_PASSWORD: ENC[AES256_GCM,data:SzerIsLjziGm+iGK4Dz9HA==,iv:S9MMFw8Ow8Hj3NCP/89JukX5Pu8OvjRCJBr0TG8Ax7g=,tag:CAaOOiNRdZ/D5h52R+T5/g==,type:str]
    MAILBRIDGE__SMTP_TLS: ENC[AES256_GCM,data:rnQy,iv:DYfFuP4HB+Zn+QDu4Xjf2jLViHGAVT+T7PskAccZTq0=,tag:/T2TBMfYeU4ok0hZPiANPQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-09-25T21:59:07Z"
    mac: ENC[AES256_GCM,data:ldWKYIkFEi1xfrgqS66/z0MjCpo/DgDGIj5baj0n3ZevxCQsWkUYup/BBrmhw6+3+3EuE95osIw+jpB3gmr6Z+baXdqmzgDqkhf7oCx2WrddxwcWqWmMcKypYESJD8VQqxpTLZJ50G4dgvGNRLXe5aonKzKMOr4t3TeJsu0whhY=,iv:qzwfrn6dkxfx8aA8KIQ6Nf8HubjwGh29niEF6pm+7p8=,tag:nNKZnkiIfE4CiNqnnU7Nlw==,type:str]
    pgp:
        - created_at: "2026-09-25T21:59:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9GRygRGwp4HrShfh40gowgE/aV+Nh6KaBSEwySSThfqiE
            Y/Jzs7oDoQbJZ8sniNbWrkol9nsYwBJeoBM5pBQtvcoE/zOrsL6KMNJWr720xM7R
            vLeS+WukNY4PVXnD2MkKb64a9SH4ZV6uU16SRLwVu7WaHN8mzXrBKy/anv75+9f/
            1Lgk0mkcQ4HM5mzK2nSEGxo4jlKMeIHQNknxJNW95yingwIGZHvekulkcy+0Jyid
            9xwxUhpPyBzg4mN7GzCk0USv6G4MYIYhrhGs3c3DrUf7uFTqjSdKdoKFBQnwYXhC
            ddeVWRQllk6XTdLDqYHslgvz3fBwurr8fo1u6vzEBcUL8vXg3lDOG4tll4Q0fbGZ
            tFs7QbU+7UzsWy7OwDDKrXCGYTQ6O2PcSHtkMBqgMMJHakxPf8SyoDQ4TvxGtAsf
            1eeg0TVu9UK+YgmAguEbrAxKgh+cbJqAj6J4dDYdO5D+8/qs4QFK6i9JTr788ZY9
            16fZrV8PAEme3Ogykc2N6QeT7VV4Hmx5Kc8Xdu57cSe4gWG0YsmF4OFNvHwvguwo
            VjUNOF8rvkR/2b4GhvsQREYoYQ47crcObrQRzC1lmL2vnA3hJtOwymTRXfiyRDCF
            1/uvM80akIdHf8nn+XIrEq0+2iy2aPnK4j043CFj2FPWy8dxPMzRu9Ts/iG1yibU
            aAEJAhDiECHhcbNl3hx6XUC9NYFVLbBoRahBJSvIxJXwVeqwr5no4zkXZ5bLZOKi
            l9x3WVHuvoCrBRawP8JZZ/0YZCSJmztriWP7D9OT0qHKQCaQ47rsCbqEL/jHCXlZ
            LoRH8g0PA6b5
            =jOqS
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
