apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:O+oYKt80Hm5Bgg==,iv:SYEAMYej9eEpkm2Z00D81zcMCW6zwxeVRrZKWG5n4xk=,tag:ORwoLaimkrzhhskQdF+HwQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:PMIkCcYKBtXxbfLHkaIzjnNbnlw=,iv:6ot8uSEREIosYJ5OfV+g0xos7KpXYrFsdFoc0QGpczM=,tag:m58rrXl4UhYNuTQRqo82hA==,type:str]
    SMTP_DOMAIN: ENC[AES256_GCM,data:XnKtIBA/+asVp9nI0g4=,iv:U2CEyQohYzAvxea9QzsJk/a07hqXjh5/S0DxTswJ08w=,tag:3Lb4P2mQS8j8wBvjXXs/3g==,type:str]
    USENET_PROVIDER_DOMAIN: ENC[AES256_GCM,data:Ppfj15WEVBI1JA/n4pcQJcKvBb8=,iv:aD6U33Xq85a5m+advcTxpbPuh8FpapjTldjet3HCXHk=,tag:Sw1ij84nIWFE2bKofl1byg==,type:str]
    USENET_INDEXER_DOMAIN: ENC[AES256_GCM,data:5yM3XhuzJguX6HiSBMrJWK0=,iv:bfj1ngAAdMsxeKFWPHUQNK9L8B1Z/RITm/STwzrfbmg=,tag:XcgRJ3vjHbG9UYg+5BbnfQ==,type:str]
    NEWSNAB_REGEX: ENC[AES256_GCM,data:glSCD2excEW8RU1VEtvBfQ==,iv:Ul27mxrKh63H2ip8/DXNKb8ZNAtw0DE9uMhVrkAqse4=,tag:aLwoaDY0P7ArZZOaFpoGHg==,type:str]
    NEWSNAB_DOMAIN: ENC[AES256_GCM,data:rUg4WDJItig0y9VolleIz8B3TchukOv+Py0fT42k6ZnTjGm7rm6b9mKZyjyOeJqjTtWqMyoxpWmL0oyYeCQS/Ec34ktYirGrPq6DT0PIwo7UMCBm,iv:zwxhxBLukQIb3xGf4yHq6dAd5/e/YmxzHk14WZN0uh0=,tag:l00fPK5Pf/dHC2Wxp7QM6g==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-08-11T15:52:39Z"
    mac: ENC[AES256_GCM,data:JPbc10mCuHkTsswkKtnTEfJ/rtZ5rUgDes5JkyhNdjlm5V4syC/8eHodjngAGwDjWsSQt2knkcE0E3V0mQnq9mSEECgGK0Q3wqAliBJGwh2ikUtXK5xGfgc8614AI1Hadlaggq3BNFsAax3VaGYSv682UoniGsncdquKYCwTLyA=,iv:AZenrHMITdOrqmoynuq/uXL/3YaV93edEApqrOyOZR4=,tag:s3F/JsobQBxNIIJ4RTiZUw==,type:str]
    pgp:
        - created_at: "2026-08-11T15:52:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//dBGV3FzipkIGvvlI0VQ7GjDOGCbdgTooqbs0xkg6nmI3
            Z7+r6Cok3BzHgBaq/JUsynr1SOUvdUXZiltcTuvtV8NGJDBdPsvWtug1Sa7qB6Ai
            V7nsj8+6I2b1/PZeIdOcjKVNyPdvl2ZPV50yUnKoGdZE7oQ3WsMWHE0vIqhtligO
            1CsgNSuj13rqwqHPpU3sf0qq2yPrtz2DVfJv8YimQRGtBu3dluXuHxknBms/aQow
            fKNkueL9NfNkvzWwVxbekXsWQpueUHyxbaTd7JgdU1vdu9RX70Ec/RmB9XwlRckD
            eU8OGXmpR/UBJL3bDUPVaTSjBc9NfD9QbamFG7OrorbrXInEe8tqPzSxnt5Fn4rJ
            gHlAvp6Fx84WTg/kNQa22jlx81zh+AS0e33nYVmSoZWx5eMplgseRo45mCx+BkXe
            RJXXTvS8WoTSTovFhk0Je9qiOA/Di/pXEfnZSaxcUzshFxjrRmSLix5H3c1zvaI2
            xvaVYiv2LZn9Hm2xyZgiio7U7seJwuz2w/jdNa/jRoOQFsJk2kWU+EAWn4ycjP7M
            E99+DR/sWzXwjoaxTPdwahWhYCEGpYdurxvXHgl5KEIx73TWwN2KhXw/NP49JXmE
            W3UT5TUZ6fytASQ8MQnkei/soiJbQy41IwrMu9v7dDGGTBb4EmLPOFEwo5rnPp3U
            ZgEJAhD81aCNjM5xiIy4lDcXrG8vvXiNe3H5kk+BufP1apDgtkrylHsr2rv2YNks
            ch9VXBF2b2GjoQiBlevhbXaq+OK+E4p9svM3Af3Dw5WENODgmFklD+synt37iefo
            pPKH0iVubA==
            =tjPf
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.3
