apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    BASE_DOMAIN: ENC[AES256_GCM,data:tmzMlbaxUbeUHA==,iv:0FJrn9iuOPE2+J2kOL3RA+P0zs5wkLMA3EPx1PQezDQ=,tag:1tBOv855D1CrzHDLP4togA==,type:str]
    EMAIL: ENC[AES256_GCM,data:+mpSjYJca4nPg2HgUGTWuQV3yCQ=,iv:WDEJnricK2oG5FdQ3GzNZmd6U8YXaoMSlKrs4Gn37Yc=,tag:1aanTP5Uo2Ng6bkY3T/dbw==,type:str]
    SMTP_DOMAIN: ENC[AES256_GCM,data:bhMJ+1AQBnP4Cw0Aycs=,iv:n1Ibp9v8EIC1jq94hAi083c7oUfpE3S6O3yeR6KC7y4=,tag:9wuUjkfH5jo5Khk+cDQClw==,type:str]
    USENET_PROVIDER_DOMAIN: ENC[AES256_GCM,data:+gEU3WaG3A3W7CioPUpB8E3nMCA=,iv:RFSpC+nDhc4aZK+IEytDA1/63bzoSdnUqL89ZZgmK6c=,tag:qVTSWEYInhSzm3ZoCMPb1w==,type:str]
    USENET_INDEXER_DOMAIN: ENC[AES256_GCM,data:GTsKAMhieluOnTYp0GMYcXo=,iv:+3zOpbhFHekoy7B9uB7GFySClq7e8g5wFg6oR93k3pY=,tag:I/vi6v7J4GihYRKj8vU1hQ==,type:str]
    NEWSNAB_REGEX: ENC[AES256_GCM,data:8PTGAP+QJok09ORkwFlMUDdYiUM=,iv:htckpjLEtElCgTW/7xEzBUFSWhx9Pwypq8fRDrHIIC8=,tag:72qens+A4/pAwGqSb0qo6w==,type:str]
    NEWSNAB_DOMAIN: ENC[AES256_GCM,data:cJ13SJnqqN3QCynX5sLEzNx83pD2nS0AlsyVOSmf4LPS+BUgxMuzRYJDFjDJGZCI9U+g3TH8ktxfLA4RVyt/hRbrFjWIWsuVe6jtyK1PzOVfJnh4,iv:RHee6FselxL3pLA7BIeaA7TSKhbGWhsN/Fek1iHWfyY=,tag:Ig1zbD4zqqH0CbCqcJ4q8w==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-07-05T18:40:34Z"
    mac: ENC[AES256_GCM,data:eGqPaYvsl2UBqPQKNESY1zWQObRc5x2+p5yjpD5UGJfiUjcdNLzgcyvOUMsIc7GyYmSVuCKocNGTuwhFPLdJkJhxHeVGJa9dD8huAJayiimoC8ejr1F+aOeboLQaICoNEx7yDEyrHdwI313b7toNNJEFJLg9CwJ8yuG7EkRv5oU=,iv:ycZrpYkfYkv86p15eV9P4ML1CRm+kWdVZz/Y/x5YHzc=,tag:9+uVacHcmgwNlEir55mWlw==,type:str]
    pgp:
        - created_at: "2026-07-05T18:40:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAAr0rNTWDs/rzuRgFBZYAiB+kkLYkgybpn/rZyrqWvEhGH
            nrhc3jkU105zfhYOuM144ipQxDfckhBXPJSZx3Yfi94ShcDqzyXDtyDlVNCrEY0e
            mtIxTyOznEq9g1+b0jHMq10lHjCDHmolyV5HgIH1Yjhk8Ca+/dj7maU9Nf+FevCs
            xKJxJgCQ+C/DDFqWEQ7dU1T6mI75H5PdEnUf5jYvdFwNVVxgluI3s30qG7asYzHY
            B48oWSavoKz5XnyXD3cpcK/j+HwMCbPEVYPpacoM3lIHbqmfUzUrf8HXBK2B5GQr
            +scYhO71l66c6vJUG6vRC8CFQV74YDmDPnnsHzbVw736JQwvrKyevgRLPgDhmPAA
            xG8APuYnb3KY+Tbld2/FSMBAhBEygMfrnWlOMZrLnQnUEBOMSNibzjHRHLswLZg1
            m5OXrgjD05M5cUMHt3x52UJm57TyIXUt4T7q0gsksyo5mzZ+aFCsLZBgdKmU3C6t
            X4UzTH0jWvstIUbR1n4UTZi6dlFcItqhT7Yiof+GSxE/vQj9iXIBJr06br/A6xdW
            KNM9uyYlo4W3O9AshepslAwNXeFR6oFBawXwSPMvMkl2IvAshOgZZNq+NRWPDiU9
            mh6z5FeIxR4vV5PAGzksPBV1VXA4S1C8+qAvDPOQim2CZfppkHDP84DLWf90kFfU
            aAEJAhA8YJIPNaz0piwG1Ap3OB0fXf9c8vviIlt9uHGv4xBFpFsjNkFYU/fzRZmG
            xa5xm8qrb7uKy4z53Pfm5Xq+fkPqGkO9azay+zCWshjH6IUXBjYTnwr2hlPwPyKQ
            cEA9pJQsl+Dv
            =b/83
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.2
