---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  suspend: false
  schedule: "*/15 * * * *"
  timeZone: Europe/Zurich
  failedJobsHistoryLimit: 4
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app.kubernetes.io/name: renovate
            app.kubernetes.io/component: job
        spec:
          initContainers:
            - name: never
              image: ghcr.io/containeroo/never:v0.8.13
              args:
                - --tcp.valkey.address=renovate-valkey.renovate.svc.cluster.local:6379
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 10m
                  memory: 16Mi
          containers:
            - name: renovate
              image: renovate/renovate:43.195.1
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_ENDPOINT
                  value: https://git.${BASE_DOMAIN}/api/v4/
                - name: RENOVATE_AUTODISCOVER
                  value: "true"
                - name: RENOVATE_CONFIG_FILE
                  value: /renovate/config.json
                - name: RENOVATE_ONBOARDING
                  value: "false"
                - name: RENOVATE_PLATFORM
                  value: gitlab
                - name: RENOVATE_REDIS_URL
                  value: redis://renovate-valkey.renovate.svc.cluster.local
                - name: RENOVATE_CONFIG_MIGRATION
                  value: "true"
              volumeMounts:
                - name: renovate-ssh
                  mountPath: /home/ubuntu/.ssh
                  readOnly: true
                - name: renovate-config
                  mountPath: /renovate/
          restartPolicy: Never
          automountServiceAccountToken: false
          volumes:
            - name: renovate-config
              secret:
                secretName: renovate-config
            - name: renovate-ssh
              secret:
                secretName: renovate-ssh
