apiVersion: v1
kind: Secret
metadata:
    name: renovate-config
    namespace: renovate
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:t7/GbzpYigu2HEwR5I/Ghay4CqXsx3NyVWoKQqP6cZz0FnijE3yCas38Jx9qZ2sSLwIY4ZZMFL6vtZ2GUEHqDyBCSxdNM33s+utIN+gIgIE0iaFmEDv3atpCLcXhZhVpOiL7q6ys42vmWoPdD4RChvsg9LJiy2JBGBNEGS5yZurOhPgjFHgLQsnlTTfDSTg5hHdNQxcXotbHH3uyxDfxK7iF+fNc4er4gwJy03QfPMNMbfAiM80f2xgehTCBV3JTv++ELAFtZa9JkWm6ScfPaoY5NC2HM3+RFz+PtRqQutavSGHJJOv9iP8TyQ8V+bcKERyrOn7pTp3Zmf+wbhtqvfEo80rbwi63TJhlowNgXIqqgDxHeVrsWlNinty3mvSvaq/yWXO9BAlUQr3D+ELB+Pa15a4fQp0XJBukc3IAOc3pMyQvNFRPIxYygpQO3LC7jkLBaARj4umgaSDEcei/lDfBe/kKVs288LXsmxnDiWTxNBOfbl9CIotSugItKRV3KYyEpSUxqbk1KlmePBzDh25/7f2fnUklyRSyEDX0lfSui7D6brEGHufG6Uqh+Sxy5ligG6GDp8+cUOc54H65i2O5RuyjrWZqqfeX8cGRoC/RbV0591hXWyguhSbi8u3Jzw84ZuSS5fKqn1zybF3zBSEEmoWTPbYLPrA933ChdOtP2ehRuCawUDYd2PWtFV21J1oLIk4V7YFhCNvVs/u4ykI+PKsV0bMYyy+0Z4LMExZHXhFvvFXGIcle1vZ5Tb0OHZMiWn5h14XSVo3HK88vSYuA6ZtW2lzOl/mRe4yQaJl8xLRlQkiuQzOG1kYLbz09bAg1r6D/LrqGAhQcjjFiFcS2xKrMdJB9Vp+euLcbkiCL+qzVj6OFoeeYl7OYFkHJZe2fiVOjQu/Kt81Ub0WXqt0g0RRCVGaoWHGn3L2vQ5u7el+fH9Xx174We5vlpmDtxUH+MiQjMwps/NzsvGBqyVYLxcnzPHJE3u6Mq4Se8DJ7TcOlBNsTuNEhz+PZCro7Z+tJsCx7aZrJkzuspqSYKeemHjsaghARDI4PNHk0WwC5t2bCa8aOvXIVVam5IuQb2MxxO9wh7OiJ/Q55dabwri9rmTqlhlAATbBiMcKVPfozXLMtpzW0SNSioHBqZ3ELHnllXNfPsvTHp+7STLE2kDOhwG6f,iv:tYWzOLAQctAF/gVmqEaAyZvV7E0bcF/PgzS+hvawkr4=,tag:H2YNcDYHC/dOEKkqmDDErA==,type:str]
sops:
    lastmodified: "2026-04-04T12:12:08Z"
    mac: ENC[AES256_GCM,data:VxJuR9br6gouwvl08PQRkB+EhAyGZMEE5o35gYlG7B3kyVxqmPkN8rQHhd1i3/4cTu9fSiOF/CBqTlgcvp/WrbbAcTRHKSbodQcs6b881awHaJjHkgCB32AoHNIcVK3zc5crxLQrWcGVMyflQOQoHbIvAmgKoXUzNiwTL0RFzHI=,iv:UaXtxsV9YyooQgE9+Tak7srk6JMJTxsiCM3jFWUyoCQ=,tag:/TRijdJC2vG2x9k13VFbVA==,type:str]
    pgp:
        - created_at: "2026-04-04T12:12:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/8DhY5PABYD2ak0WpHK3QMABMuO3s6YnHpKFwM8tkZ/e2I
            9gnk9NYQhnBbQHzVpokRUQjN/HWZV9QbhPOaMfh6Nb9IgLQ2k+iINT/Jwv5z9TZU
            IapqdEFcV1xBkauGQcY4IsRENmGpdRajEZOBVgTysAWs+dipiByQd7nH9tSw3J7B
            knK9/U9Ykflgutww1674eGrwlyGOJUubK+N/rxnLWoDvck1zsYqClOcmqupykN84
            SuVNdHWRWEsoJCfoCcFsUJn76KZ8zY4dY1PdfT0g9EOorL5Il7PqHqMFvD/D/kvH
            krIkFRfKtjURbdPkYY1KQU7ADHPz0op++wA9FpElJsNUzSALWrH+xTwEvu5UPvG/
            XN8tKZYabYV/fKHv/mP0f6HGmgK7Zuts8d2AaT+6HNHsHExkT9//J26/kySYIbCh
            RRoDQc9VFbBH4+EnQ6dd6OEeDP7dfbaUqRUBNTMo/PxIHe/vE2lXjETB110p0RKD
            ASts3AlH6eL5ZkabnLjMN4lRhbCEChCxVtognSQdiDh8mOG40cVfsCrIHkFPZWT7
            YNsitpibFK6ZKNKQDpxOFwxNhzBJ3Cz9qRgFSXK+exTc/zI3nElBB83iKAfqmdbw
            FeFfMCaoteajuV+d8z5Vnd156l9vu1huUril5tgZ2cy7HFQf2HbcNZvNnXkBpPvU
            aAEJAhAF/73BwbhXKNzEfBgHY++pg0RooTweMPM6jAzmwadMn2KmyPw0dfAemJAa
            hzYVofF/UnimrZxN8mUGp/Gmaf+g6Dgaf1GTO4oUWNYDwuQV+hdp44jnazmBDUuB
            /V50m02ity7c
            =SAQM
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-ssh
    namespace: renovate
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:4L+RMytj+K5QYDXRdgrwkEW/HvS9JeIcteRC1mMNsSNFjE3zOEIAyypD5TENKnKeT7UWQQ/V7vuMzr9WM7JU5eAIQtHSZ3AgN1X4Hx8OaBtrMXC/wd8Edk/bFYIrE87DCpFs7/13xj/6R0fJ92n885H3LzBaVGn6STuq3T4=,iv:SSyaBB22850kd0Za1oqz76pBcjlqREUOSCCxMqxPX1k=,tag:/3Hto3GfbGf50yybnF31CQ==,type:str]
    id_ed25519: ENC[AES256_GCM,data:qxyuc+AihIm6qnpVxDWOvIDTQtGWzEdPVsvdnjrsJPZ2QavihIn9xlT//wOCooixLq6DFYRotws6X69UEOxnTGHlUTwNuTGJ/8oXEnbxxlXd1at37i7CsuMnGGkgBKPSBSvjd3pzbC9GZfsFAl3d/nOnbygiv6HK78w6VrNyHPl890UhPKgLcNzt4R/cG3jY1y+YOo/aRNBUliFVXzKmXEola6b090Iuj4zgl4x2GxZzQgwn6BPVwWWZYhRXClkp6C3ExlgKZnD4V7j9qLAaoB7HJ/V7LNPAkqQVyJi2UXdORM18OQuEyfRxATlr9VJmywURhblANvGqMMTWZX0hcy0xoog1dzBbzTOm/gktFyVXoYxkDrkkkwXMO2O1LqEICZPm6/GhH2op3Advf4fwD9UT3Z4m/Tk2LRf/RdOf54Vbo0JqXjML9WeKUP+cCEoK/obbGIXsxSLyVe6TOfRbjHYgOCvh5ZVsOTTBUrARpsxSyEhQKzgp1G5bYZCGtDMyYrZMw+lC6CuSydXuWX8/ov0GNPSIspzpFADh,iv:NJ98fuEY+G4244hI/wSmuj/A+YTg2f8sOJP4jg7paqA=,tag:L88Mur5VC127Iyp1ZhY6CQ==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:7onpPBmrV2oPMAZh8OnmFZPVh0/8Sqos1eYzatayqFj+I3jzKIKFczbDebYseXGUyq/wtbWbWOtLru2F0TZX7aZ7EYj4bM7uAwffZ6h2dhmIClEASrGSqc+hHcB/m3/X0Yl/2NT2JODJ,iv:0nEBMRg/YmQZs9A9fAgc1OuaDKPhCoocmtjERz8hpbs=,tag:8pP9gq0c91Ed1DUd3y1wpA==,type:str]
sops:
    lastmodified: "2026-04-04T12:12:08Z"
    mac: ENC[AES256_GCM,data:VxJuR9br6gouwvl08PQRkB+EhAyGZMEE5o35gYlG7B3kyVxqmPkN8rQHhd1i3/4cTu9fSiOF/CBqTlgcvp/WrbbAcTRHKSbodQcs6b881awHaJjHkgCB32AoHNIcVK3zc5crxLQrWcGVMyflQOQoHbIvAmgKoXUzNiwTL0RFzHI=,iv:UaXtxsV9YyooQgE9+Tak7srk6JMJTxsiCM3jFWUyoCQ=,tag:/TRijdJC2vG2x9k13VFbVA==,type:str]
    pgp:
        - created_at: "2026-04-04T12:12:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/8DhY5PABYD2ak0WpHK3QMABMuO3s6YnHpKFwM8tkZ/e2I
            9gnk9NYQhnBbQHzVpokRUQjN/HWZV9QbhPOaMfh6Nb9IgLQ2k+iINT/Jwv5z9TZU
            IapqdEFcV1xBkauGQcY4IsRENmGpdRajEZOBVgTysAWs+dipiByQd7nH9tSw3J7B
            knK9/U9Ykflgutww1674eGrwlyGOJUubK+N/rxnLWoDvck1zsYqClOcmqupykN84
            SuVNdHWRWEsoJCfoCcFsUJn76KZ8zY4dY1PdfT0g9EOorL5Il7PqHqMFvD/D/kvH
            krIkFRfKtjURbdPkYY1KQU7ADHPz0op++wA9FpElJsNUzSALWrH+xTwEvu5UPvG/
            XN8tKZYabYV/fKHv/mP0f6HGmgK7Zuts8d2AaT+6HNHsHExkT9//J26/kySYIbCh
            RRoDQc9VFbBH4+EnQ6dd6OEeDP7dfbaUqRUBNTMo/PxIHe/vE2lXjETB110p0RKD
            ASts3AlH6eL5ZkabnLjMN4lRhbCEChCxVtognSQdiDh8mOG40cVfsCrIHkFPZWT7
            YNsitpibFK6ZKNKQDpxOFwxNhzBJ3Cz9qRgFSXK+exTc/zI3nElBB83iKAfqmdbw
            FeFfMCaoteajuV+d8z5Vnd156l9vu1huUril5tgZ2cy7HFQf2HbcNZvNnXkBpPvU
            aAEJAhAF/73BwbhXKNzEfBgHY++pg0RooTweMPM6jAzmwadMn2KmyPw0dfAemJAa
            hzYVofF/UnimrZxN8mUGp/Gmaf+g6Dgaf1GTO4oUWNYDwuQV+hdp44jnazmBDUuB
            /V50m02ity7c
            =SAQM
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
