apiVersion: v1
kind: Secret
metadata:
    name: renovate-config
    namespace: renovate
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:D4OVJFtsMiKAQ1bynvwnYhW7l2ohvy/Z+C1viJi+P/0JTBoSzBqLUbvoXgSmhSG2Lctn8LgsrhuVBiXaXgS7eSddotKSW3A9yirqR4MDub+oBJ7SaQK4NNLRG/yQciZTYs7CWwa1fRYTFCHv03XtbJ8i77dmYiWzHMeIkkKhpGScUX19/j07JN05M9eqsj7yEZ3b4PWfxKcMsoDb/LZ2q0aUWw2EljA4mdlopm+cLCjgg55JhSQLsD+Zs38Arw8QnF2t8wF8gIqA1d0HRVrbdOgwC5MMdd3iueDxywzt6r31IrnFOnf89JouhsyyEI+pw0kObRdN+BbaAK8DXlWOKYhsr2+8wC/kz1yZon3onOg8d7gMXeUIhug8fii3Lq15S0bVg0levVtZGILfcxwG61CXwlJKQ8cqJ1L2jARDkK80yK6fKxXQcb6uuzUXWwXMbd2TgNthTVJjabznej+dNQOPVXgS8tV7OyaV5vaAPrgkgNTLZUm+0ljAMoc5Pvy7M9l9WMYL9tlhpYYGgYfLMD7lDxkn2ZB4YGjzBHFgZTAFshglnGMSRyW0xkNiatClXUZGERmx29D5rDIxn9o8gCmJFLCL9mGPz0LRSYKDSibKj3jD2cz9tyv4K7bGU2Z4ai3IGrfVjQ13XxEBcvRFN2LKEJ0vW4sy4/nPQ6x2cjJHlewXRDpxNKjhpJPunxToUeZyvO6COA4Ywgob5/PFxJeQrIdP5GNabVQ1zwGFKWfPrU8k0KW8TA5GiiprxN3IRwX3WMKLpVwNogodCxxXWrTNwRHgrATCDIglnTl0/7FqPUU+dlq0Wy7YdT9FgNMrJ6iuPF/gJl2Xv5TxJoWP1OX6O6liaoWny2CkH/0QIz7tJnOluaNftnp9eejW2AF/xZZjp68VR+BY4Npe6LIlLM5oBHcmt11h7o/GJ/r/Au7kxEOSfymQwu3N0RJUQ9e1Mx/3wHPzhJQvh9zXwsbw0bOxaYNOnMQyCR8fT4j2+6yZdBJca4IQdGKawlDe9xV9ELMfER+hU/gAGQ==,iv:8k3zkLDGCKYTw4Lamvfss0bsv/v7dnNyRjiRjR/LO58=,tag:suYWRqsIsKXRIlw74QJ58Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-03T06:49:16Z"
    mac: ENC[AES256_GCM,data:0BbUzb9laAcu+Ln3FmgFd96O/RHIWlHJ0va3OPQlkfpovhwzgfOMxiDqRcHBUi45MPiajhTGKdX20XiAyMO1eUJ/PpqahfEJW8Y2LibPhQem1v7hmCHmmv6v1iC5PaLOElmWhb7RdoPU2vxLEah6nEnleP33F/3TZseoCMDuURk=,iv:RsY2zJdwia1GGCpXsZYGg7O5QYN9CjSWOB77+AqyDPE=,tag:b+5qTwz53zvmcUWna6pxXw==,type:str]
    pgp:
        - created_at: "2026-06-03T06:49:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//Rj+EofWLQgo+eSJuj42aMgNniQ2Zn48DE9svMlp8/MHc
            wZuQAEQX9H37cBGjfsR1EhzDack4uSC6GSFo56T1fDEKx2L4jqZWgz/jyXrKxTtc
            BK+ivXQ7D21+wxOYvs1FmbimSZmCR0PSuKQ7vKjNJeu6PtC9aYGo3LIPXfhwB26c
            He/s42v4Jx4g1j/ZmAtOP/TfbIYcMda07cbnFBjyN3wB/btQnQm/317mN0FM88rq
            OneivpEFUuvecrqn7LzUmgIMln29u5/K1A67zZcNSp7tcXpQfxPWdnjidYLpkpSP
            i0pyoM3AaLdzA2jlqVqKEDT0neFBm/MBrvE4FubmfVSQzchzTWD3SH+G4YTcjnup
            4Bpc026uBqoaj9GWTh5t9AU0jXsbe5/OKwNv99r4EPns/Q5yKPd1ZcaD1jmGqFyV
            mc2TLIxLZKWsudT/Exrfdny76/g313a8Sa6vUL6lrSGid5myTgb+7mCNTvQlEA6D
            O7kcIqydOSupZnfRvqCLT3BhwGX/lNrCO5bx3cbW7hxA7Xu2bFsgHKa28+jziu/s
            wMJVQn1ZKJcYwaKG08BTiHgt+QCV385RW2o7hyJf5Vcf2AoKj2hPSCuUgD58uceL
            yqhiNPHfjmsCtcOHPOui6zRBdwrcX7RtWbuaHNVG0WFJ+ex7/r4diV9yuEPEgrHU
            aAEJAhAiBHNF2rIJ22pVpE5wNZiHGNlqgQxAsdMb0wpMEysHoFYBpKnyTgRBRXtA
            5xrRlwA4OpLa6zAySmLH/Al1bL6VbOBNfDkVerii7gRY4Mp5U7EFQe18GiXDLLjV
            c5giVM4a115K
            =CGaQ
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
