apiVersion: v1
kind: Secret
metadata:
    name: renovate-config
    namespace: renovate
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:5GSWZDjiZkL4wssiYlyUDrhDIG1W/BmK3z+T5K6gQnF7ltWwyjcQP74SDUe2B4EPCPvo/qTMUm94sK6t81Fw/c9c00wq+eHK8YkNrZBjMR7kDSG+kDDR/9kghlcR7yvy6huISdq6GBW48fLIQnz/6cCBrs6OTsVCd6rh4DRbDqkfk4qOqlET7TIdXLY7upBD0wbreT230F3tkTIQOta5UWucNU9lgQQS9bfHdJZwMxwBB/owAr0u3B+mgHA5X+udgDr75rQWnryxV8//hegjG4VRaOfPnm6mjcAy3xxn7kxUBjwPwBpCHNtdMOrzSWWKimoBq7oPHvFprRtRAhznuuf3EC8sqQjasytHOcpSRePrOwLmTaGc0xD8fOMyStlErhGwCtgXF2qRGxwIjMBTSCHCo/HTaeU3E97SBBZ+HatzmtUiGwvpTMakO5lMrESRrdVuqrvHD+SQ39f8iQvhCjuETeehH8MI3zZWbZuhzuC4GikZ+GEI7hDqeiXdPm1xE70tiVL2uOgEsr6u4ueYKBp84ovqoshjhT5SoPkjDa5su3xf0Fl8zpRKG8p3+B0qNRgMTg5wOIGs3UG953JSxN6Pyuk2s1XyAAKwPTv4kOTa/oFIk8shRc4j6dN9z48KnwVQvJC+Xo5b1jjXBo+gnPN61sE+n744BhSAhjEcMSMsulVgxFAmNPbygqVhDz0yRX7M4LyKDSqeA3YRCqtLo/A+ObEoJ2BQUMWBuCUIS+an2qMM9PaeSrycFgXDGAD092Gtou7GaB6Et4S6EgrXiiJGbuIvvNwG059+dKm+FL4BAWcOqMhETTOwqPT+KoZmIaTJ7yFudXYDMV5yUM9+53oNGToI0qQMsxqs83QfiDIoXHjj4Zq+CUehd9xzVNJ3GAW97P2Iref3nnuf5NGkNV4gBfGgCLWmrzQERJ219uJa5+M4bUfEy9YVfeFqB50LZFHz1lcIHrhJMpt6RuM/4MTH4STpGogOzQLf2YoPeMjxDtFVdv6ZI3AY44mPS9/ntfysKRcJ2Aj5iA==,iv:OJRfw0Ht7aP7P+YVaIxIVHoOI89l8ZRCcXxiykTERRk=,tag:jfLtGXHCX9MPsPZP5i24fg==,type:str]
sops:
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    lastmodified: "2026-06-03T06:55:40Z"
    mac: ENC[AES256_GCM,data:s3/Fka+PyiepuOQXok2SCCU/+lLu0tuP7U619IKXtAh0W1xwvm2WBYFfwDeYj9lDJZoa22ZrmSl61jl1D0JINTd6POz25F2YPYa7GuY0Duc7AIrXvbodff0GBl55KfuF/sxM5MbcwJrf35dnY/iCBWwSFdgMlvDkxWw975qff+M=,iv:b3pCPfT7CuYEsbVA95GNxfbDUDEh/L1coLLhi+xvfLw=,tag:0r/pOkoSO3XIEFoUP0kzGw==,type:str]
    pgp:
        - created_at: "2026-06-03T06:55:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ//deGXyM/QEYHMIa7tHWR5y87UalO3/S1VCVrnb4vXkq8C
            f7LRrUK5BwjCjDqW9dagPvJvxYHOHDLNyTrGynX9NSLU1Ny4avfbOmgdZeKhm+DK
            Ai4O9hqo1TuRp9VrMqe9r21KFp1jbDRjsEB5ttd98fot7aQKC2CKqhJS+5qWxbbx
            /2xNBo6j9eC8NAe0QmZGmow2mEMQWII9ZAd9IHoev6HeRQL16GeggZyWggwMikUw
            7hv5OP9jx8l/oGoxXXYwT5dx7fYxPG2CPjKIM+A634nNIQC0XMAuCObQMUl5z539
            XW9ih28nO+TDe/E97TCv4in82IaRBbJXrfa0FuwQcquLdXmfliFoOfYFFcp9HEGY
            nQK+v1yg7BNCLGeyZGgPcWO9T/Rq6jZsAiSuhgn7VOeWvLh8no0DENPXOvNZZPJh
            iXAHOPJ26XSGBHUTZR0n/07ySK5LgThA5eu+Hc8Bk2WTx8dQ+KhMhjj9kJr47RCT
            fVUuhFNezIiJw8OkPh1CTvK2vEq2HrLadOuo+/1iqbSkbKbRJQjSfW8Vxa3QWEDI
            3ObpvaGL3ayJVgPkAEG1XfdeL2hNLPzD+0gqWzbuXCQ7l5RBVpQgnQTgwPqOUi6W
            45ZAFUr2TGjOJ86Y3I4rGATLpImCm8mwe7SkQD8IR+TKYJvX8qq9aZe2IF5RKD/U
            WwEJAhCOtGJKozuua0JdMyWcI1bcny/DDQGkbpfQyvvbZUYWTw9yz8XOYwTiOqSE
            NYIT3j//lTt2+my6+jruOYCnHn1ce8XqOo5XJoiX0r9xvHdg72tfrwTKE4Q=
            =MA+p
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    version: 3.13.1
