---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: media
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-state
  namespace: media
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd
  resources:
    requests:
      storage: 1Gi
