apiVersion: v1
kind: Secret
metadata:
    name: ${BASE_DOMAIN/./-}-sso-client-secret
    namespace: debug
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:5/k7dlJzklzPt1t6EMPElNhOftZOXOP0ljfFxH+U1Pc=,iv:+DFTDun0upB1EP1+03gjsfS53DLMDUXVzBST4GcVucA=,tag:24dLWV2Zhr3O/a21MfudTg==,type:str]
sops:
    lastmodified: "2026-03-30T11:53:19Z"
    mac: ENC[AES256_GCM,data:JkyR9NSTAqwxrBLea7gooSYi8WxiuzGSJ/uwuqHlOkwx/j8jFKKCH/D5znDVXswTkIHF/dHdvP7zWhRsDi29PqV312yn8EEBA/2vC7ypEUldX5NyMtRW4RSwAVi8y+IDRaDMFeqbAAePn/VMcAIs2vHApknxAAIgHjWD5J+KtNg=,iv:TsbuyKjQBdSxnPwx3DLjL2SlCgyA9h8ZTY1tm2rLgwo=,tag:oWFCebsHL0J6SCRbyT090A==,type:str]
    pgp:
        - created_at: "2026-03-30T11:53:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAA0eqzs1YJVZY7X5PK3lNpUXVfpZYcYQuAasG9xUDdm5ED
            q46PpHASK3hfAIezTo/cRSj1Qd002wFY08bUi+LY1wSsX/5qKwHyVlXpIcew669P
            Fuzl20hyltpUPDMMINV6X/OSg49fhKN6Gpk1L6VxArStr9yIzf1ym4fya/bDQb64
            N7qCmqRjqCzdikwR7Aa5OOjXASiCG02SuuizL0ElDeyRc7iS+7OfEDm44v/3uml2
            /XgN0S27YhLLmal3ovGqDr/xPsPuorZyLGq2xTGQWKB/ETcDLyOX6PgsQ4eU61Dl
            j6FRkLdZRrqSoAI5Lo+sBWWbQ/qhMuB+cdH0XBwPSeoUNmdVqX+TjRQ9wmIum2md
            XFsA9BaDgQdBzs55EqXlhzW6I+jvbhKqhkRmrgRadC2tXMabaE0ZHb2lhTdKvaWh
            blTG1nb9omZ/SUzvxC5eTDks7+92rdMAWlGTTKfr2k8rn1209BO9b7wTUaOt2llu
            dw0pelVhaOVj0LkFfQWM6TS6k/sNGVy84StlEucHHRw6/mlaBz/wu5gKLLyvySaA
            EmfwGvO+3F+XmetyxZVp5FM1bZawV/JQMU6cXsEVpmI4s+QdMBryPWFgOxoZVMX+
            sMroaA9f19U/j5MhHZfuxyqHNQnUYHmgzNBesDrfBIK0YrRG5MPD1Yov20S/Su3U
            aAEJAhDg040chg7v1xYwfDUnTBetgeW2NRycrK0eakdLZRbGAQhUapvfgFG2boAY
            4xO/3czQ9t7mDf0wz0vOHiN7Tszi6oqnFnPUlvPC/j/Ds5AGn7PrHlZAlWBKPP/J
            w06RR72o9HDE
            =nxYF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.12.2
