apiVersion: v1
kind: Secret
metadata:
  name: ${BASE_DOMAIN/./-}-sso-client-secret
  namespace: debug
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:/WX2FohXLRQxnhSyrHB5IILIm9N1ioMiekFUUlERjkk=,iv:/GoJ3vbawMddb8Xf1ldwgPCzFMYYgYu9s9IkN8IunSg=,tag:fhdgRDZn78BQrKh5y024UA==,type:str]
sops:
  encrypted_regex: ^(data|stringData|customRequestHeaders)$
  lastmodified: "2026-06-29T15:35:03Z"
  mac: ENC[AES256_GCM,data:OokpF64OrwvfpDZWoHSbMb1Bc520JxX6FH9A30cXTRzWV+sQo3kzR4kIWlLdCYgxboE3WW9C1R+M3LoPVSKimpgQ0CGC6rWNsy4c8Cq/4Cqa/rUjlbSQxRUviMNb3504fRh98fg1MRD/Wt3FWRMpIAGBdqH/OBvrBcgqCZ+9sPY=,iv:neShuNj6npk7+VTq8gui7iaXS3iPDZgdjjktxota1ls=,tag:Qs0eFAmZsoWrC6zjgoSO1g==,type:str]
  pgp:
    - created_at: "2026-06-29T15:35:03Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAxCiAiPlgInVAQ/+J5AY0vNGr4HqK5rET5rqaAAV59isusREdaw/qY/kAexK
        NA++kxg3SabCirPx9SPnzgyG6XJm3RoJq6H2caw8VlJKntEiX33mF8ne4X8kIAY+
        jSY9jRh4O7tD2dnLbFPlWJSdO0HCQRzOcdAT35madeDUg6Kj9r7u5BZ8Qc3zLv8C
        /4H4EFJVUD8ck5+gGzP5Hoki4hblOA9HRmrImGg4F1IyjzTy0can7Ktnk43wylgR
        hnJtKrHbIFyr5/dQNZtvkb0Ye99Vin5o1AhkJXHngA2xmBglwljdmSSX+hOUrjg2
        MOfEY2OFaKe+9C/r6cn4F1JQjZXIUU2Gu2mNjBs2YQWqo1YObYKgfxBdAkMiWvmy
        mw+i7i3dQauiHQa4hNXqKJDYCU7AO1a/OoUwMa6SRr8jJabHt7U6uSg+XdD4f7xn
        3YpKoEN/fw4QLI6bDJkF/cf6Pkg0BYBnj1ds0oTadMGsMf3bRLCHC1FhBGssn4bO
        oRaZ68twe4IBfDzohFCNypmx+27tDJukH9w3Uvqx9jEWRi9hLwhNhQLXEPPzAY2C
        x/CsMUKSJeFmDZBjBaJc1WzF/O9AP37EisG3MD/G8nzTx9KTv9qTUViUTBSfJQKP
        A5it49e1BcImiMq6SFaVKu8Lm5L1CnYPlQdudNFV6olfqy6cEWXAc3qfhk0LPETU
        ZgEJAhC+N+PnHLo+gdCUeWvY/GvPnL/5QqGgXFUK+Bh5IP55f41UCCtjiEvfa8wv
        hrIKutX0katRhbp7DN4k55grP1IZEzaDnamAk2NSIEUSCjIj4JjhfW8s433TIAPS
        7G5Asq+0lA==
        =ubW2
        -----END PGP MESSAGE-----
      fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
  version: 3.13.1
