---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-viewer
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
    verbs:
      - get
      - list
  # CloudNativePG owners
  - apiGroups: ["postgresql.cnpg.io"]
    resources:
      - clusters
    verbs:
      - get
  # K8up owners
  - apiGroups: ["k8up.io"]
    resources:
      - prunes
    verbs:
      - get
