---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozzle
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dozzle
      app.kubernetes.io/instance: dozzle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dozzle
        app.kubernetes.io/instance: dozzle
    spec:
      serviceAccountName: pod-viewer
      containers:
        - name: dozzle
          image: amir20/dozzle:v10.6.11
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DOZZLE_MODE
              value: "k8s"
            - name: DOZZLE_AUTH_PROVIDER
              value: forward-proxy
            - name: DOZZLE_AUTH_HEADER_USER
              value: "X-Auth-Request-Email"
            - name: DOZZLE_AUTH_HEADER_EMAIL
              value: "X-Auth-Request-Email"
            - name: DOZZLE_AUTH_HEADER_NAME
              value: "X-Auth-Request-Email"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dozzle-data
