---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dozzle-data
  namespace: observability
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
