---
name: compatibility.fyi gate

"on":
  push:
    branches:
      - "renovate/**"
  schedule:
    - cron: "23 */6 * * *"
  workflow_dispatch:

jobs:
  gate:
    permissions:
      contents: read
      statuses: write
    uses: compatibility-fyi/compatibility-gate/.github/workflows/gate.yml@dd343c1416bf6fdc1c40f721c314a34276f4e583 # v1.1.1
    with:
      mode: ${{ github.event_name == 'push' && 'current' || 'all' }}
