---
name: compatibility.fyi gate

"on":
  push:
    branches:
      - "renovate/**"
  schedule:
    - cron: "23 */6 * * *"
  workflow_dispatch:

jobs:
  gate:
    permissions:
      contents: read
      statuses: write
    uses: compatibility-fyi/compatibility-gate/.github/workflows/gate.yml@c70e132dad832f45f4f6daa6943e2ec675433f6e # v1.1.3
    with:
      mode: ${{ github.event_name == 'push' && 'current' || 'all' }}
